using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

using Shouldly;
using Xunit;

using static Hexalith.FrontComposer.SourceTools.Tests.Drift.Comparison.DriftClassifierProjectionPropertyTests;

namespace Hexalith.FrontComposer.SourceTools.Tests.Drift.Regression;

/// <summary>
/// AC18 / T5 + T7 — generated outputs are byte-stable across:
/// (a) repeated runs,
/// (b) equivalent declaration-order permutations of the same source set,
/// (c) partial-type declaration ordering,
/// (d) equivalent baseline file enumeration order.
/// Drift detection adds diagnostics only — never rewrites generated output.
/// </summary>
public sealed class DriftByteStabilityRegressionTests {
    private const string SkipReason = "RED-PHASE: T5 + T7 — byte-stability regression harness pending Story 9-1 wiring.";

    private const string ValidBaseline = """
        { "schemaVersion": "frontcomposer.generated-ui-baseline.v1",
          "algorithm": "frontcomposer-structural-v1",
          "contracts": [{ "family": "projection", "type": "TestDomain.OrderProjection", "boundedContext": "Orders",
            "properties": [{ "name": "Id", "category": "String", "nullable": false }] }] }
        """;

    private const string ProjectionA = """
        using Hexalith.FrontComposer.Contracts.Attributes;
        namespace TestDomain;
        [BoundedContext("Orders")]
        [Projection]
        public partial class A { public string Id { get; set; } = string.Empty; }
        """;

    private const string ProjectionB = """
        using Hexalith.FrontComposer.Contracts.Attributes;
        namespace TestDomain;
        [BoundedContext("Orders")]
        [Projection]
        public partial class B { public string Id { get; set; } = string.Empty; }
        """;

    [Fact()]
    public void GeneratedOutput_IsByteIdenticalAcrossRepeatedRuns_WithBaselinePresent() {
        string[] runOne = RunAndCollectGenerated([ProjectionA, ProjectionB], ValidBaseline);
        string[] runTwo = RunAndCollectGenerated([ProjectionA, ProjectionB], ValidBaseline);

        runOne.Length.ShouldBe(runTwo.Length);
        for (int i = 0; i < runOne.Length; i++) {
            runOne[i].ShouldBe(runTwo[i], "AC18 — generated output must be byte-identical across repeated runs.");
        }
    }

    [Fact()]
    public void GeneratedOutput_IsByteIdenticalAcrossInputFileOrderPermutations() {
        string[] forward = RunAndCollectGenerated([ProjectionA, ProjectionB], ValidBaseline);
        string[] reverse = RunAndCollectGenerated([ProjectionB, ProjectionA], ValidBaseline);

        forward.ShouldBe(reverse, "AC18 — input file order must not change generated bytes.");
    }

    [Fact()]
    public void GeneratedOutput_IsByteIdenticalAcrossPartialDeclarationOrderPermutations() {
        const string partA = """
            using Hexalith.FrontComposer.Contracts.Attributes;
            namespace TestDomain;
            [BoundedContext("Orders")]
            [Projection]
            public partial class OrderProjection {
                public string Id { get; set; } = string.Empty;
            }
            """;
        const string partB = """
            namespace TestDomain;
            public partial class OrderProjection {
                public string Notes { get; set; } = string.Empty;
            }
            """;

        string[] forward = RunAndCollectGenerated([partA, partB], ValidBaseline);
        string[] reverse = RunAndCollectGenerated([partB, partA], ValidBaseline);

        forward.ShouldBe(reverse, "AC18 — partial-declaration order must not change generated bytes.");
    }

    [Fact()]
    public void GeneratedOutput_IsByteIdenticalAcrossEquivalentBaselineFileOrder() {
        const string baselineA = """
            { "schemaVersion": "frontcomposer.generated-ui-baseline.v1",
              "algorithm": "frontcomposer-structural-v1",
              "contracts": [{ "family": "projection", "type": "TestDomain.A", "boundedContext": "Orders",
                "properties": [{ "name": "Id", "category": "String", "nullable": false }] }] }
            """;
        const string baselineB = """
            { "schemaVersion": "frontcomposer.generated-ui-baseline.v1",
              "algorithm": "frontcomposer-structural-v1",
              "contracts": [{ "family": "projection", "type": "TestDomain.B", "boundedContext": "Orders",
                "properties": [{ "name": "Id", "category": "String", "nullable": false }] }] }
            """;

        string[] forward = RunAndCollectGeneratedMultiBaseline([ProjectionA, ProjectionB], [("a.json", baselineA), ("b.json", baselineB)]);
        string[] reverse = RunAndCollectGeneratedMultiBaseline([ProjectionA, ProjectionB], [("b.json", baselineB), ("a.json", baselineA)]);

        forward.ShouldBe(reverse, "AC18 — baseline file enumeration order must not change generated bytes.");
    }

    [Fact()]
    public void DriftDetection_DoesNotRewriteGeneratedOutput_ComparedToPreviousMaster() {
        // Activation: generate before T1-T7 land (master baseline) and compare to generation
        // after activation. Both must be byte-equal because Story 9-1 is diagnostics-only.
        string[] withDrift = RunAndCollectGenerated([ProjectionA], ValidBaseline);
        string[] withoutDrift = RunAndCollectGenerated([ProjectionA], baselineJson: null);

        withDrift.ShouldBe(withoutDrift,
            "AC18 — drift detection is diagnostics-only and MUST NOT alter generated output.");
    }

    private static string[] RunAndCollectGenerated(string[] sources, string? baselineJson) {
        CancellationToken ct = TestContext.Current.CancellationToken;
        CSharpCompilation compilation = CompilationHelper.CreateCompilation(sources);
        FrontComposerGenerator generator = new();
        AdditionalText[] texts = baselineJson is null
            ? []
            : [new InMemoryAdditionalText("frontcomposer.drift-baseline.json", baselineJson)];

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            generators: [generator.AsSourceGenerator()],
            additionalTexts: texts,
            optionsProvider: CompilationHelper.DriftEnabledOptions());
        driver = driver.RunGenerators(compilation, ct);

        return [.. driver.GetRunResult().GeneratedTrees
            .Select(t => t.GetText(ct).ToString())
            .OrderBy(s => s, StringComparer.Ordinal)];
    }

    private static string[] RunAndCollectGeneratedMultiBaseline(string[] sources, (string Path, string Content)[] baselines) {
        CancellationToken ct = TestContext.Current.CancellationToken;
        CSharpCompilation compilation = CompilationHelper.CreateCompilation(sources);
        FrontComposerGenerator generator = new();
        AdditionalText[] texts = [.. baselines.Select(b => (AdditionalText)new InMemoryAdditionalText(b.Path, b.Content))];

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            generators: [generator.AsSourceGenerator()],
            additionalTexts: texts,
            optionsProvider: CompilationHelper.DriftEnabledOptions());
        driver = driver.RunGenerators(compilation, ct);

        return [.. driver.GetRunResult().GeneratedTrees
            .Select(t => t.GetText(ct).ToString())
            .OrderBy(s => s, StringComparer.Ordinal)];
    }
}
