using System.Globalization;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

using Shouldly;

using static Hexalith.FrontComposer.SourceTools.Tests.Drift.DriftTestFixtures;

namespace Hexalith.FrontComposer.SourceTools.Tests.Drift.Regression;

/// <summary>
/// AC19 / T7 — culture invariance.
/// </summary>
[Collection(DriftCultureTestGroup.Name)]
public sealed class DriftCultureInvarianceTests {
    private const string ValidBaseline = """
        { "schemaVersion": "frontcomposer.generated-ui-baseline.v1",
          "algorithm": "frontcomposer-structural-v1",
          "contracts": [{ "family": "projection", "type": "TestDomain.OrderProjection", "boundedContext": "Orders",
            "properties": [
              { "name": "Id",         "category": "String", "nullable": false, "columnPriority": 0 },
              { "name": "Identifier", "category": "String", "nullable": false, "columnPriority": 1 },
              { "name": "Priority",   "category": "Int32",  "nullable": false, "columnPriority": 2 }
            ] }] }
        """;

    private const string DriftedSource = """
        using Hexalith.FrontComposer.Contracts.Attributes;
        namespace TestDomain;
        [BoundedContext("Orders")]
        [Projection]
        public partial class OrderProjection {
            // CH-8 — `Id`/`Identifier` exercises tr-TR dotted-I; `İdentifier` (mistyped removal)
            // would mis-classify under culture-sensitive `ToUpper`/`ToLower`.
            public string Id { get; set; } = string.Empty;
            public string Identifier { get; set; } = string.Empty;
            public int Priority { get; set; }
            public string AddedField { get; set; } = string.Empty;
        }
        """;

    [Theory]
    // CH-9 — exercise cultures with numeric-formatting divergence (de-DE comma decimal,
    // fa-IR Persian numerals) and casing divergence (tr-TR dotted-I).
    [InlineData("fr-FR")]
    [InlineData("tr-TR")]
    [InlineData("de-DE")]
    [InlineData("fa-IR")]
    public void DriftDiagnostics_AreInvariantUnderNonDefaultCulture(string cultureName) {
        IReadOnlyList<Diagnostic> invariant = RunUnderCulture(CultureInfo.InvariantCulture);
        IReadOnlyList<Diagnostic> scoped = RunUnderCulture(new CultureInfo(cultureName));

        // CH-2 — restrict to the drift HFC range, not all HFC10xx.
        Diagnostic[] invariantDrifts = [.. invariant.Where(d => IsDriftDiagnostic(d.Id))];
        Diagnostic[] scopedDrifts = [.. scoped.Where(d => IsDriftDiagnostic(d.Id))];

        invariantDrifts.Length.ShouldBeGreaterThan(0,
            "Test setup: expected drift diagnostics from the AddedField property.");
        invariantDrifts.Length.ShouldBe(scopedDrifts.Length,
            $"AC19 — drift diagnostic count must be culture-invariant under {cultureName}.");

        // CH-1 — sort before pairing so culture-induced ordering changes (the bug under test) don't
        // mis-pair items.
        invariantDrifts = [.. invariantDrifts.OrderBy(DiagnosticSortKey, StringComparer.Ordinal)];
        scopedDrifts = [.. scopedDrifts.OrderBy(DiagnosticSortKey, StringComparer.Ordinal)];

        for (int i = 0; i < invariantDrifts.Length; i++) {
            // CC-9 — full message text invariance, including formatted numerics.
            invariantDrifts[i].Id.ShouldBe(scopedDrifts[i].Id,
                $"AC19 — diagnostic ID at index {i} must be culture-invariant under {cultureName}.");
            invariantDrifts[i].GetMessage(CultureInfo.InvariantCulture).ShouldBe(
                scopedDrifts[i].GetMessage(CultureInfo.InvariantCulture),
                $"AC19 — diagnostic message at index {i} must be culture-invariant under {cultureName}.");

            // CM-7 — also pin the property bag (which carries hashes and numeric values).
            foreach (KeyValuePair<string, string?> p in invariantDrifts[i].Properties) {
                scopedDrifts[i].Properties[p.Key].ShouldBe(p.Value,
                    $"AC19 — diagnostic property '{p.Key}' at index {i} must be culture-invariant under {cultureName}.");
            }
        }
    }

    [Theory]
    [InlineData("fr-FR")]
    [InlineData("tr-TR")]
    [InlineData("de-DE")]
    [InlineData("fa-IR")]
    public void GeneratedBytes_AreInvariantUnderNonDefaultCulture(string cultureName) {
        // CC-1 — compare in emit order including hint names; sorting masks ordering churn.
        (string Hint, string Source)[] invariantBytes = RunGeneratedUnderCulture(CultureInfo.InvariantCulture);
        (string Hint, string Source)[] scopedBytes = RunGeneratedUnderCulture(new CultureInfo(cultureName));

        invariantBytes.ShouldBe(scopedBytes,
            $"AC19 — generated bytes (hint+source, in emit order) must be identical under {cultureName}.");
    }

    private static string DiagnosticSortKey(Diagnostic d) {
        string declaration = d.Properties.TryGetValue("DeclarationName", out string? dn) ? dn ?? string.Empty : string.Empty;
        string member = d.Properties.TryGetValue("MemberName", out string? mn) ? mn ?? string.Empty : string.Empty;
        return $"{d.Id}|{declaration}|{member}";
    }

    private static bool IsDriftDiagnostic(string id)
        => id.Length == 7
        && id.StartsWith("HFC", StringComparison.Ordinal)
        && int.TryParse(id.AsSpan("HFC".Length), NumberStyles.None, CultureInfo.InvariantCulture, out int n)
        && n is >= 1058 and <= 1099;

    private static IReadOnlyList<Diagnostic> RunUnderCulture(CultureInfo culture) {
        CultureInfo prior = CultureInfo.CurrentCulture;
        CultureInfo priorUi = CultureInfo.CurrentUICulture;
        try {
            // CH-3 — DefaultThreadCurrentCulture sets the default for new threads in the AppDomain;
            // combined with the [Collection] non-parallel attribute on the test class, this provides
            // process-wide isolation while the test executes.
            CultureInfo.CurrentCulture = culture;
            CultureInfo.CurrentUICulture = culture;
            CultureInfo.DefaultThreadCurrentCulture = culture;
            CultureInfo.DefaultThreadCurrentUICulture = culture;

            CancellationToken ct = TestContext.Current.CancellationToken;
            CSharpCompilation compilation = CompilationHelper.CreateCompilation(DriftedSource);
            FrontComposerGenerator generator = new();
            AdditionalText baselineText = new InMemoryAdditionalText("frontcomposer.drift-baseline.json", ValidBaseline);
            GeneratorDriver driver = CSharpGeneratorDriver.Create(
                generators: [generator.AsSourceGenerator()],
                additionalTexts: [baselineText],
                optionsProvider: CompilationHelper.DriftEnabledOptions());
            driver = driver.RunGenerators(compilation, ct);
            return driver.GetRunResult().Diagnostics;
        }
        finally {
            CultureInfo.CurrentCulture = prior;
            CultureInfo.CurrentUICulture = priorUi;
            CultureInfo.DefaultThreadCurrentCulture = null;
            CultureInfo.DefaultThreadCurrentUICulture = null;
        }
    }

    private static (string Hint, string Source)[] RunGeneratedUnderCulture(CultureInfo culture) {
        CultureInfo prior = CultureInfo.CurrentCulture;
        CultureInfo priorUi = CultureInfo.CurrentUICulture;
        try {
            CultureInfo.CurrentCulture = culture;
            CultureInfo.CurrentUICulture = culture;
            CultureInfo.DefaultThreadCurrentCulture = culture;
            CultureInfo.DefaultThreadCurrentUICulture = culture;

            CancellationToken ct = TestContext.Current.CancellationToken;
            CSharpCompilation compilation = CompilationHelper.CreateCompilation(DriftedSource);
            FrontComposerGenerator generator = new();
            AdditionalText baselineText = new InMemoryAdditionalText("frontcomposer.drift-baseline.json", ValidBaseline);
            GeneratorDriver driver = CSharpGeneratorDriver.Create(
                generators: [generator.AsSourceGenerator()],
                additionalTexts: [baselineText],
                optionsProvider: CompilationHelper.DriftEnabledOptions());
            driver = driver.RunGenerators(compilation, ct);

            GeneratorRunResult result = driver.GetRunResult().Results[0];
            return [.. result.GeneratedSources.Select(s => (s.HintName, s.SourceText.ToString()))];
        }
        finally {
            CultureInfo.CurrentCulture = prior;
            CultureInfo.CurrentUICulture = priorUi;
            CultureInfo.DefaultThreadCurrentCulture = null;
            CultureInfo.DefaultThreadCurrentUICulture = null;
        }
    }
}
