using Hexalith.FrontComposer.Contracts.Diagnostics;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;

using Shouldly;

using static Hexalith.FrontComposer.SourceTools.Tests.Drift.DriftTestFixtures;

namespace Hexalith.FrontComposer.SourceTools.Tests.Drift.Regression;

/// <summary>
/// AC18 / T5 + T7 — generated outputs are byte-stable. Drift detection adds diagnostics only.
/// </summary>
[Trait("Category", "MutationErrorHandling")]
public sealed class DriftByteStabilityRegressionTests {
    private const string ValidBaseline = """
        { "schemaVersion": "frontcomposer.generated-ui-baseline.v1",
          "algorithm": "frontcomposer-structural-v1",
          "contracts": [{ "family": "projection", "type": "TestDomain.OrderProjection", "boundedContext": "Orders",
            "properties": [{ "name": "Id", "category": "String", "nullable": false }] }] }
        """;

    private const string ProjectionA = """
        using Hexalith.FrontComposer.Contracts.Attributes;
        namespace TestDomain;
        [BoundedContext("Orders")]
        [Projection]
        public partial class A { public string Id { get; set; } = string.Empty; }
        """;

    private const string ProjectionB = """
        using Hexalith.FrontComposer.Contracts.Attributes;
        namespace TestDomain;
        [BoundedContext("Orders")]
        [Projection]
        public partial class B { public string Id { get; set; } = string.Empty; }
        """;

    [Fact]
    public void GeneratedOutput_IsByteIdenticalAcrossRepeatedRuns_WithBaselinePresent() {
        // CC-1 — no sort: compare in emit order including hint names so an ordering churn shows.
        (string Hint, string Source)[] runOne = RunAndCollectGenerated([ProjectionA, ProjectionB], ValidBaseline);
        (string Hint, string Source)[] runTwo = RunAndCollectGenerated([ProjectionA, ProjectionB], ValidBaseline);

        runOne.ShouldBe(runTwo, "AC18 — generated output (hint+source, in emit order) must be byte-identical across repeated runs.");
    }

    [Fact]
    public void GeneratedOutput_IsByteIdenticalAcrossInputFileOrderPermutations() {
        (string Hint, string Source)[] forward = RunAndCollectGenerated([ProjectionA, ProjectionB], ValidBaseline);
        (string Hint, string Source)[] reverse = RunAndCollectGenerated([ProjectionB, ProjectionA], ValidBaseline);

        // Order-equivalence: file order must not change the generated set, but emit order may
        // depend on input order. Compare as sets keyed by hint name.
        Dictionary<string, string> forwardMap = forward.ToDictionary(t => t.Hint, t => t.Source, StringComparer.Ordinal);
        Dictionary<string, string> reverseMap = reverse.ToDictionary(t => t.Hint, t => t.Source, StringComparer.Ordinal);
        forwardMap.Keys.OrderBy(k => k, StringComparer.Ordinal)
            .ShouldBe(reverseMap.Keys.OrderBy(k => k, StringComparer.Ordinal),
                "AC18 — input file order must not change the set of emitted hint names.");
        foreach (string hint in forwardMap.Keys) {
            forwardMap[hint].ShouldBe(reverseMap[hint],
                $"AC18 — input file order must not change generated bytes (hint={hint}).");
        }
    }

    [Fact]
    public void GeneratedOutput_IsByteIdenticalAcrossPartialDeclarationOrderPermutations() {
        const string partA = """
            using Hexalith.FrontComposer.Contracts.Attributes;
            namespace TestDomain;
            [BoundedContext("Orders")]
            [Projection]
            public partial class OrderProjection {
                public string Id { get; set; } = string.Empty;
            }
            """;
        const string partB = """
            namespace TestDomain;
            public partial class OrderProjection {
                public string Notes { get; set; } = string.Empty;
            }
            """;

        (string Hint, string Source)[] forward = RunAndCollectGenerated([partA, partB], ValidBaseline);
        (string Hint, string Source)[] reverse = RunAndCollectGenerated([partB, partA], ValidBaseline);

        AssertSameSetByHint(forward, reverse, "AC18 — partial-declaration order must not change generated bytes.");
    }

    [Fact]
    public void DriftDiagnostics_AgainstSamePartials_AreInvariantToPartialOrder() {
        // CM-16 — partial-declaration order also must not change drift comparison.
        const string partA = """
            using Hexalith.FrontComposer.Contracts.Attributes;
            namespace TestDomain;
            [BoundedContext("Orders")]
            [Projection]
            public partial class OrderProjection {
                public string Id { get; set; } = string.Empty;
            }
            """;
        const string partB = """
            namespace TestDomain;
            public partial class OrderProjection {
                public string AddedField { get; set; } = string.Empty;
            }
            """;

        IReadOnlyList<Diagnostic> forward = RunAndCollectDriftDiagnostics([partA, partB], ValidBaseline);
        IReadOnlyList<Diagnostic> reverse = RunAndCollectDriftDiagnostics([partB, partA], ValidBaseline);

        forward.Select(d => d.Id + "|" + d.GetMessage(System.Globalization.CultureInfo.InvariantCulture))
            .OrderBy(s => s, StringComparer.Ordinal)
            .ShouldBe(reverse.Select(d => d.Id + "|" + d.GetMessage(System.Globalization.CultureInfo.InvariantCulture))
                .OrderBy(s => s, StringComparer.Ordinal),
                "AC18 — drift diagnostics must be invariant to partial-declaration order.");
    }

    [Fact]
    public void GeneratedOutput_IsByteIdenticalAcrossEquivalentBaselineFileOrder() {
        const string baselineA = """
            { "schemaVersion": "frontcomposer.generated-ui-baseline.v1",
              "algorithm": "frontcomposer-structural-v1",
              "contracts": [{ "family": "projection", "type": "TestDomain.A", "boundedContext": "Orders",
                "properties": [{ "name": "Id", "category": "String", "nullable": false }] }] }
            """;
        const string baselineB = """
            { "schemaVersion": "frontcomposer.generated-ui-baseline.v1",
              "algorithm": "frontcomposer-structural-v1",
              "contracts": [{ "family": "projection", "type": "TestDomain.B", "boundedContext": "Orders",
                "properties": [{ "name": "Id", "category": "String", "nullable": false }] }] }
            """;

        (string Hint, string Source)[] forward = RunAndCollectGeneratedMultiBaseline(
            [ProjectionA, ProjectionB],
            [("frontcomposer.drift-baseline-a.json", baselineA),
             ("frontcomposer.drift-baseline-b.json", baselineB)]);
        (string Hint, string Source)[] reverse = RunAndCollectGeneratedMultiBaseline(
            [ProjectionA, ProjectionB],
            [("frontcomposer.drift-baseline-b.json", baselineB),
             ("frontcomposer.drift-baseline-a.json", baselineA)]);

        AssertSameSetByHint(forward, reverse, "AC18 — baseline file enumeration order must not change generated bytes.");
    }

    [Fact]
    public void DuplicateBaselineIdentity_AcrossFiles_IsRejectedDeterministicallyInBothOrders() {
        // CM-9 — AC9 deterministic-fail-closed under file-order swap.
        const string baselineDup1 = """
            { "schemaVersion": "frontcomposer.generated-ui-baseline.v1",
              "algorithm": "frontcomposer-structural-v1",
              "contracts": [{ "family": "projection", "type": "TestDomain.A", "boundedContext": "Orders",
                "properties": [{ "name": "Id", "category": "String", "nullable": false }] }] }
            """;
        const string baselineDup2 = """
            { "schemaVersion": "frontcomposer.generated-ui-baseline.v1",
              "algorithm": "frontcomposer-structural-v1",
              "contracts": [{ "family": "projection", "type": "TestDomain.A", "boundedContext": "Orders",
                "properties": [{ "name": "Notes", "category": "String", "nullable": true }] }] }
            """;

        // Baselines must use the documented `frontcomposer.drift-baseline*.json` prefix
        // (Story 9-1 P5) to be recognized as drift baselines.
        IReadOnlyList<Diagnostic> forward = RunAndCollectDriftDiagnosticsMultiBaseline(
            [ProjectionA],
            [("frontcomposer.drift-baseline-dup1.json", baselineDup1),
             ("frontcomposer.drift-baseline-dup2.json", baselineDup2)]);
        IReadOnlyList<Diagnostic> reverse = RunAndCollectDriftDiagnosticsMultiBaseline(
            [ProjectionA],
            [("frontcomposer.drift-baseline-dup2.json", baselineDup2),
             ("frontcomposer.drift-baseline-dup1.json", baselineDup1)]);

        // HFC1064 (BaselineIdentityInvalid) MUST fire in both orderings deterministically.
        forward.Any(d => d.Id == FcDiagnosticIds.HFC1064_GeneratedUiBaselineIdentityInvalid).ShouldBeTrue(
            "AC9 — duplicate baseline identity must produce HFC1064.");
        reverse.Any(d => d.Id == FcDiagnosticIds.HFC1064_GeneratedUiBaselineIdentityInvalid).ShouldBeTrue(
            "AC9 — duplicate baseline identity must produce HFC1064 regardless of file order.");
    }

    [Fact]
    public void DriftDetection_DoesNotRewriteGeneratedOutput_GateOffVsGateOn() {
        // CC-2 — compare HfcDriftDetectionEnabled=false vs =true with the same source AND
        // baseline. Both must emit byte-identical generated output: drift is diagnostics-only.
        (string Hint, string Source)[] gateOff = RunAndCollectGenerated([ProjectionA], ValidBaseline, driftEnabled: false);
        (string Hint, string Source)[] gateOn = RunAndCollectGenerated([ProjectionA], ValidBaseline, driftEnabled: true);

        AssertSameSetByHint(gateOff, gateOn,
            "AC18 — drift detection is diagnostics-only and MUST NOT alter generated output.");
    }

    [Fact]
    public void GateOff_EmitsNoDriftDiagnostics() {
        // CL-6 — when drift is gated off, no diagnostics in the drift HFC range escape.
        IReadOnlyList<Diagnostic> diagnostics = RunAndCollectAllDiagnostics([ProjectionA], ValidBaseline, driftEnabled: false);
        Diagnostic[] driftDiagnostics = [.. diagnostics.Where(d => IsDriftDiagnostic(d.Id))];
        driftDiagnostics.ShouldBeEmpty(
            "AC18 — gate-off path must produce zero drift diagnostics (current: " + string.Join(", ", driftDiagnostics.Select(d => d.Id)) + ").");
    }

    [Fact]
    public void DriftDiagnosticOrdering_IsByteStableAcrossRepeatedRuns() {
        // CH-10 — make the harness produce drift diagnostics so ordering instability is exposed.
        const string driftedSource = """
            using Hexalith.FrontComposer.Contracts.Attributes;
            namespace TestDomain;
            [BoundedContext("Orders")]
            [Projection]
            public partial class OrderProjection {
                public string Id { get; set; } = string.Empty;
                public string AddedFieldOne { get; set; } = string.Empty;
                public string AddedFieldTwo { get; set; } = string.Empty;
            }
            """;

        IReadOnlyList<Diagnostic> runOne = RunAndCollectDriftDiagnostics([driftedSource], ValidBaseline);
        IReadOnlyList<Diagnostic> runTwo = RunAndCollectDriftDiagnostics([driftedSource], ValidBaseline);

        // Compare as ordered sequences — sort masks the very ordering bug AC18 forbids.
        runOne.Count.ShouldBeGreaterThan(0, "Test setup: expected drift diagnostics from added properties.");
        runOne.Select(d => d.Id).ShouldBe(runTwo.Select(d => d.Id),
            "AC18 — diagnostic emission order must be byte-stable across repeated runs.");
    }

    [Fact]
    public void GeneratedOutput_BomVsNoBom_IsByteIdentical() {
        // CH-11 — production strips UTF-8 BOM (DriftDetection.cs ~480-496); a regression must show.
        string bomBaseline = "﻿" + ValidBaseline;
        (string Hint, string Source)[] withBom = RunAndCollectGenerated([ProjectionA], bomBaseline);
        (string Hint, string Source)[] withoutBom = RunAndCollectGenerated([ProjectionA], ValidBaseline);

        AssertSameSetByHint(withBom, withoutBom,
            "AC18 — UTF-8 BOM on the baseline must not affect generated output.");
    }

    [Fact]
    public void GeneratedOutput_CrlfVsLfBaseline_IsByteIdentical() {
        // CH-11 — CRLF vs LF in baseline JSON must round-trip identically.
        string crlfBaseline = ValidBaseline.Replace("\n", "\r\n", StringComparison.Ordinal);
        (string Hint, string Source)[] crlf = RunAndCollectGenerated([ProjectionA], crlfBaseline);
        (string Hint, string Source)[] lf = RunAndCollectGenerated([ProjectionA], ValidBaseline);

        AssertSameSetByHint(crlf, lf,
            "AC18 — line-ending convention in baseline must not affect generated output.");
    }

    private static (string Hint, string Source)[] RunAndCollectGenerated(string[] sources, string? baselineJson, bool driftEnabled = true) {
        CancellationToken ct = TestContext.Current.CancellationToken;
        CSharpCompilation compilation = CompilationHelper.CreateCompilation(sources);
        FrontComposerGenerator generator = new();
        AdditionalText[] texts = baselineJson is null
            ? []
            : [new InMemoryAdditionalText("frontcomposer.drift-baseline.json", baselineJson)];

        AnalyzerConfigOptionsProvider options = driftEnabled
            ? CompilationHelper.DriftEnabledOptions()
            : EmptyOptionsProvider.Instance;
        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            generators: [generator.AsSourceGenerator()],
            additionalTexts: texts,
            optionsProvider: options);
        driver = driver.RunGenerators(compilation, ct);

        GeneratorRunResult result = driver.GetRunResult().Results[0];
        return [.. result.GeneratedSources.Select(s => (s.HintName, s.SourceText.ToString()))];
    }

    private static (string Hint, string Source)[] RunAndCollectGeneratedMultiBaseline(string[] sources, (string Path, string Content)[] baselines) {
        CancellationToken ct = TestContext.Current.CancellationToken;
        CSharpCompilation compilation = CompilationHelper.CreateCompilation(sources);
        FrontComposerGenerator generator = new();
        AdditionalText[] texts = [.. baselines.Select(b => (AdditionalText)new InMemoryAdditionalText(b.Path, b.Content))];

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            generators: [generator.AsSourceGenerator()],
            additionalTexts: texts,
            optionsProvider: CompilationHelper.DriftEnabledOptions());
        driver = driver.RunGenerators(compilation, ct);

        GeneratorRunResult result = driver.GetRunResult().Results[0];
        return [.. result.GeneratedSources.Select(s => (s.HintName, s.SourceText.ToString()))];
    }

    private static IReadOnlyList<Diagnostic> RunAndCollectDriftDiagnostics(string[] sources, string baselineJson) {
        CancellationToken ct = TestContext.Current.CancellationToken;
        CSharpCompilation compilation = CompilationHelper.CreateCompilation(sources);
        FrontComposerGenerator generator = new();
        AdditionalText baseline = new InMemoryAdditionalText("frontcomposer.drift-baseline.json", baselineJson);

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            generators: [generator.AsSourceGenerator()],
            additionalTexts: [baseline],
            optionsProvider: CompilationHelper.DriftEnabledOptions());
        driver = driver.RunGenerators(compilation, ct);

        return [.. driver.GetRunResult().Diagnostics.Where(d => IsDriftDiagnostic(d.Id))];
    }

    private static IReadOnlyList<Diagnostic> RunAndCollectDriftDiagnosticsMultiBaseline(string[] sources, (string Path, string Content)[] baselines) {
        CancellationToken ct = TestContext.Current.CancellationToken;
        CSharpCompilation compilation = CompilationHelper.CreateCompilation(sources);
        FrontComposerGenerator generator = new();
        AdditionalText[] texts = [.. baselines.Select(b => (AdditionalText)new InMemoryAdditionalText(b.Path, b.Content))];

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            generators: [generator.AsSourceGenerator()],
            additionalTexts: texts,
            optionsProvider: CompilationHelper.DriftEnabledOptions());
        driver = driver.RunGenerators(compilation, ct);

        return [.. driver.GetRunResult().Diagnostics.Where(d => IsDriftDiagnostic(d.Id))];
    }

    private static IReadOnlyList<Diagnostic> RunAndCollectAllDiagnostics(string[] sources, string baselineJson, bool driftEnabled) {
        CancellationToken ct = TestContext.Current.CancellationToken;
        CSharpCompilation compilation = CompilationHelper.CreateCompilation(sources);
        FrontComposerGenerator generator = new();
        AdditionalText baseline = new InMemoryAdditionalText("frontcomposer.drift-baseline.json", baselineJson);

        AnalyzerConfigOptionsProvider options = driftEnabled
            ? CompilationHelper.DriftEnabledOptions()
            : EmptyOptionsProvider.Instance;
        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            generators: [generator.AsSourceGenerator()],
            additionalTexts: [baseline],
            optionsProvider: options);
        driver = driver.RunGenerators(compilation, ct);
        return driver.GetRunResult().Diagnostics;
    }

    private static bool IsDriftDiagnostic(string id)
        => id.Length == 7
        && id.StartsWith("HFC", StringComparison.Ordinal)
        && int.TryParse(id.AsSpan("HFC".Length), System.Globalization.NumberStyles.None, System.Globalization.CultureInfo.InvariantCulture, out int n)
        && n is >= 1058 and <= 1099;

    private static void AssertSameSetByHint((string Hint, string Source)[] left, (string Hint, string Source)[] right, string message) {
        Dictionary<string, string> leftMap = left.ToDictionary(t => t.Hint, t => t.Source, StringComparer.Ordinal);
        Dictionary<string, string> rightMap = right.ToDictionary(t => t.Hint, t => t.Source, StringComparer.Ordinal);
        leftMap.Keys.OrderBy(k => k, StringComparer.Ordinal)
            .ShouldBe(rightMap.Keys.OrderBy(k => k, StringComparer.Ordinal), message);
        foreach (string hint in leftMap.Keys) {
            leftMap[hint].ShouldBe(rightMap[hint], $"{message} (hint={hint})");
        }
    }

    private sealed class EmptyOptionsProvider : AnalyzerConfigOptionsProvider {
        internal static EmptyOptionsProvider Instance { get; } = new();

        public override AnalyzerConfigOptions GlobalOptions { get; } = new EmptyOptions();
        public override AnalyzerConfigOptions GetOptions(SyntaxTree tree) => GlobalOptions;
        public override AnalyzerConfigOptions GetOptions(AdditionalText textFile) => GlobalOptions;

        private sealed class EmptyOptions : AnalyzerConfigOptions {
            public override bool TryGetValue(string key, out string value) {
                value = string.Empty;
                return false;
            }
        }
    }
}
