using System.Globalization;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

using Shouldly;
using Xunit;

using static Hexalith.FrontComposer.SourceTools.Tests.Drift.Comparison.DriftClassifierProjectionPropertyTests;

namespace Hexalith.FrontComposer.SourceTools.Tests.Drift.Regression;

/// <summary>
/// AC19 / T7 — culture invariance. Under non-default cultures (`fr-FR`, `tr-TR`):
/// classification, sorting, hashes, numeric formatting in messages and properties, diagnostics,
/// and generated bytes must remain identical to the invariant baseline.
/// </summary>
public sealed class DriftCultureInvarianceTests {
    private const string SkipReason = "RED-PHASE: T7 — culture-invariant pipeline pending.";

    private const string ValidBaseline = """
        { "schemaVersion": "frontcomposer.generated-ui-baseline.v1",
          "algorithm": "frontcomposer-structural-v1",
          "contracts": [{ "family": "projection", "type": "TestDomain.OrderProjection", "boundedContext": "Orders",
            "properties": [
              { "name": "Id",       "category": "String", "nullable": false, "columnPriority": 0 },
              { "name": "Priority", "category": "Int32",  "nullable": false, "columnPriority": 1 }
            ] }] }
        """;

    private const string Source = """
        using Hexalith.FrontComposer.Contracts.Attributes;
        namespace TestDomain;
        [BoundedContext("Orders")]
        [Projection]
        public partial class OrderProjection {
            public string Id { get; set; } = string.Empty;
            public int Priority { get; set; }
            public string Added { get; set; } = string.Empty;
        }
        """;

    [Theory(Skip = SkipReason)]
    [InlineData("fr-FR")]
    [InlineData("tr-TR")]
    public void DiagnosticIds_AreInvariantUnderNonDefaultCulture(string cultureName) {
        IReadOnlyList<Diagnostic> invariant = RunUnderCulture(CultureInfo.InvariantCulture);
        IReadOnlyList<Diagnostic> scoped = RunUnderCulture(new CultureInfo(cultureName));

        invariant.Select(d => d.Id).OrderBy(s => s, StringComparer.Ordinal)
            .ShouldBe(scoped.Select(d => d.Id).OrderBy(s => s, StringComparer.Ordinal),
                $"AC19 — diagnostic IDs must be identical under {cultureName}.");
    }

    [Theory(Skip = SkipReason)]
    [InlineData("fr-FR")]
    [InlineData("tr-TR")]
    public void DiagnosticPropertyValues_AreInvariantUnderNonDefaultCulture(string cultureName) {
        IReadOnlyList<Diagnostic> invariant = RunUnderCulture(CultureInfo.InvariantCulture);
        IReadOnlyList<Diagnostic> scoped = RunUnderCulture(new CultureInfo(cultureName));

        Diagnostic[] invariantDrifts = [.. invariant.Where(d => d.Id.StartsWith("HFC10", StringComparison.Ordinal))];
        Diagnostic[] scopedDrifts = [.. scoped.Where(d => d.Id.StartsWith("HFC10", StringComparison.Ordinal))];
        invariantDrifts.Length.ShouldBe(scopedDrifts.Length);

        for (int i = 0; i < invariantDrifts.Length; i++) {
            foreach (KeyValuePair<string, string?> p in invariantDrifts[i].Properties) {
                scopedDrifts[i].Properties[p.Key].ShouldBe(p.Value,
                    $"AC19 — diagnostic property '{p.Key}' must be culture-invariant under {cultureName}.");
            }
        }
    }

    [Theory(Skip = SkipReason)]
    [InlineData("fr-FR")]
    [InlineData("tr-TR")]
    public void GeneratedBytes_AreInvariantUnderNonDefaultCulture(string cultureName) {
        string[] invariantBytes = RunGeneratedUnderCulture(CultureInfo.InvariantCulture);
        string[] scopedBytes = RunGeneratedUnderCulture(new CultureInfo(cultureName));

        invariantBytes.ShouldBe(scopedBytes, $"AC19 — generated bytes must be identical under {cultureName}.");
    }

    private static IReadOnlyList<Diagnostic> RunUnderCulture(CultureInfo culture) {
        CultureInfo prior = CultureInfo.CurrentCulture;
        CultureInfo priorUi = CultureInfo.CurrentUICulture;
        try {
            CultureInfo.CurrentCulture = culture;
            CultureInfo.CurrentUICulture = culture;

            CancellationToken ct = TestContext.Current.CancellationToken;
            CSharpCompilation compilation = CompilationHelper.CreateCompilation(Source);
            FrontComposerGenerator generator = new();
            AdditionalText baselineText = new InMemoryAdditionalText("frontcomposer.drift-baseline.json", ValidBaseline);
            GeneratorDriver driver = CSharpGeneratorDriver.Create(
                generators: [generator.AsSourceGenerator()], additionalTexts: [baselineText]);
            driver = driver.RunGenerators(compilation, ct);
            return driver.GetRunResult().Diagnostics;
        }
        finally {
            CultureInfo.CurrentCulture = prior;
            CultureInfo.CurrentUICulture = priorUi;
        }
    }

    private static string[] RunGeneratedUnderCulture(CultureInfo culture) {
        CultureInfo prior = CultureInfo.CurrentCulture;
        CultureInfo priorUi = CultureInfo.CurrentUICulture;
        try {
            CultureInfo.CurrentCulture = culture;
            CultureInfo.CurrentUICulture = culture;

            CancellationToken ct = TestContext.Current.CancellationToken;
            CSharpCompilation compilation = CompilationHelper.CreateCompilation(Source);
            FrontComposerGenerator generator = new();
            AdditionalText baselineText = new InMemoryAdditionalText("frontcomposer.drift-baseline.json", ValidBaseline);
            GeneratorDriver driver = CSharpGeneratorDriver.Create(
                generators: [generator.AsSourceGenerator()], additionalTexts: [baselineText]);
            driver = driver.RunGenerators(compilation, ct);
            return [.. driver.GetRunResult().GeneratedTrees
                .Select(t => t.GetText(ct).ToString())
                .OrderBy(s => s, StringComparer.Ordinal)];
        }
        finally {
            CultureInfo.CurrentCulture = prior;
            CultureInfo.CurrentUICulture = priorUi;
        }
    }
}
