using System.Text;

using Hexalith.FrontComposer.SourceTools.Transforms;

namespace Hexalith.FrontComposer.SourceTools.Emitters;

/// <summary>
/// Story 2-3 Decision D4/D16: emits <c>{CommandTypeName}LifecycleBridge.g.cs</c> per <c>[Command]</c>.
/// The bridge subscribes to the six per-command Fluxor actions and forwards them to
/// <c>ILifecycleStateService.Transition(correlationId, state, messageId)</c> so the service owns a
/// cross-command correlation-keyed index (ADR-017). Namespace mirrors the command's namespace.
/// </summary>
public static class CommandLifecycleBridgeEmitter {
    /// <summary>
    /// Generates the bridge source for a single <see cref="CommandFluxorModel"/>.
    /// </summary>
    /// <param name="model">The Fluxor model for the command — supplies <c>ActionsWrapperName</c>.</param>
    /// <returns>The generated C# source.</returns>
    public static string Emit(CommandFluxorModel model) {
        StringBuilder sb = new(2048);
        _ = sb.AppendLine("// Generated by FrontComposer source generator");
        _ = sb.AppendLine("// Do not edit directly");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace) {
            _ = sb.AppendLine("namespace " + model.Namespace + ";");
            _ = sb.AppendLine();
        }

        string bridgeTypeName = model.TypeName + "LifecycleBridge";

        _ = sb.AppendLine("/// <summary>Story 2-3 Decision D4: per-command lifecycle bridge forwarding Fluxor actions to <see cref=\"global::Hexalith.FrontComposer.Contracts.Lifecycle.ILifecycleStateService\"/>.</summary>");
        _ = sb.AppendLine("public sealed class " + bridgeTypeName + " : global::System.IDisposable");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    private readonly global::Fluxor.IActionSubscriber _subscriber;");
        _ = sb.AppendLine("    private readonly global::Hexalith.FrontComposer.Contracts.Lifecycle.ILifecycleStateService _service;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    public " + bridgeTypeName + "(");
        _ = sb.AppendLine("        global::Fluxor.IActionSubscriber subscriber,");
        _ = sb.AppendLine("        global::Hexalith.FrontComposer.Contracts.Lifecycle.ILifecycleStateService service)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        _subscriber = subscriber ?? throw new global::System.ArgumentNullException(nameof(subscriber));");
        _ = sb.AppendLine("        _service = service ?? throw new global::System.ArgumentNullException(nameof(service));");
        _ = sb.AppendLine("        _subscriber.SubscribeToAction<" + model.ActionsWrapperName + ".SubmittedAction>(this,");
        _ = sb.AppendLine("            a => _service.Transition(a.CorrelationId, global::Hexalith.FrontComposer.Contracts.Lifecycle.CommandLifecycleState.Submitting, null));");
        _ = sb.AppendLine("        _subscriber.SubscribeToAction<" + model.ActionsWrapperName + ".AcknowledgedAction>(this,");
        _ = sb.AppendLine("            a => _service.Transition(a.CorrelationId, global::Hexalith.FrontComposer.Contracts.Lifecycle.CommandLifecycleState.Acknowledged, a.MessageId));");
        _ = sb.AppendLine("        _subscriber.SubscribeToAction<" + model.ActionsWrapperName + ".SyncingAction>(this,");
        _ = sb.AppendLine("            a => _service.Transition(a.CorrelationId, global::Hexalith.FrontComposer.Contracts.Lifecycle.CommandLifecycleState.Syncing, null));");
        _ = sb.AppendLine("        _subscriber.SubscribeToAction<" + model.ActionsWrapperName + ".ConfirmedAction>(this,");
        _ = sb.AppendLine("            a => _service.Transition(a.CorrelationId, global::Hexalith.FrontComposer.Contracts.Lifecycle.CommandLifecycleState.Confirmed, null));");
        _ = sb.AppendLine("        _subscriber.SubscribeToAction<" + model.ActionsWrapperName + ".RejectedAction>(this,");
        _ = sb.AppendLine("            a => _service.Transition(a.CorrelationId, global::Hexalith.FrontComposer.Contracts.Lifecycle.CommandLifecycleState.Rejected, null));");
        _ = sb.AppendLine("        _subscriber.SubscribeToAction<" + model.ActionsWrapperName + ".ResetToIdleAction>(this,");
        _ = sb.AppendLine("            a => _service.Transition(a.CorrelationId, global::Hexalith.FrontComposer.Contracts.Lifecycle.CommandLifecycleState.Idle, null));");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    public void Dispose() => _subscriber.UnsubscribeFromAllActions(this);");
        _ = sb.AppendLine("}");

        return sb.ToString();
    }
}
