using System.Text;

using Hexalith.FrontComposer.SourceTools.Parsing;
using Hexalith.FrontComposer.SourceTools.Transforms;

namespace Hexalith.FrontComposer.SourceTools.Emitters;

/// <summary>
/// Story 2-2 Task 4 — emits <c>{CommandTypeName}Renderer.g.razor.cs</c>: the chrome around the
/// Story 2-1 form (ADR-016 — renderer never emits <c>&lt;EditForm&gt;</c>). Selects the rendering
/// shape (Inline / CompactInline / FullPage) from the density-derived default or the explicit
/// <c>RenderMode</c> parameter.
/// </summary>
/// <remarks>
/// Story 2-2 emits layout chrome via Fluent UI primitives (buttons, popover, card, breadcrumb link)
/// around the Story 2-1 <c>{Cmd}Form</c> per ADR-016. The form still owns <c>EditForm</c>, validation,
/// and lifecycle dispatch; this emitter focuses on density-driven shape and wiring (D5, D6, D21).
/// </remarks>
public static class CommandRendererEmitter {
    public static string Emit(CommandRendererModel model) {
        if (model is null) {
            throw new ArgumentNullException(nameof(model));
        }

        StringBuilder sb = new(4096);
        _ = sb.AppendLine("// Generated by FrontComposer source generator (Story 2-2 Task 4)");
        _ = sb.AppendLine("// Do not edit directly");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine("#pragma warning disable ASP0006");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine("using System.Collections.Generic;");
        _ = sb.AppendLine("using System.Globalization;");
        _ = sb.AppendLine("using System.Threading.Tasks;");
        _ = sb.AppendLine("using Fluxor;");
        _ = sb.AppendLine("using Hexalith.FrontComposer.Contracts;");
        _ = sb.AppendLine("using Hexalith.FrontComposer.Contracts.Communication;");
        _ = sb.AppendLine("using Hexalith.FrontComposer.Contracts.Rendering;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components.Forms;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components.Rendering;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components.Web;");
        _ = sb.AppendLine("using Microsoft.FluentUI.AspNetCore.Components;");
        _ = sb.AppendLine("using Microsoft.Extensions.Logging;");
        _ = sb.AppendLine("using Microsoft.Extensions.Options;");
        _ = sb.AppendLine("using Microsoft.JSInterop;");
        // Story 2-5 Task 6.1 — emitted usings so FcDestructiveConfirmationDialog + FcFormAbandonmentGuard resolve.
        _ = sb.AppendLine("using Hexalith.FrontComposer.Shell.Components.Forms;");
        _ = sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace) {
            _ = sb.AppendLine("namespace " + model.Namespace + ";");
            _ = sb.AppendLine();
        }

        string rendererName = model.TypeName + "Renderer";
        string defaultModeLiteral = "CommandRenderMode." + ToRenderMode(model.Density);
        string commandFqn = model.CommandFullyQualifiedName;
        string displayLabelEscaped = EscapeString(model.DisplayLabel);
        string densityName = model.Density.ToString();
        string lifecycleStateTypeFqn = string.IsNullOrEmpty(model.Namespace)
            ? model.StateName
            : model.Namespace + "." + model.StateName;
        bool hasAuthorizationPolicy = !string.IsNullOrWhiteSpace(model.AuthorizationPolicyName);

        _ = sb.AppendLine("/// <summary>Auto-generated density-driven renderer for <see cref=\"" + model.TypeName + "\"/> (Story 2-2).</summary>");
        // Story 7-3 Pass 4 DN-7-3-4-7 — protected renderers implement IDisposable so the
        // CTS / AuthState subscription can be cleaned up on circuit teardown. Unprotected renderers
        // keep the prior signature.
        if (hasAuthorizationPolicy) {
            _ = sb.AppendLine("public partial class " + rendererName + " : ComponentBase, IInlinePopover, global::System.IDisposable");
        }
        else {
            _ = sb.AppendLine("public partial class " + rendererName + " : ComponentBase, IInlinePopover");
        }

        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    [Parameter] public CommandRenderMode? RenderMode { get; set; }");
        _ = sb.AppendLine("    [Parameter] public " + commandFqn + "? InitialValue { get; set; }");
        _ = sb.AppendLine("    // Story 2-2 code-review D11 — CompactInline collapse callback (AC9 Escape focus-return). Story 2-5 adds NavigateAwayRequested.");
        _ = sb.AppendLine("    [Parameter] public EventCallback OnCollapseRequested { get; set; }");
        _ = sb.AppendLine("    [CascadingParameter] public ProjectionContext? ProjectionContext { get; set; }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    [Inject] private IEnumerable<IDerivedValueProvider> DerivedValueProviders { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private IOptions<FcShellOptions> ShellOptions { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private IJSRuntime JSRuntime { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private InlinePopoverRegistry InlinePopoverRegistry { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private NavigationManager NavigationManager { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private ILogger<" + rendererName + ">? Logger { get; set; }");
        _ = sb.AppendLine("    [Inject] private ICommandPageContext PageContext { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private IState<" + lifecycleStateTypeFqn + "> _lifecycleState { get; set; } = default!;");
        if (hasAuthorizationPolicy) {
            _ = sb.AppendLine("    [Inject] private global::Hexalith.FrontComposer.Shell.Services.Authorization.ICommandAuthorizationEvaluator CommandAuthorizationEvaluator { get; set; } = default!;");
            _ = sb.AppendLine("    [Inject] private global::Microsoft.Extensions.Localization.IStringLocalizer<global::Hexalith.FrontComposer.Shell.Resources.FcShellResources> AuthorizationLocalizer { get; set; } = default!;");
        }
        if (model.IsDestructive) {
            // Story 2-5 Task 6.1 — destructive commands open a FluentDialog via IDialogService (D11).
            _ = sb.AppendLine("    [Inject] private IDialogService DialogService { get; set; } = default!;");
        }
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private CommandRenderMode _effectiveMode;");
        _ = sb.AppendLine("    private bool _popoverOpen;");
        _ = sb.AppendLine("    private ElementReference _compactCardRef;");
        if (model.IsDestructive) {
            // Story 2-5 D24 + Winston #2 — dialog-lifetime flag prevents double-click dispatch.
            _ = sb.AppendLine("    private bool _dialogOpen;");
        }
        // Story 2-5 Task 5.3 / Task 6.1 — expose EditContext to FcFormAbandonmentGuard via OnEditContextReady.
        _ = sb.AppendLine("    private EditContext? _formEditContext;");
        // Story 2-2 code-review D12 — stable id derived from command type FullName for SSR/interactive consistency.
        string stableTriggerId = "fc-trigger-" + SanitizeCssId(model.CommandFullyQualifiedName);
        _ = sb.AppendLine("    private readonly string _triggerButtonId = \"" + stableTriggerId + "\";");
        _ = sb.AppendLine("    private Action? _externalSubmit;");
        _ = sb.AppendLine("    private IJSObjectReference? _expandInRowModule;");
        _ = sb.AppendLine("    private " + commandFqn + " _prefilledModel = new();");
        if (hasAuthorizationPolicy) {
            _ = sb.AppendLine("    [Inject] private global::Microsoft.AspNetCore.Components.Authorization.AuthenticationStateProvider AuthenticationStateProvider { get; set; } = default!;");
            _ = sb.AppendLine("    private const string AuthorizationPolicyName = \"" + EscapeString(model.AuthorizationPolicyName!) + "\";");
            _ = sb.AppendLine("    private bool _authorizationPresentationReady;");
            _ = sb.AppendLine("    private bool _authorizationPresentationAllowed;");
            _ = sb.AppendLine("    private global::System.Threading.CancellationTokenSource? _authorizationCts;");
            _ = sb.AppendLine("    private bool _authorizationDisposed;");
            _ = sb.AppendLine("    private long _authorizationRefreshSequence;");
            _ = sb.AppendLine("    private bool _authorizationStateSubscribed;");
            _ = sb.AppendLine("    private string _authorizationPresentationTitle = string.Empty;");
            _ = sb.AppendLine("    private string _authorizationPresentationMessage = string.Empty;");
        }
        _ = sb.AppendLine();

        _ = sb.AppendLine("    protected override async Task OnInitializedAsync()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        _effectiveMode = RenderMode ?? " + defaultModeLiteral + ";");
        _ = sb.AppendLine("        if (RenderMode.HasValue && !IsCompatibleOverride(RenderMode.Value))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            Logger?.LogWarning(\"HFC1015: RenderMode {Mode} incompatible with " + model.TypeName + " density " + densityName + "\", _effectiveMode);");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        Logger?.LogInformation(\"Rendering {CommandType} in {Mode} (density=" + densityName + ")\", \"" + commandFqn + "\", _effectiveMode);");
        _ = sb.AppendLine("        _prefilledModel = InitialValue ?? new();");
        _ = sb.AppendLine("        await PrefillDerivableFieldsAsync().ConfigureAwait(false);");
        if (hasAuthorizationPolicy) {
            // Initialize CTS synchronously so disposal during the first await actually cancels.
            _ = sb.AppendLine("        _authorizationCts ??= new global::System.Threading.CancellationTokenSource();");
            _ = sb.AppendLine("        if (!_authorizationStateSubscribed)");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            AuthenticationStateProvider.AuthenticationStateChanged += OnAuthenticationStateChanged;");
            _ = sb.AppendLine("            _authorizationStateSubscribed = true;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        await RefreshPresentationAuthorizationAsync().ConfigureAwait(false);");
        }
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        if (hasAuthorizationPolicy) {
            _ = sb.AppendLine("    private async Task RefreshPresentationAuthorizationAsync()");
            _ = sb.AppendLine("    {");
            _ = sb.AppendLine("        if (_authorizationDisposed) { return; }");
            // Sync flip Ready=false so concurrent renders see the in-flight state immediately
            // (Pass-3 form-emitter pattern; mirror in renderer).
            _ = sb.AppendLine("        _authorizationPresentationReady = false;");
            _ = sb.AppendLine("        _authorizationPresentationAllowed = false;");
            _ = sb.AppendLine("        SetAuthorizationPresentationMessage(global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationDecision.Pending(global::System.Guid.NewGuid().ToString(\"N\")));");
            _ = sb.AppendLine("        long sequence = global::System.Threading.Interlocked.Increment(ref _authorizationRefreshSequence);");
            _ = sb.AppendLine("        var cts = _authorizationCts;");
            _ = sb.AppendLine("        global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationDecision? decision;");
            _ = sb.AppendLine("        try");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            decision = await CommandAuthorizationEvaluator.EvaluateAsync(new global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationRequest(");
            _ = sb.AppendLine("                typeof(" + commandFqn + "),");
            _ = sb.AppendLine("                AuthorizationPolicyName,");
            // Pass-4 AA-15 / BH-37 — pass null (not _prefilledModel). Presentation-time auth must
            // not include unvalidated user input as the resource. Submit-time gate sees the
            // command via the form's own EvaluateAsync call.
            _ = sb.AppendLine("                null,");
            _ = sb.AppendLine("                \"" + EscapeString(model.BoundedContext) + "\",");
            _ = sb.AppendLine("                \"" + displayLabelEscaped + "\",");
            _ = sb.AppendLine("                ResolveAuthorizationSurface()),");
            _ = sb.AppendLine("                cts?.Token ?? global::System.Threading.CancellationToken.None);");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        catch (global::System.OperationCanceledException)");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            return;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        catch (global::System.Exception ex)");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            Logger?.LogWarning(ex, \"Renderer authorization evaluation failed; trigger remains disabled. CommandType={CommandType}\", \"" + commandFqn + "\");");
            _ = sb.AppendLine("            decision = null;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        if (_authorizationDisposed) { return; }");
            _ = sb.AppendLine("        if (global::System.Threading.Interlocked.Read(ref _authorizationRefreshSequence) != sequence) { return; }");
            _ = sb.AppendLine("        if (decision is null)");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            _authorizationPresentationReady = true;");
            _ = sb.AppendLine("            _authorizationPresentationAllowed = false;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        else");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            _authorizationPresentationReady = decision.Kind != global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationDecisionKind.Pending;");
            _ = sb.AppendLine("            _authorizationPresentationAllowed = decision.IsAllowed;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        SetAuthorizationPresentationMessage(decision);");
            _ = sb.AppendLine("        await InvokeAsync(StateHasChanged).ConfigureAwait(false);");
            _ = sb.AppendLine("        if (decision?.Kind == global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationDecisionKind.Pending)");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            _ = ScheduleAuthorizationRetryAsync(sequence);");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("    }");
            _ = sb.AppendLine();
            _ = sb.AppendLine("    private async Task ScheduleAuthorizationRetryAsync(long observedSequence)");
            _ = sb.AppendLine("    {");
            _ = sb.AppendLine("        try");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            await global::System.Threading.Tasks.Task.Delay(global::System.TimeSpan.FromMilliseconds(250), _authorizationCts?.Token ?? global::System.Threading.CancellationToken.None).ConfigureAwait(false);");
            _ = sb.AppendLine("            if (_authorizationDisposed) { return; }");
            _ = sb.AppendLine("            if (global::System.Threading.Interlocked.Read(ref _authorizationRefreshSequence) != observedSequence) { return; }");
            _ = sb.AppendLine("            await InvokeAsync(RefreshPresentationAuthorizationAsync).ConfigureAwait(false);");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        catch (global::System.OperationCanceledException) { }");
            _ = sb.AppendLine("        catch (global::System.ObjectDisposedException) { }");
            _ = sb.AppendLine("    }");
            _ = sb.AppendLine();
            _ = sb.AppendLine("    private void SetAuthorizationPresentationMessage(global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationDecision? decision)");
            _ = sb.AppendLine("    {");
            _ = sb.AppendLine("        if (decision?.Kind == global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationDecisionKind.Pending)");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            _authorizationPresentationTitle = ResolveAuthorizationLocalized(\"AuthorizationCheckingPermissionTitle\", \"Checking permission...\");");
            _ = sb.AppendLine("            _authorizationPresentationMessage = ResolveAuthorizationLocalized(\"AuthorizationCheckingPermissionMessage\", \"Verifying you can {0}. This usually takes a moment.\", \"" + displayLabelEscaped + "\");");
            _ = sb.AppendLine("            return;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        if (decision?.Reason is global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationReason.Denied or global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationReason.Unauthenticated)");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            _authorizationPresentationTitle = ResolveAuthorizationLocalized(\"UnauthorizedCommandWarningTitle\", \"Permission required\");");
            _ = sb.AppendLine("            _authorizationPresentationMessage = ResolveAuthorizationLocalized(\"UnauthorizedCommandWarningMessage\", \"You do not have permission to {0}.\", \"" + displayLabelEscaped + "\");");
            _ = sb.AppendLine("            return;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        _authorizationPresentationTitle = ResolveAuthorizationLocalized(\"AuthorizationActionUnavailableTitle\", \"Action unavailable\");");
            _ = sb.AppendLine("        _authorizationPresentationMessage = ResolveAuthorizationLocalized(\"AuthorizationActionUnavailableMessage\", \"This action is not available for the current user or session.\");");
            _ = sb.AppendLine("    }");
            _ = sb.AppendLine();
            _ = sb.AppendLine("    private string ResolveAuthorizationLocalized(string key, string fallback, params object[] args)");
            _ = sb.AppendLine("    {");
            _ = sb.AppendLine("        global::Microsoft.Extensions.Localization.LocalizedString candidate = args.Length == 0 ? AuthorizationLocalizer[key] : AuthorizationLocalizer[key, args];");
            _ = sb.AppendLine("        return candidate.ResourceNotFound");
            _ = sb.AppendLine("            ? string.Format(CultureInfo.CurrentCulture, fallback, args)");
            _ = sb.AppendLine("            : candidate.Value;");
            _ = sb.AppendLine("    }");
            _ = sb.AppendLine();
            _ = sb.AppendLine("    private void OnAuthenticationStateChanged(global::System.Threading.Tasks.Task<global::Microsoft.AspNetCore.Components.Authorization.AuthenticationState> task)");
            _ = sb.AppendLine("    {");
            _ = sb.AppendLine("        if (_authorizationDisposed) { return; }");
            _ = sb.AppendLine("        try");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            _ = InvokeAsync(async () =>");
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine("                if (_authorizationDisposed) { return; }");
            _ = sb.AppendLine("                _ = await task.ConfigureAwait(true);");
            _ = sb.AppendLine("                await RefreshPresentationAuthorizationAsync().ConfigureAwait(true);");
            _ = sb.AppendLine("            });");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        catch (global::System.ObjectDisposedException) { /* circuit torn down */ }");
            _ = sb.AppendLine("    }");
            _ = sb.AppendLine();
            _ = sb.AppendLine("    public void Dispose()");
            _ = sb.AppendLine("    {");
            _ = sb.AppendLine("        if (_authorizationDisposed) { return; }");
            _ = sb.AppendLine("        _authorizationDisposed = true;");
            _ = sb.AppendLine("        if (_authorizationStateSubscribed)");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            AuthenticationStateProvider.AuthenticationStateChanged -= OnAuthenticationStateChanged;");
            _ = sb.AppendLine("            _authorizationStateSubscribed = false;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        try { _authorizationCts?.Cancel(); }");
            _ = sb.AppendLine("        catch (global::System.ObjectDisposedException) { }");
            _ = sb.AppendLine("        _authorizationCts?.Dispose();");
            _ = sb.AppendLine("        _authorizationCts = null;");
            _ = sb.AppendLine("    }");
            _ = sb.AppendLine();
            _ = sb.AppendLine("    private global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationSurface ResolveAuthorizationSurface()");
            _ = sb.AppendLine("        => _effectiveMode switch");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            CommandRenderMode.Inline => global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationSurface.InlineAction,");
            _ = sb.AppendLine("            CommandRenderMode.CompactInline => global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationSurface.CompactInlineAction,");
            _ = sb.AppendLine("            CommandRenderMode.FullPage => global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationSurface.FullPage,");
            _ = sb.AppendLine("            _ => global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationSurface.FullPage,");
            _ = sb.AppendLine("        };");
            _ = sb.AppendLine();
            _ = sb.AppendLine("    private bool AuthorizationTriggerDisabled()");
            _ = sb.AppendLine("        => !_authorizationPresentationReady || !_authorizationPresentationAllowed;");
            _ = sb.AppendLine();
        }
        _ = sb.AppendLine("    private static bool IsCompatibleOverride(CommandRenderMode mode)");
        _ = sb.AppendLine("        => mode != CommandRenderMode.Inline || " + (model.NonDerivablePropertyNames.Count <= 1 ? "true" : "false") + ";");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private async Task PrefillDerivableFieldsAsync()");
        _ = sb.AppendLine("    {");
        foreach (string propertyName in model.DerivablePropertyNames) {
            string escapedPropertyName = EscapeString(propertyName);
            _ = sb.AppendLine("        await TryPrefillPropertyAsync(\"" + escapedPropertyName + "\").ConfigureAwait(false);");
        }
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private Task RefreshDerivedValuesBeforeSubmitAsync()");
        _ = sb.AppendLine("        => PrefillDerivableFieldsAsync();");
        _ = sb.AppendLine();
        // Story 2-2 code-review P31 — distinguish "no provider resolved" from "provider resolved but assignment failed".
        _ = sb.AppendLine("    private async Task TryPrefillPropertyAsync(string propertyName)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        bool anyProviderResolved = false;");
        _ = sb.AppendLine("        foreach (IDerivedValueProvider provider in DerivedValueProviders)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            DerivedValueResult result = await provider.ResolveAsync(typeof(" + commandFqn + "), propertyName, ProjectionContext, default).ConfigureAwait(false);");
        _ = sb.AppendLine("            if (!result.HasValue)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                continue;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            anyProviderResolved = true;");
        _ = sb.AppendLine("            if (TrySetPropertyValue(propertyName, result.Value))");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                return;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            Logger?.LogWarning(\"Derived value for {PropertyName} on {CommandType} could not be assigned.\", propertyName, \"" + commandFqn + "\");");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        if (!anyProviderResolved)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            Logger?.LogDebug(\"No derived value could be resolved for {PropertyName} on {CommandType}; leaving default value in place.\", propertyName, \"" + commandFqn + "\");");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        // Story 2-2 code-review P25 — use CurrentCulture for DateTime/number parse (matches CommandFormEmitter numeric binding).
        _ = sb.AppendLine("    private bool TrySetPropertyValue(string propertyName, object? value)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        System.Reflection.PropertyInfo? property = typeof(" + commandFqn + ").GetProperty(propertyName, System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance);");
        _ = sb.AppendLine("        if (property is null || !property.CanWrite)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return false;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        if (value is null)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            property.SetValue(_prefilledModel, null);");
        _ = sb.AppendLine("            return true;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        Type targetType = Nullable.GetUnderlyingType(property.PropertyType) ?? property.PropertyType;");
        _ = sb.AppendLine("        object? converted = value;");
        _ = sb.AppendLine("        if (!targetType.IsInstanceOfType(value))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            try");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                if (targetType.IsEnum)");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    converted = value is string s");
        _ = sb.AppendLine("                        ? Enum.Parse(targetType, s, ignoreCase: true)");
        _ = sb.AppendLine("                        : Enum.ToObject(targetType, value);");
        _ = sb.AppendLine("                }");
        _ = sb.AppendLine("                else if (targetType == typeof(Guid))");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    converted = value is Guid guid ? guid : Guid.Parse(Convert.ToString(value, CultureInfo.InvariantCulture)!);");
        _ = sb.AppendLine("                }");
        _ = sb.AppendLine("                else if (targetType == typeof(DateTimeOffset))");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    converted = value is DateTimeOffset dto");
        _ = sb.AppendLine("                        ? dto");
        _ = sb.AppendLine("                        : DateTimeOffset.Parse(Convert.ToString(value, CultureInfo.CurrentCulture)!, CultureInfo.CurrentCulture);");
        _ = sb.AppendLine("                }");
        _ = sb.AppendLine("                else");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    converted = Convert.ChangeType(value, targetType, CultureInfo.CurrentCulture);");
        _ = sb.AppendLine("                }");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("            catch (Exception ex) when (ex is InvalidCastException or FormatException or OverflowException or ArgumentException)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                return false;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        property.SetValue(_prefilledModel, converted);");
        _ = sb.AppendLine("        return true;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private Icon? ResolveIcon()");
        _ = sb.AppendLine("    {");
        if (!string.IsNullOrEmpty(model.IconName)) {
            _ = sb.AppendLine("        if (TryResolveIcon(\"" + EscapeString(model.IconName!) + "\", out Icon? configured))");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            return configured;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        Logger?.LogWarning(\"Icon '{IconName}' failed to resolve on {CommandType}; falling back to Play.\", \"" + EscapeString(model.IconName!) + "\", \"" + commandFqn + "\");");
        }
        _ = sb.AppendLine("        return TryResolveIcon(\"Regular.Size16.Play\", out Icon? fallback) ? fallback : null;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private static bool TryResolveIcon(string iconName, out Icon? icon)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        icon = null;");
        _ = sb.AppendLine("        if (string.IsNullOrWhiteSpace(iconName))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return false;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        return global::Hexalith.FrontComposer.Shell.Components.Icons.FcFluentIcons.TryCreate(iconName, out icon);");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    private void OnFormRegisteredExternalSubmit(Action submit)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        _externalSubmit = submit;");
        _ = sb.AppendLine("        _ = InvokeAsync(StateHasChanged);");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        // Story 2-5 Task 5.3 / Task 6.1 — capture the form's EditContext for abandonment-guard
        // binding + (for destructive commands) ensuring D24 validation before the dialog opens.
        _ = sb.AppendLine("    private void OnFormEditContextReady(EditContext context)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        _formEditContext = context;");
        _ = sb.AppendLine("        _ = InvokeAsync(StateHasChanged);");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        if (model.IsDestructive) {
            string title = !string.IsNullOrEmpty(model.DestructiveConfirmTitle)
                ? EscapeString(model.DestructiveConfirmTitle!)
                : EscapeString(model.DisplayLabel) + "?";
            string body = !string.IsNullOrEmpty(model.DestructiveConfirmBody)
                ? EscapeString(model.DestructiveConfirmBody!)
                : "This action cannot be undone.";

            // Story 2-5 D2 / D11 / D24 — gating lives in BeforeSubmit so the form's OnValidSubmit
            // has already validated (D24 satisfied: if invalid, OnInvalidSubmit fires and we never
            // reach here). The dialog opens, and cancel → throw OperationCanceledException → the
            // form's existing catch resets lifecycle state to Idle via ResetToIdleAction (P-11).
            // Review 2026-04-17 P11 — _dialogOpen is set BEFORE any async work so a rapid
            // double-click during RefreshDerivedValuesBeforeSubmitAsync cannot open a second dialog.
            // Review 2026-04-17 P8 — no ConfigureAwait(false) on Blazor UI paths; continuations
            // must resume on the component's sync context.
            _ = sb.AppendLine("    private async Task DestructiveBeforeSubmitAsync()");
            _ = sb.AppendLine("    {");
            _ = sb.AppendLine("        if (_dialogOpen) throw new OperationCanceledException(\"Destructive dialog already open.\");");
            _ = sb.AppendLine("        _dialogOpen = true;");
            _ = sb.AppendLine("        try");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            await RefreshDerivedValuesBeforeSubmitAsync();");
            _ = sb.AppendLine("            var dialogRef = await DialogService.ShowDialogAsync<FcDestructiveConfirmationDialog>(options =>");
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine("                options.Parameters.Add(nameof(FcDestructiveConfirmationDialog.Title), \"" + title + "\");");
            _ = sb.AppendLine("                options.Parameters.Add(nameof(FcDestructiveConfirmationDialog.Body), \"" + body + "\");");
            _ = sb.AppendLine("                options.Parameters.Add(nameof(FcDestructiveConfirmationDialog.DestructiveLabel), \"" + EscapeString(model.DisplayLabel) + "\");");
            _ = sb.AppendLine("            });");
            _ = sb.AppendLine("            var result = await dialogRef.Result;");
            _ = sb.AppendLine("            if (result.Cancelled)");
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine("                throw new OperationCanceledException(\"User cancelled destructive confirmation.\");");
            _ = sb.AppendLine("            }");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        finally");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            _dialogOpen = false;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("    }");
            _ = sb.AppendLine();
        }

        _ = sb.AppendLine("    private Task OnZeroFieldClickAsync()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        _externalSubmit?.Invoke();");
        _ = sb.AppendLine("        return Task.CompletedTask;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    private async Task OpenPopoverAsync()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        await InlinePopoverRegistry.OpenAsync(this).ConfigureAwait(false);");
        _ = sb.AppendLine("        _popoverOpen = true;");
        _ = sb.AppendLine("        await InvokeAsync(StateHasChanged).ConfigureAwait(false);");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    /// <inheritdoc/>");
        _ = sb.AppendLine("    public async Task ClosePopoverAsync()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (!_popoverOpen) return;");
        _ = sb.AppendLine("        _popoverOpen = false;");
        _ = sb.AppendLine("        InlinePopoverRegistry.Released(this);");
        _ = sb.AppendLine("        try");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            _expandInRowModule ??= await JSRuntime.InvokeAsync<IJSObjectReference>(\"import\", \"./_content/Hexalith.FrontComposer.Shell/js/fc-expandinrow.js\").ConfigureAwait(false);");
        _ = sb.AppendLine("            await _expandInRowModule.InvokeVoidAsync(\"focusTriggerElementById\", _triggerButtonId).ConfigureAwait(false);");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        catch (InvalidOperationException) { /* prerender or unavailable JS runtime. */ }");
        _ = sb.AppendLine("        catch (JSDisconnectedException) { /* circuit teardown; benign. */ }");
        _ = sb.AppendLine("        await InvokeAsync(StateHasChanged).ConfigureAwait(false);");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    private Task HandleEscape(KeyboardEventArgs e)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        return e.Key == \"Escape\" && _popoverOpen ? ClosePopoverAsync() : Task.CompletedTask;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    // Story 2-2 code-review D11 — CompactInline Escape → OnCollapseRequested (AC9 focus-return contract).");
        _ = sb.AppendLine("    private async Task HandleCompactEscapeAsync(KeyboardEventArgs e)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (e.Key == \"Escape\" && _effectiveMode == CommandRenderMode.CompactInline && OnCollapseRequested.HasDelegate)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            await OnCollapseRequested.InvokeAsync().ConfigureAwait(false);");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    private Task OnConfirmedAsync()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (_effectiveMode == CommandRenderMode.Inline && _popoverOpen)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return ClosePopoverAsync();");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        if (_effectiveMode == CommandRenderMode.FullPage)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            NavigateToReturnPath();");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        return Task.CompletedTask;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    private void NavigateToReturnPath()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        string? path = GetRawReturnPath();");
        _ = sb.AppendLine("        if (IsValidRelativeReturnPath(path))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            NavigationManager.NavigateTo(path!);");
        _ = sb.AppendLine("            return;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        if (!string.IsNullOrEmpty(path))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            Logger?.LogError(\"D32: ReturnPath '{Path}' rejected as invalid-relative; navigating home. CorrelationId={CorrelationId}\", path, ResolveLoggingCorrelationId());");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        NavigationManager.NavigateTo(\"/\");");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        // Story 2-2 code-review D8 — delegate to Contracts.Rendering.ReturnPathValidator for security single-source-of-truth.
        _ = sb.AppendLine("    private static bool IsValidRelativeReturnPath(string? path)");
        _ = sb.AppendLine("        => Hexalith.FrontComposer.Contracts.Rendering.ReturnPathValidator.IsSafeRelativePath(path);");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private string? GetRawReturnPath()");
        _ = sb.AppendLine("        => !string.IsNullOrWhiteSpace(PageContext.ReturnPath) ? PageContext.ReturnPath : GetQueryParameter(\"returnPath\");");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private string? GetQueryParameter(string key)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (string.IsNullOrWhiteSpace(key))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return null;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        Uri uri = NavigationManager.ToAbsoluteUri(NavigationManager.Uri);");
        _ = sb.AppendLine("        if (string.IsNullOrWhiteSpace(uri.Query))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return null;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        foreach (string pair in uri.Query.TrimStart('?').Split('&', StringSplitOptions.RemoveEmptyEntries))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            string[] segments = pair.Split('=', 2);");
        _ = sb.AppendLine("            string currentKey = Uri.UnescapeDataString(segments[0]);");
        _ = sb.AppendLine("            if (!string.Equals(currentKey, key, StringComparison.OrdinalIgnoreCase))");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                continue;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            return segments.Length > 1 ? Uri.UnescapeDataString(segments[1]) : string.Empty;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        return null;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private string GetBreadcrumbReturnPath()");
        _ = sb.AppendLine("        => IsValidRelativeReturnPath(GetRawReturnPath()) ? GetRawReturnPath()! : \"/\";");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private string GetBreadcrumbBoundedContext()");
        _ = sb.AppendLine("        => !string.IsNullOrWhiteSpace(PageContext.BoundedContext) ? PageContext.BoundedContext : \"" + EscapeString(model.BoundedContext ?? "Default") + "\";");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private string? ResolveLoggingCorrelationId()");
        _ = sb.AppendLine("        => _lifecycleState.Value.CorrelationId;");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    protected override async Task OnAfterRenderAsync(bool firstRender)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (firstRender && _effectiveMode == CommandRenderMode.CompactInline)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            try");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                _expandInRowModule ??= await JSRuntime.InvokeAsync<IJSObjectReference>(\"import\", \"./_content/Hexalith.FrontComposer.Shell/js/fc-expandinrow.js\").ConfigureAwait(false);");
        _ = sb.AppendLine("                await _expandInRowModule.InvokeVoidAsync(\"initializeExpandInRow\", _compactCardRef).ConfigureAwait(false);");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("            catch (InvalidOperationException) { /* prerender: JSInterop not yet available. */ }");
        _ = sb.AppendLine("            catch (JSDisconnectedException) { /* circuit teardown; benign. */ }");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        // BuildRenderTree — dispatches on _effectiveMode
        EmitBuildRenderTree(sb, model, displayLabelEscaped);

        _ = sb.AppendLine("}");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#pragma warning restore ASP0006");

        return sb.ToString();
    }

    private static void EmitBuildRenderTree(StringBuilder sb, CommandRendererModel model, string displayLabelEscaped) {
        string formFqn = string.IsNullOrEmpty(model.Namespace) ? model.FormComponentName : model.Namespace + "." + model.FormComponentName;
        int nonDerivableCount = model.NonDerivablePropertyNames.Count;
        string firstFieldName = nonDerivableCount >= 1 ? EscapeString(model.NonDerivablePropertyNames[0]) : "";
        // Story 2-5 Task 6.1 — destructive commands route BeforeSubmit through DestructiveBeforeSubmitAsync
        // which opens the confirmation dialog. Non-destructive commands keep the default (derived-values
        // refresh only).
        string beforeSubmitFunc = model.IsDestructive
            ? "(Func<Task>)DestructiveBeforeSubmitAsync"
            : "(Func<Task>)RefreshDerivedValuesBeforeSubmitAsync";
        bool hasAuthorizationPolicy = !string.IsNullOrWhiteSpace(model.AuthorizationPolicyName);

        _ = sb.AppendLine("    protected override void BuildRenderTree(RenderTreeBuilder builder)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        int seq = 0;");
        _ = sb.AppendLine("        switch (_effectiveMode)");
        _ = sb.AppendLine("        {");

        _ = sb.AppendLine("            case CommandRenderMode.Inline:");
        _ = sb.AppendLine("            {");
        if (nonDerivableCount == 0) {
            _ = sb.AppendLine("                builder.OpenComponent<FluentButton>(seq++);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Id\", _triggerButtonId);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Type\", ButtonType.Button);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Appearance\", ButtonAppearance.Outline);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Disabled\", " + (hasAuthorizationPolicy ? "(_externalSubmit is null) || AuthorizationTriggerDisabled()" : "_externalSubmit is null") + ");");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"IconStart\", ResolveIcon());");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Label\", \"" + displayLabelEscaped + "\");");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"OnClick\", EventCallback.Factory.Create<MouseEventArgs>(this, _ => OnZeroFieldClickAsync()));");
            _ = sb.AppendLine("                builder.CloseComponent();");
            _ = sb.AppendLine();
            _ = sb.AppendLine("                builder.OpenElement(seq++, \"div\");");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"style\", \"display:none\");");
            _ = sb.AppendLine("                builder.OpenComponent<" + formFqn + ">(seq++);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"InitialValue\", _prefilledModel);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"RegisterExternalSubmit\", (Action<Action>)OnFormRegisteredExternalSubmit);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"BeforeSubmit\", " + beforeSubmitFunc + ");");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"OnConfirmed\", EventCallback.Factory.Create(this, OnConfirmedAsync));");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"OnEditContextReady\", EventCallback.Factory.Create<EditContext>(this, OnFormEditContextReady));");
            _ = sb.AppendLine("                builder.CloseComponent();");
            _ = sb.AppendLine("                builder.CloseElement();");
        }
        else {
            _ = sb.AppendLine("                builder.OpenComponent<FluentButton>(seq++);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Id\", _triggerButtonId);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Type\", ButtonType.Button);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Appearance\", ButtonAppearance.Outline);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"IconStart\", ResolveIcon());");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Label\", \"" + displayLabelEscaped + "\");");
            if (hasAuthorizationPolicy) {
                _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Disabled\", AuthorizationTriggerDisabled());");
            }
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"OnClick\", EventCallback.Factory.Create<MouseEventArgs>(this, _ => OpenPopoverAsync()));");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"aria-expanded\", _popoverOpen);");
            _ = sb.AppendLine("                builder.CloseComponent();");
            _ = sb.AppendLine();
            _ = sb.AppendLine("                builder.OpenComponent<FluentPopover>(seq++);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"AnchorId\", _triggerButtonId);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Opened\", _popoverOpen);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"OpenedChanged\", EventCallback.Factory.Create<bool>(this, value => _popoverOpen = value));");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"ChildContent\", (RenderFragment)(__popover =>");
            _ = sb.AppendLine("                {");
            _ = sb.AppendLine("                    int pseq = 0;");
            _ = sb.AppendLine("                    __popover.OpenElement(pseq++, \"div\");");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"class\", \"fc-popover\");");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"onkeydown\", EventCallback.Factory.Create<KeyboardEventArgs>(this, HandleEscape));");
            _ = sb.AppendLine("                    __popover.OpenComponent<" + formFqn + ">(pseq++);");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"InitialValue\", _prefilledModel);");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"ShowFieldsOnly\", new[] { \"" + firstFieldName + "\" });");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"BeforeSubmit\", " + beforeSubmitFunc + ");");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"OnConfirmed\", EventCallback.Factory.Create(this, OnConfirmedAsync));");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"OnEditContextReady\", EventCallback.Factory.Create<EditContext>(this, OnFormEditContextReady));");
            _ = sb.AppendLine("                    __popover.CloseComponent();");
            _ = sb.AppendLine("                    __popover.OpenComponent<FluentButton>(pseq++);");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"Type\", ButtonType.Button);");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"Appearance\", ButtonAppearance.Outline);");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"Label\", \"Cancel\");");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"OnClick\", EventCallback.Factory.Create<MouseEventArgs>(this, _ => ClosePopoverAsync()));");
            _ = sb.AppendLine("                    __popover.CloseComponent();");
            _ = sb.AppendLine("                    __popover.CloseElement();");
            _ = sb.AppendLine("                }));");
            _ = sb.AppendLine("                builder.CloseComponent();");
        }

        _ = sb.AppendLine("                break;");
        _ = sb.AppendLine("            }");

        _ = sb.AppendLine("            case CommandRenderMode.CompactInline:");
        _ = sb.AppendLine("            {");
        if (hasAuthorizationPolicy) {
            // Pass-4 DN-7-3-4-6 (b) — render a localized "Action unavailable" placeholder when
            // presentation auth disallows the trigger. Form-level submit gate still authoritative
            // but the user sees a coherent "no permission" surface instead of an interactive form
            // that always rejects on submit.
            _ = sb.AppendLine("                if (AuthorizationTriggerDisabled())");
            _ = sb.AppendLine("                {");
            _ = sb.AppendLine("                    builder.OpenComponent<FluentMessageBar>(seq++);");
            _ = sb.AppendLine("                    builder.AddAttribute(seq++, \"Intent\", MessageIntent.Warning);");
            _ = sb.AppendLine("                    builder.AddAttribute(seq++, \"Title\", _authorizationPresentationTitle);");
            _ = sb.AppendLine("                    builder.AddAttribute(seq++, \"AllowDismiss\", false);");
            _ = sb.AppendLine("                    builder.AddAttribute(seq++, \"ChildContent\", (RenderFragment)(__message => __message.AddContent(0, _authorizationPresentationMessage)));");
            _ = sb.AppendLine("                    builder.CloseComponent();");
            _ = sb.AppendLine("                    break;");
            _ = sb.AppendLine("                }");
        }

        _ = sb.AppendLine("                builder.OpenElement(seq++, \"div\");");
        _ = sb.AppendLine("                builder.AddAttribute(seq++, \"class\", \"fc-expand-in-row\");");
        _ = sb.AppendLine("                builder.AddAttribute(seq++, \"onkeydown\", EventCallback.Factory.Create<KeyboardEventArgs>(this, HandleCompactEscapeAsync));");
        _ = sb.AppendLine("                builder.AddAttribute(seq++, \"tabindex\", \"-1\");");
        _ = sb.AppendLine("                builder.AddElementReferenceCapture(seq++, r => _compactCardRef = r);");
        _ = sb.AppendLine("                builder.OpenComponent<FluentCard>(seq++);");
        _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Appearance\", CardAppearance.Outline);");
        _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Shadow\", CardShadow.Small);");
        _ = sb.AppendLine("                builder.AddAttribute(seq++, \"ChildContent\", (RenderFragment)(__card =>");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    int cseq = 0;");
        _ = sb.AppendLine("                    __card.OpenComponent<" + formFqn + ">(cseq++);");
        _ = sb.AppendLine("                    __card.AddAttribute(cseq++, \"InitialValue\", _prefilledModel);");
        _ = sb.AppendLine("                    __card.AddAttribute(cseq++, \"DerivableFieldsHidden\", true);");
        _ = sb.AppendLine("                    __card.AddAttribute(cseq++, \"BeforeSubmit\", " + beforeSubmitFunc + ");");
        _ = sb.AppendLine("                    __card.AddAttribute(cseq++, \"OnConfirmed\", EventCallback.Factory.Create(this, OnConfirmedAsync));");
        _ = sb.AppendLine("                    __card.AddAttribute(cseq++, \"OnEditContextReady\", EventCallback.Factory.Create<EditContext>(this, OnFormEditContextReady));");
        _ = sb.AppendLine("                    __card.CloseComponent();");
        _ = sb.AppendLine("                }));");
        _ = sb.AppendLine("                builder.CloseComponent();");
        _ = sb.AppendLine("                builder.CloseElement();");
        _ = sb.AppendLine("                break;");
        _ = sb.AppendLine("            }");

        _ = sb.AppendLine("            case CommandRenderMode.FullPage:");
        _ = sb.AppendLine("            default:");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                var opts = ShellOptions.Value;");
        if (hasAuthorizationPolicy) {
            // Pass-4 DN-7-3-4-6 (b) — same presentation gate as CompactInline. Form's submit-time
            // auth check is authoritative; this guard prevents users from interacting with form
            // fields they will never be able to submit.
            _ = sb.AppendLine("                if (AuthorizationTriggerDisabled())");
            _ = sb.AppendLine("                {");
            _ = sb.AppendLine("                    builder.OpenElement(seq++, \"div\");");
            _ = sb.AppendLine("                    builder.AddAttribute(seq++, \"style\", $\"max-width: {opts.FullPageFormMaxWidth}; margin: 0 auto;\");");
            _ = sb.AppendLine("                    builder.OpenComponent<FluentMessageBar>(seq++);");
            _ = sb.AppendLine("                    builder.AddAttribute(seq++, \"Intent\", MessageIntent.Warning);");
            _ = sb.AppendLine("                    builder.AddAttribute(seq++, \"Title\", _authorizationPresentationTitle);");
            _ = sb.AppendLine("                    builder.AddAttribute(seq++, \"AllowDismiss\", false);");
            _ = sb.AppendLine("                    builder.AddAttribute(seq++, \"ChildContent\", (RenderFragment)(__message => __message.AddContent(0, _authorizationPresentationMessage)));");
            _ = sb.AppendLine("                    builder.CloseComponent();");
            _ = sb.AppendLine("                    builder.CloseElement();");
            _ = sb.AppendLine("                    break;");
            _ = sb.AppendLine("                }");
        }

        _ = sb.AppendLine("                builder.OpenElement(seq++, \"div\");");
        _ = sb.AppendLine("                builder.AddAttribute(seq++, \"style\", $\"max-width: {opts.FullPageFormMaxWidth}; margin: 0 auto;\");");
        _ = sb.AppendLine("                if (opts.EmbeddedBreadcrumb)");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    builder.OpenElement(seq++, \"nav\");");
        _ = sb.AppendLine("                    builder.AddAttribute(seq++, \"aria-label\", \"breadcrumb\");");
        _ = sb.AppendLine("                    builder.OpenComponent<FluentLink>(seq++);");
        _ = sb.AppendLine("                    builder.AddAttribute(seq++, \"Href\", GetBreadcrumbReturnPath());");
        _ = sb.AppendLine("                    builder.AddAttribute(seq++, \"Appearance\", LinkAppearance.Subtle);");
        _ = sb.AppendLine("                    builder.AddAttribute(seq++, \"ChildContent\", (RenderFragment)(__link =>");
        _ = sb.AppendLine("                    {");
        _ = sb.AppendLine("                        __link.AddContent(0, GetBreadcrumbBoundedContext());");
        _ = sb.AppendLine("                    }));");
        _ = sb.AppendLine("                    builder.CloseComponent();");
        _ = sb.AppendLine("                    builder.AddContent(seq++, \" > " + displayLabelEscaped + "\");");
        _ = sb.AppendLine("                    builder.CloseElement();");
        _ = sb.AppendLine("                }");
        // Story 2-5 D19 / Task 6.1 — FullPage forms wrap their body in FcFormAbandonmentGuard.
        _ = sb.AppendLine("                builder.OpenComponent<FcFormAbandonmentGuard>(seq++);");
        _ = sb.AppendLine("                builder.AddAttribute(seq++, \"CorrelationId\", _lifecycleState.Value.CorrelationId ?? string.Empty);");
        _ = sb.AppendLine("                builder.AddAttribute(seq++, \"EditContext\", _formEditContext);");
        _ = sb.AppendLine("                builder.AddAttribute(seq++, \"ChildContent\", (RenderFragment)(__guard =>");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    int gseq = 0;");
        _ = sb.AppendLine("                    __guard.OpenComponent<" + formFqn + ">(gseq++);");
        _ = sb.AppendLine("                    __guard.AddAttribute(gseq++, \"InitialValue\", _prefilledModel);");
        _ = sb.AppendLine("                    __guard.AddAttribute(gseq++, \"BeforeSubmit\", " + beforeSubmitFunc + ");");
        _ = sb.AppendLine("                    __guard.AddAttribute(gseq++, \"OnConfirmed\", EventCallback.Factory.Create(this, OnConfirmedAsync));");
        _ = sb.AppendLine("                    __guard.AddAttribute(gseq++, \"OnEditContextReady\", EventCallback.Factory.Create<EditContext>(this, OnFormEditContextReady));");
        _ = sb.AppendLine("                    __guard.CloseComponent();");
        _ = sb.AppendLine("                }));");
        _ = sb.AppendLine("                builder.CloseComponent();");
        _ = sb.AppendLine("                builder.CloseElement();");
        _ = sb.AppendLine("                break;");
        _ = sb.AppendLine("            }");

        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
    }

    private static string ToRenderMode(CommandDensity d) => d switch {
        CommandDensity.Inline => "Inline",
        CommandDensity.CompactInline => "CompactInline",
        CommandDensity.FullPage => "FullPage",
        _ => "FullPage",
    };

    /// <summary>Matches <see cref="CommandFormEmitter"/> — safe C# string literals for generated code.</summary>
    private static string EscapeString(string? value) {
        if (string.IsNullOrEmpty(value)) {
            return string.Empty;
        }

        return Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value!, quote: false);
    }

    /// <summary>Story 2-2 code-review D12 — reduce a command FQN to a stable CSS/HTML id.</summary>
    private static string SanitizeCssId(string value) {
        if (string.IsNullOrEmpty(value)) {
            return "unknown";
        }

        StringBuilder sb = new(value.Length);
        foreach (char c in value) {
            _ = sb.Append(char.IsLetterOrDigit(c) ? c : '-');
        }

        return sb.ToString();
    }
}
