using System.Text;

using Hexalith.FrontComposer.SourceTools.Transforms;

using Microsoft.CodeAnalysis.CSharp;

namespace Hexalith.FrontComposer.SourceTools.Emitters;

/// <summary>
/// Story 2-2 Task 4.5 — emits <c>{CommandTypeName}Page.g.razor.cs</c>: a routable page
/// composing the route header and FullPage renderer under <c>/commands/{BoundedContext}/{CommandTypeName}</c>.
/// Dispatches the <c>RestoreGridStateAction</c> on mount (Decision D30 — reducer-only no-op today).
/// </summary>
public static class CommandPageEmitter {
    public static string Emit(CommandRendererModel model) {
        if (model is null) {
            throw new ArgumentNullException(nameof(model));
        }

        StringBuilder sb = new(2048);
        _ = sb.AppendLine("// Generated by FrontComposer source generator (Story 2-2 Task 4.5)");
        _ = sb.AppendLine("// Do not edit directly");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine("using Fluxor;");
        _ = sb.AppendLine("using Hexalith.FrontComposer.Contracts.Rendering;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components.Rendering;");
        _ = sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace) {
            _ = sb.AppendLine("namespace " + model.Namespace + ";");
            _ = sb.AppendLine();
        }

        string pageName = model.TypeName + "Page";
        string rendererFqn = string.IsNullOrEmpty(model.Namespace) ? model.TypeName + "Renderer" : model.Namespace + "." + model.TypeName + "Renderer";
        string route = model.FullPageRoute;
        string pageTitleText = EscapeString(model.DisplayLabel);

        _ = sb.AppendLine("/// <summary>Generated routable page composing a route header and FullPage renderer (Story 2-2 Decision D5 + D22).</summary>");
        _ = sb.AppendLine("[Route(\"" + route + "\")]");
        _ = sb.AppendLine("public partial class " + pageName + " : ComponentBase");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    [Inject] private IDispatcher Dispatcher { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private NavigationManager NavigationManager { get; set; } = default!;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    protected override void OnInitialized()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        // Story 2-2 Decision D10 + D30: dispatch RestoreGridStateAction; effect landing in Story 4.3.");
        _ = sb.AppendLine("        string? viewKey = InferReturnViewKeyFromReferrer();");
        _ = sb.AppendLine("        if (!string.IsNullOrWhiteSpace(viewKey))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            Dispatcher.Dispatch(new global::Hexalith.FrontComposer.Shell.State.DataGridNavigation.RestoreGridStateAction(viewKey));");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private string? InferReturnViewKeyFromReferrer()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        Uri uri = NavigationManager.ToAbsoluteUri(NavigationManager.Uri);");
        _ = sb.AppendLine("        if (string.IsNullOrWhiteSpace(uri.Query))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return null;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        string? projectionTypeFqn = null;");
        _ = sb.AppendLine("        foreach (string pair in uri.Query.TrimStart('?').Split('&', StringSplitOptions.RemoveEmptyEntries))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            string[] segments = pair.Split('=', 2);");
        _ = sb.AppendLine("            string key = Uri.UnescapeDataString(segments[0]);");
        _ = sb.AppendLine("            string value = segments.Length > 1 ? Uri.UnescapeDataString(segments[1]) : string.Empty;");
        _ = sb.AppendLine("            if (string.IsNullOrWhiteSpace(value))");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                continue;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            if (string.Equals(key, \"viewKey\", StringComparison.OrdinalIgnoreCase))");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                return value;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            if (string.Equals(key, \"projectionTypeFqn\", StringComparison.OrdinalIgnoreCase))");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                projectionTypeFqn = value;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        return string.IsNullOrWhiteSpace(projectionTypeFqn)");
        _ = sb.AppendLine("            ? null");
        _ = sb.AppendLine("            : \"" + EscapeString(model.BoundedContext ?? "Default") + ":\" + projectionTypeFqn;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    protected override void BuildRenderTree(RenderTreeBuilder builder)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        int seq = 0;");
        _ = sb.AppendLine("        builder.OpenComponent<global::Microsoft.FluentUI.AspNetCore.Components.FluentStack>(seq++);");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"Orientation\", global::Microsoft.FluentUI.AspNetCore.Components.Orientation.Vertical);");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"VerticalGap\", \"24px\");");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"ChildContent\", (RenderFragment)(__page =>");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            int pseq = 0;");
        _ = sb.AppendLine("            __page.OpenComponent<global::Hexalith.FrontComposer.Shell.Components.Layout.FcPageHeader>(pseq++);");
        _ = sb.AppendLine("            __page.AddAttribute(pseq++, \"PageTitle\", \"" + pageTitleText + "\");");
        _ = sb.AppendLine("            __page.AddAttribute(pseq++, \"Heading\", \"" + pageTitleText + "\");");
        _ = sb.AppendLine("            __page.AddAttribute(pseq++, \"HeadingTabIndex\", (int?)-1);");
        _ = sb.AppendLine("            __page.CloseComponent();");
        _ = sb.AppendLine("            __page.OpenComponent<" + rendererFqn + ">(pseq++);");
        _ = sb.AppendLine("            __page.AddAttribute(pseq++, \"RenderMode\", (CommandRenderMode?)CommandRenderMode.FullPage);");
        _ = sb.AppendLine("            __page.CloseComponent();");
        _ = sb.AppendLine("        }));");
        _ = sb.AppendLine("        builder.CloseComponent();");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");

        // Story 11.21 ASP0006 — the emitters above write runtime `seq++` counters; the rewriter
        // converts each call site to the literal for its position in this document, and fails the
        // generation rather than emitting a counter this output has no control for.
        return RenderTreeSequenceRewriter.AssignLiteralsOrFail(sb.ToString());
    }

    /// <summary>Delegates to <see cref="GeneratedLiteral.Escape"/> — the single escaping helper
    /// (quote-safe; <c>FormatLiteral(quote: false)</c> did not escape embedded double quotes).</summary>
    private static string EscapeString(string? value)
        => string.IsNullOrEmpty(value) ? string.Empty : GeneratedLiteral.Escape(value!);
}
