using System.Text;

using Hexalith.FrontComposer.SourceTools.Transforms;

namespace Hexalith.FrontComposer.SourceTools.Emitters;

/// <summary>
/// Emits the static actions wrapper class containing the 5-state lifecycle action records.
/// </summary>
public static class CommandFluxorActionsEmitter {
    /// <summary>
    /// Generates the actions wrapper source code.
    /// </summary>
    public static string Emit(CommandFluxorModel model) {
        var sb = new StringBuilder(1024);
        _ = sb.AppendLine("// Generated by FrontComposer source generator");
        _ = sb.AppendLine("// Do not edit directly");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace) {
            _ = sb.AppendLine("namespace " + model.Namespace + ";");
            _ = sb.AppendLine();
        }

        _ = sb.AppendLine("/// <summary>Wrapper for <see cref=\"" + model.TypeName + "\"/> lifecycle action records.</summary>");
        _ = sb.AppendLine("public static class " + model.ActionsWrapperName);
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    /// <summary>User clicked submit -- command is being dispatched.</summary>");
        _ = sb.AppendLine("    public sealed record SubmittedAction(string CorrelationId, " + model.CommandFullyQualifiedName + " Command);");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <summary>Command service returned a MessageId (EventStore 202).</summary>");
        _ = sb.AppendLine("    public sealed record AcknowledgedAction(string CorrelationId, string MessageId);");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <summary>Projection is being updated (SignalR catch-up in flight).</summary>");
        _ = sb.AppendLine("    public sealed record SyncingAction(string CorrelationId);");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <summary>Projection state confirmed -- the command fully resolved.</summary>");
        _ = sb.AppendLine("    public sealed record ConfirmedAction(string CorrelationId);");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <summary>Command rejected by the domain. Form retains its field values.</summary>");
        _ = sb.AppendLine("    public sealed record RejectedAction(string CorrelationId, string Reason, string Resolution);");
        _ = sb.AppendLine("}");

        return sb.ToString();
    }
}
