using System.Text;

using Hexalith.FrontComposer.SourceTools.Parsing;
using Hexalith.FrontComposer.SourceTools.Transforms;

namespace Hexalith.FrontComposer.SourceTools.Emitters;

/// <summary>
/// Story 2-2 Task 4 — emits <c>{CommandTypeName}Renderer.g.razor.cs</c>: the chrome around the
/// Story 2-1 form (ADR-016 — renderer never emits <c>&lt;EditForm&gt;</c>). Selects the rendering
/// shape (Inline / CompactInline / FullPage) from the density-derived default or the explicit
/// <c>RenderMode</c> parameter.
/// </summary>
/// <remarks>
/// Story 2-2 emits layout chrome via Fluent UI primitives (buttons, popover, card, breadcrumb link)
/// around the Story 2-1 <c>{Cmd}Form</c> per ADR-016. The form still owns <c>EditForm</c>, validation,
/// and lifecycle dispatch; this emitter focuses on density-driven shape and wiring (D5, D6, D21).
/// </remarks>
public static class CommandRendererEmitter {
    public static string Emit(CommandRendererModel model) {
        if (model is null) {
            throw new ArgumentNullException(nameof(model));
        }

        StringBuilder sb = new(4096);
        _ = sb.AppendLine("// Generated by FrontComposer source generator (Story 2-2 Task 4)");
        _ = sb.AppendLine("// Do not edit directly");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine("#pragma warning disable ASP0006");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine("using System.Collections.Generic;");
        _ = sb.AppendLine("using System.Globalization;");
        _ = sb.AppendLine("using System.Reflection;");
        _ = sb.AppendLine("using System.Threading.Tasks;");
        _ = sb.AppendLine("using Fluxor;");
        _ = sb.AppendLine("using Hexalith.FrontComposer.Contracts;");
        _ = sb.AppendLine("using Hexalith.FrontComposer.Contracts.Communication;");
        _ = sb.AppendLine("using Hexalith.FrontComposer.Contracts.Rendering;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components.Rendering;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components.Web;");
        _ = sb.AppendLine("using Microsoft.FluentUI.AspNetCore.Components;");
        _ = sb.AppendLine("using Microsoft.Extensions.Logging;");
        _ = sb.AppendLine("using Microsoft.Extensions.Options;");
        _ = sb.AppendLine("using Microsoft.JSInterop;");
        _ = sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace) {
            _ = sb.AppendLine("namespace " + model.Namespace + ";");
            _ = sb.AppendLine();
        }

        string rendererName = model.TypeName + "Renderer";
        string defaultModeLiteral = "CommandRenderMode." + ToRenderMode(model.Density);
        string commandFqn = model.CommandFullyQualifiedName;
        string displayLabelEscaped = EscapeString(model.DisplayLabel);
        string densityName = model.Density.ToString();
        string lifecycleStateTypeFqn = string.IsNullOrEmpty(model.Namespace)
            ? model.StateName
            : model.Namespace + "." + model.StateName;

        _ = sb.AppendLine("/// <summary>Auto-generated density-driven renderer for <see cref=\"" + model.TypeName + "\"/> (Story 2-2).</summary>");
        _ = sb.AppendLine("public partial class " + rendererName + " : ComponentBase, IInlinePopover");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    [Parameter] public CommandRenderMode? RenderMode { get; set; }");
        _ = sb.AppendLine("    [Parameter] public " + commandFqn + "? InitialValue { get; set; }");
        _ = sb.AppendLine("    [CascadingParameter] public ProjectionContext? ProjectionContext { get; set; }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    [Inject] private IEnumerable<IDerivedValueProvider> DerivedValueProviders { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private IOptions<FcShellOptions> ShellOptions { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private IJSRuntime JSRuntime { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private InlinePopoverRegistry InlinePopoverRegistry { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private NavigationManager NavigationManager { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private ILogger<" + rendererName + ">? Logger { get; set; }");
        _ = sb.AppendLine("    [Inject] private ICommandPageContext PageContext { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private IState<" + lifecycleStateTypeFqn + "> _lifecycleState { get; set; } = default!;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private CommandRenderMode _effectiveMode;");
        _ = sb.AppendLine("    private bool _popoverOpen;");
        _ = sb.AppendLine("    private ElementReference _compactCardRef;");
        _ = sb.AppendLine("    private readonly string _triggerButtonId = \"fc-trigger-\" + Guid.NewGuid().ToString(\"N\");");
        _ = sb.AppendLine("    private Action? _externalSubmit;");
        _ = sb.AppendLine("    private IJSObjectReference? _expandInRowModule;");
        _ = sb.AppendLine("    private " + commandFqn + " _prefilledModel = new();");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    protected override async Task OnInitializedAsync()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        _effectiveMode = RenderMode ?? " + defaultModeLiteral + ";");
        _ = sb.AppendLine("        if (RenderMode.HasValue && !IsCompatibleOverride(RenderMode.Value))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            Logger?.LogWarning(\"HFC1015: RenderMode {Mode} incompatible with " + model.TypeName + " density " + densityName + "\", _effectiveMode);");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        Logger?.LogInformation(\"Rendering {CommandType} in {Mode} (density=" + densityName + ")\", \"" + commandFqn + "\", _effectiveMode);");
        _ = sb.AppendLine("        _prefilledModel = InitialValue ?? new();");
        _ = sb.AppendLine("        await PrefillDerivableFieldsAsync().ConfigureAwait(false);");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private static bool IsCompatibleOverride(CommandRenderMode mode)");
        _ = sb.AppendLine("        => mode != CommandRenderMode.Inline || " + (model.NonDerivablePropertyNames.Count <= 1 ? "true" : "false") + ";");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private async Task PrefillDerivableFieldsAsync()");
        _ = sb.AppendLine("    {");
        foreach (string propertyName in model.DerivablePropertyNames) {
            string escapedPropertyName = EscapeString(propertyName);
            _ = sb.AppendLine("        await TryPrefillPropertyAsync(\"" + escapedPropertyName + "\").ConfigureAwait(false);");
        }
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private Task RefreshDerivedValuesBeforeSubmitAsync()");
        _ = sb.AppendLine("        => PrefillDerivableFieldsAsync();");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private async Task TryPrefillPropertyAsync(string propertyName)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        foreach (IDerivedValueProvider provider in DerivedValueProviders)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            DerivedValueResult result = await provider.ResolveAsync(typeof(" + commandFqn + "), propertyName, ProjectionContext, default).ConfigureAwait(false);");
        _ = sb.AppendLine("            if (!result.HasValue)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                continue;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            if (TrySetPropertyValue(propertyName, result.Value))");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                return;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine();
            _ = sb.AppendLine("            Logger?.LogWarning(\"Derived value for {PropertyName} on {CommandType} could not be assigned.\", propertyName, \"" + commandFqn + "\");");
        _ = sb.AppendLine("            continue;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        Logger?.LogWarning(\"No derived value could be resolved for {PropertyName} on {CommandType}; leaving default value in place.\", propertyName, \"" + commandFqn + "\");");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private bool TrySetPropertyValue(string propertyName, object? value)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        PropertyInfo? property = typeof(" + commandFqn + ").GetProperty(propertyName, BindingFlags.Public | BindingFlags.Instance);");
        _ = sb.AppendLine("        if (property is null || !property.CanWrite)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return false;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        if (value is null)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            property.SetValue(_prefilledModel, null);");
        _ = sb.AppendLine("            return true;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        Type targetType = Nullable.GetUnderlyingType(property.PropertyType) ?? property.PropertyType;");
        _ = sb.AppendLine("        object? converted = value;");
        _ = sb.AppendLine("        if (!targetType.IsInstanceOfType(value))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            try");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                if (targetType.IsEnum)");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    converted = value is string s");
        _ = sb.AppendLine("                        ? Enum.Parse(targetType, s, ignoreCase: true)");
        _ = sb.AppendLine("                        : Enum.ToObject(targetType, value);");
        _ = sb.AppendLine("                }");
        _ = sb.AppendLine("                else if (targetType == typeof(Guid))");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    converted = value is Guid guid ? guid : Guid.Parse(Convert.ToString(value, CultureInfo.InvariantCulture)!);");
        _ = sb.AppendLine("                }");
        _ = sb.AppendLine("                else if (targetType == typeof(DateTimeOffset))");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    converted = value is DateTimeOffset dto");
        _ = sb.AppendLine("                        ? dto");
        _ = sb.AppendLine("                        : DateTimeOffset.Parse(Convert.ToString(value, CultureInfo.InvariantCulture)!, CultureInfo.InvariantCulture);");
        _ = sb.AppendLine("                }");
        _ = sb.AppendLine("                else");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    converted = Convert.ChangeType(value, targetType, CultureInfo.InvariantCulture);");
        _ = sb.AppendLine("                }");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("            catch");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                return false;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        property.SetValue(_prefilledModel, converted);");
        _ = sb.AppendLine("        return true;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private Icon? ResolveIcon()");
        _ = sb.AppendLine("    {");
        if (!string.IsNullOrEmpty(model.IconName)) {
            _ = sb.AppendLine("        if (TryResolveIcon(\"" + EscapeString(model.IconName!) + "\", out Icon? configured))");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            return configured;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        Logger?.LogWarning(\"Icon '{IconName}' failed to resolve on {CommandType}; falling back to Play.\", \"" + EscapeString(model.IconName!) + "\", \"" + commandFqn + "\");");
        }
        _ = sb.AppendLine("        return TryResolveIcon(\"Regular.Size16.Play\", out Icon? fallback) ? fallback : null;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private static bool TryResolveIcon(string iconName, out Icon? icon)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        icon = null;");
        _ = sb.AppendLine("        if (string.IsNullOrWhiteSpace(iconName))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return false;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        // FluentUI v5 icon classes are nested under the `Icons` static class and live in");
        _ = sb.AppendLine("        // per-variant satellite assemblies (Icons.Regular, Icons.Filled, Icons.Light, Icons.Color).");
        _ = sb.AppendLine("        // The icon-name format is `Variant.SizeNN.Name`, so the variant prefix selects the assembly.");
        _ = sb.AppendLine("        try");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            int firstDot = iconName.IndexOf('.');");
        _ = sb.AppendLine("            string variant = firstDot > 0 ? iconName.Substring(0, firstDot) : iconName;");
        _ = sb.AppendLine("            string assemblyName = \"Microsoft.FluentUI.AspNetCore.Components.Icons.\" + variant;");
        _ = sb.AppendLine("            string typeName = \"Microsoft.FluentUI.AspNetCore.Components.Icons+\" + iconName.Replace('.', '+') + \", \" + assemblyName;");
        _ = sb.AppendLine("            Type? type = Type.GetType(typeName, throwOnError: false);");
        _ = sb.AppendLine("            if (type is null)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                return false;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            icon = Activator.CreateInstance(type) as Icon;");
        _ = sb.AppendLine("            return icon is not null;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        catch");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            icon = null;");
        _ = sb.AppendLine("            return false;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    private void OnFormRegisteredExternalSubmit(Action submit)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        _externalSubmit = submit;");
        _ = sb.AppendLine("        _ = InvokeAsync(StateHasChanged);");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    private Task OnZeroFieldClickAsync()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        _externalSubmit?.Invoke();");
        _ = sb.AppendLine("        return Task.CompletedTask;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    private async Task OpenPopoverAsync()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        await InlinePopoverRegistry.OpenAsync(this).ConfigureAwait(false);");
        _ = sb.AppendLine("        _popoverOpen = true;");
        _ = sb.AppendLine("        await InvokeAsync(StateHasChanged).ConfigureAwait(false);");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    /// <inheritdoc/>");
        _ = sb.AppendLine("    public async Task ClosePopoverAsync()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (!_popoverOpen) return;");
        _ = sb.AppendLine("        _popoverOpen = false;");
        _ = sb.AppendLine("        InlinePopoverRegistry.Released(this);");
        _ = sb.AppendLine("        try");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            _expandInRowModule ??= await JSRuntime.InvokeAsync<IJSObjectReference>(\"import\", \"./_content/Hexalith.FrontComposer.Shell/js/fc-expandinrow.js\").ConfigureAwait(false);");
        _ = sb.AppendLine("            await _expandInRowModule.InvokeVoidAsync(\"focusTriggerElementById\", _triggerButtonId).ConfigureAwait(false);");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        catch (InvalidOperationException) { /* prerender or unavailable JS runtime. */ }");
        _ = sb.AppendLine("        catch (JSDisconnectedException) { /* circuit teardown; benign. */ }");
        _ = sb.AppendLine("        await InvokeAsync(StateHasChanged).ConfigureAwait(false);");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    private Task HandleEscape(KeyboardEventArgs e)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        return e.Key == \"Escape\" && _popoverOpen ? ClosePopoverAsync() : Task.CompletedTask;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    private Task OnConfirmedAsync()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (_effectiveMode == CommandRenderMode.Inline && _popoverOpen)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return ClosePopoverAsync();");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        if (_effectiveMode == CommandRenderMode.FullPage)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            NavigateToReturnPath();");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        return Task.CompletedTask;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    private void NavigateToReturnPath()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        string? path = GetRawReturnPath();");
        _ = sb.AppendLine("        if (IsValidRelativeReturnPath(path))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            NavigationManager.NavigateTo(path!);");
        _ = sb.AppendLine("            return;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        if (!string.IsNullOrEmpty(path))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            Logger?.LogError(\"D32: ReturnPath '{Path}' rejected as invalid-relative; navigating home. CorrelationId={CorrelationId}\", path, ResolveLoggingCorrelationId());");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        NavigationManager.NavigateTo(\"/\");");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private static bool IsValidRelativeReturnPath(string? path)");
        _ = sb.AppendLine("        => !string.IsNullOrWhiteSpace(path)");
        _ = sb.AppendLine("            && System.Uri.IsWellFormedUriString(path, System.UriKind.Relative)");
        _ = sb.AppendLine("            && !path.StartsWith(\"//\", StringComparison.Ordinal);");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private string? GetRawReturnPath()");
        _ = sb.AppendLine("        => !string.IsNullOrWhiteSpace(PageContext.ReturnPath) ? PageContext.ReturnPath : GetQueryParameter(\"returnPath\");");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private string? GetQueryParameter(string key)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (string.IsNullOrWhiteSpace(key))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return null;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        Uri uri = NavigationManager.ToAbsoluteUri(NavigationManager.Uri);");
        _ = sb.AppendLine("        if (string.IsNullOrWhiteSpace(uri.Query))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return null;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        foreach (string pair in uri.Query.TrimStart('?').Split('&', StringSplitOptions.RemoveEmptyEntries))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            string[] segments = pair.Split('=', 2);");
        _ = sb.AppendLine("            string currentKey = Uri.UnescapeDataString(segments[0]);");
        _ = sb.AppendLine("            if (!string.Equals(currentKey, key, StringComparison.OrdinalIgnoreCase))");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                continue;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            return segments.Length > 1 ? Uri.UnescapeDataString(segments[1]) : string.Empty;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        return null;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private string GetBreadcrumbReturnPath()");
        _ = sb.AppendLine("        => IsValidRelativeReturnPath(GetRawReturnPath()) ? GetRawReturnPath()! : \"/\";");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private string GetBreadcrumbBoundedContext()");
        _ = sb.AppendLine("        => !string.IsNullOrWhiteSpace(PageContext.BoundedContext) ? PageContext.BoundedContext : \"" + EscapeString(model.BoundedContext ?? "Default") + "\";");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private string? ResolveLoggingCorrelationId()");
        _ = sb.AppendLine("        => _lifecycleState.Value.CorrelationId;");
        _ = sb.AppendLine();

        _ = sb.AppendLine("    protected override async Task OnAfterRenderAsync(bool firstRender)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (firstRender && _effectiveMode == CommandRenderMode.CompactInline)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            try");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                _expandInRowModule ??= await JSRuntime.InvokeAsync<IJSObjectReference>(\"import\", \"./_content/Hexalith.FrontComposer.Shell/js/fc-expandinrow.js\").ConfigureAwait(false);");
        _ = sb.AppendLine("                await _expandInRowModule.InvokeVoidAsync(\"initializeExpandInRow\", _compactCardRef).ConfigureAwait(false);");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("            catch (InvalidOperationException) { /* prerender: JSInterop not yet available. */ }");
        _ = sb.AppendLine("            catch (JSDisconnectedException) { /* circuit teardown; benign. */ }");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        // BuildRenderTree — dispatches on _effectiveMode
        EmitBuildRenderTree(sb, model, displayLabelEscaped);

        _ = sb.AppendLine("}");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#pragma warning restore ASP0006");

        return sb.ToString();
    }

    private static void EmitBuildRenderTree(StringBuilder sb, CommandRendererModel model, string displayLabelEscaped) {
        string formFqn = string.IsNullOrEmpty(model.Namespace) ? model.FormComponentName : model.Namespace + "." + model.FormComponentName;
        int nonDerivableCount = model.NonDerivablePropertyNames.Count;
        string firstFieldName = nonDerivableCount >= 1 ? model.NonDerivablePropertyNames[0] : "";

        _ = sb.AppendLine("    protected override void BuildRenderTree(RenderTreeBuilder builder)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        int seq = 0;");
        _ = sb.AppendLine("        switch (_effectiveMode)");
        _ = sb.AppendLine("        {");

        _ = sb.AppendLine("            case CommandRenderMode.Inline:");
        _ = sb.AppendLine("            {");
        if (nonDerivableCount == 0) {
            _ = sb.AppendLine("                builder.OpenComponent<FluentButton>(seq++);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Id\", _triggerButtonId);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Type\", ButtonType.Button);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Appearance\", ButtonAppearance.Outline);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Disabled\", _externalSubmit is null);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"IconStart\", ResolveIcon());");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Label\", \"" + displayLabelEscaped + "\");");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"OnClick\", EventCallback.Factory.Create<MouseEventArgs>(this, _ => OnZeroFieldClickAsync()));");
            _ = sb.AppendLine("                builder.CloseComponent();");
            _ = sb.AppendLine();
            _ = sb.AppendLine("                builder.OpenElement(seq++, \"div\");");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"style\", \"display:none\");");
            _ = sb.AppendLine("                builder.OpenComponent<" + formFqn + ">(seq++);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"InitialValue\", _prefilledModel);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"RegisterExternalSubmit\", (Action<Action>)OnFormRegisteredExternalSubmit);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"BeforeSubmit\", (Func<Task>)RefreshDerivedValuesBeforeSubmitAsync);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"OnConfirmed\", EventCallback.Factory.Create(this, OnConfirmedAsync));");
            _ = sb.AppendLine("                builder.CloseComponent();");
            _ = sb.AppendLine("                builder.CloseElement();");
        }
        else {
            _ = sb.AppendLine("                builder.OpenComponent<FluentButton>(seq++);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Id\", _triggerButtonId);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Type\", ButtonType.Button);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Appearance\", ButtonAppearance.Outline);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"IconStart\", ResolveIcon());");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Label\", \"" + displayLabelEscaped + "\");");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"OnClick\", EventCallback.Factory.Create<MouseEventArgs>(this, _ => OpenPopoverAsync()));");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"aria-expanded\", _popoverOpen);");
            _ = sb.AppendLine("                builder.CloseComponent();");
            _ = sb.AppendLine();
            _ = sb.AppendLine("                builder.OpenComponent<FluentPopover>(seq++);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"AnchorId\", _triggerButtonId);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Opened\", _popoverOpen);");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"OpenedChanged\", EventCallback.Factory.Create<bool>(this, value => _popoverOpen = value));");
            _ = sb.AppendLine("                builder.AddAttribute(seq++, \"ChildContent\", (RenderFragment)(__popover =>");
            _ = sb.AppendLine("                {");
            _ = sb.AppendLine("                    int pseq = 0;");
            _ = sb.AppendLine("                    __popover.OpenElement(pseq++, \"div\");");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"class\", \"fc-popover\");");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"onkeydown\", EventCallback.Factory.Create<KeyboardEventArgs>(this, HandleEscape));");
            _ = sb.AppendLine("                    __popover.OpenComponent<" + formFqn + ">(pseq++);");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"InitialValue\", _prefilledModel);");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"ShowFieldsOnly\", new[] { \"" + firstFieldName + "\" });");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"BeforeSubmit\", (Func<Task>)RefreshDerivedValuesBeforeSubmitAsync);");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"OnConfirmed\", EventCallback.Factory.Create(this, OnConfirmedAsync));");
            _ = sb.AppendLine("                    __popover.CloseComponent();");
            _ = sb.AppendLine("                    __popover.OpenComponent<FluentButton>(pseq++);");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"Type\", ButtonType.Button);");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"Appearance\", ButtonAppearance.Outline);");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"Label\", \"Cancel\");");
            _ = sb.AppendLine("                    __popover.AddAttribute(pseq++, \"OnClick\", EventCallback.Factory.Create<MouseEventArgs>(this, _ => ClosePopoverAsync()));");
            _ = sb.AppendLine("                    __popover.CloseComponent();");
            _ = sb.AppendLine("                    __popover.CloseElement();");
            _ = sb.AppendLine("                }));");
            _ = sb.AppendLine("                builder.CloseComponent();");
        }

        _ = sb.AppendLine("                break;");
        _ = sb.AppendLine("            }");

        _ = sb.AppendLine("            case CommandRenderMode.CompactInline:");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                builder.OpenElement(seq++, \"div\");");
        _ = sb.AppendLine("                builder.AddAttribute(seq++, \"class\", \"fc-expand-in-row\");");
        _ = sb.AppendLine("                builder.AddElementReferenceCapture(seq++, r => _compactCardRef = r);");
        _ = sb.AppendLine("                builder.OpenComponent<FluentCard>(seq++);");
        _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Appearance\", CardAppearance.Outline);");
        _ = sb.AppendLine("                builder.AddAttribute(seq++, \"Shadow\", CardShadow.Small);");
        _ = sb.AppendLine("                builder.AddAttribute(seq++, \"ChildContent\", (RenderFragment)(__card =>");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    int cseq = 0;");
        _ = sb.AppendLine("                    __card.OpenComponent<" + formFqn + ">(cseq++);");
        _ = sb.AppendLine("                    __card.AddAttribute(cseq++, \"InitialValue\", _prefilledModel);");
        _ = sb.AppendLine("                    __card.AddAttribute(cseq++, \"DerivableFieldsHidden\", true);");
        _ = sb.AppendLine("                    __card.AddAttribute(cseq++, \"BeforeSubmit\", (Func<Task>)RefreshDerivedValuesBeforeSubmitAsync);");
        _ = sb.AppendLine("                    __card.AddAttribute(cseq++, \"OnConfirmed\", EventCallback.Factory.Create(this, OnConfirmedAsync));");
        _ = sb.AppendLine("                    __card.CloseComponent();");
        _ = sb.AppendLine("                }));");
        _ = sb.AppendLine("                builder.CloseComponent();");
        _ = sb.AppendLine("                builder.CloseElement();");
        _ = sb.AppendLine("                break;");
        _ = sb.AppendLine("            }");

        _ = sb.AppendLine("            case CommandRenderMode.FullPage:");
        _ = sb.AppendLine("            default:");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                var opts = ShellOptions.Value;");
        _ = sb.AppendLine("                builder.OpenElement(seq++, \"div\");");
        _ = sb.AppendLine("                builder.AddAttribute(seq++, \"style\", $\"max-width: {opts.FullPageFormMaxWidth}; margin: 0 auto;\");");
        _ = sb.AppendLine("                if (opts.EmbeddedBreadcrumb)");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    builder.OpenElement(seq++, \"nav\");");
        _ = sb.AppendLine("                    builder.AddAttribute(seq++, \"aria-label\", \"breadcrumb\");");
        _ = sb.AppendLine("                    builder.OpenComponent<FluentLink>(seq++);");
        _ = sb.AppendLine("                    builder.AddAttribute(seq++, \"Href\", GetBreadcrumbReturnPath());");
        _ = sb.AppendLine("                    builder.AddAttribute(seq++, \"Appearance\", LinkAppearance.Subtle);");
        _ = sb.AppendLine("                    builder.AddAttribute(seq++, \"ChildContent\", (RenderFragment)(__link =>");
        _ = sb.AppendLine("                    {");
        _ = sb.AppendLine("                        __link.AddContent(0, GetBreadcrumbBoundedContext());");
        _ = sb.AppendLine("                    }));");
        _ = sb.AppendLine("                    builder.CloseComponent();");
        _ = sb.AppendLine("                    builder.AddContent(seq++, \" > " + displayLabelEscaped + "\");");
        _ = sb.AppendLine("                    builder.CloseElement();");
        _ = sb.AppendLine("                }");
        _ = sb.AppendLine("                builder.OpenComponent<" + formFqn + ">(seq++);");
        _ = sb.AppendLine("                builder.AddAttribute(seq++, \"InitialValue\", _prefilledModel);");
        _ = sb.AppendLine("                builder.AddAttribute(seq++, \"BeforeSubmit\", (Func<Task>)RefreshDerivedValuesBeforeSubmitAsync);");
        _ = sb.AppendLine("                builder.AddAttribute(seq++, \"OnConfirmed\", EventCallback.Factory.Create(this, OnConfirmedAsync));");
        _ = sb.AppendLine("                builder.CloseComponent();");
        _ = sb.AppendLine("                builder.CloseElement();");
        _ = sb.AppendLine("                break;");
        _ = sb.AppendLine("            }");

        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
    }

    private static string ToRenderMode(CommandDensity d) => d switch {
        CommandDensity.Inline => "Inline",
        CommandDensity.CompactInline => "CompactInline",
        CommandDensity.FullPage => "FullPage",
        _ => "FullPage",
    };

    /// <summary>Matches <see cref="CommandFormEmitter"/> — safe C# string literals for generated code.</summary>
    private static string EscapeString(string? value) {
        if (string.IsNullOrEmpty(value)) {
            return string.Empty;
        }

        return Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value!, quote: false);
    }
}
