using System.Text;

using Hexalith.FrontComposer.SourceTools.Transforms;

using Microsoft.CodeAnalysis.CSharp;

namespace Hexalith.FrontComposer.SourceTools.Emitters;

/// <summary>
/// Story 2-2 Task 4.5 — emits <c>{CommandTypeName}Page.g.razor.cs</c>: a routable wrapper
/// hosting the FullPage renderer under <c>/commands/{BoundedContext}/{CommandTypeName}</c>.
/// Dispatches the <c>RestoreGridStateAction</c> on mount (Decision D30 — reducer-only no-op today).
/// </summary>
public static class CommandPageEmitter {
    public static string Emit(CommandRendererModel model) {
        if (model is null) {
            throw new ArgumentNullException(nameof(model));
        }

        StringBuilder sb = new(2048);
        _ = sb.AppendLine("// Generated by FrontComposer source generator (Story 2-2 Task 4.5)");
        _ = sb.AppendLine("// Do not edit directly");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine("using Fluxor;");
        _ = sb.AppendLine("using Hexalith.FrontComposer.Contracts.Rendering;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components.Rendering;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components.Web;");
        _ = sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace) {
            _ = sb.AppendLine("namespace " + model.Namespace + ";");
            _ = sb.AppendLine();
        }

        string pageName = model.TypeName + "Page";
        string rendererFqn = string.IsNullOrEmpty(model.Namespace) ? model.TypeName + "Renderer" : model.Namespace + "." + model.TypeName + "Renderer";
        string route = model.FullPageRoute;
        string pageTitleText = EscapeString(model.DisplayLabel);

        _ = sb.AppendLine("/// <summary>Generated routable host for the FullPage renderer (Story 2-2 Decision D5 + D22).</summary>");
        _ = sb.AppendLine("[Route(\"" + route + "\")]");
        _ = sb.AppendLine("public partial class " + pageName + " : ComponentBase");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    [Inject] private IDispatcher Dispatcher { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private NavigationManager NavigationManager { get; set; } = default!;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    protected override void OnInitialized()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        // Story 2-2 Decision D10 + D30: dispatch RestoreGridStateAction; effect landing in Story 4.3.");
        _ = sb.AppendLine("        string? viewKey = InferReturnViewKeyFromReferrer();");
        _ = sb.AppendLine("        if (!string.IsNullOrWhiteSpace(viewKey))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            Dispatcher.Dispatch(new RestoreGridStateAction(viewKey));");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private string? InferReturnViewKeyFromReferrer()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        Uri uri = NavigationManager.ToAbsoluteUri(NavigationManager.Uri);");
        _ = sb.AppendLine("        if (string.IsNullOrWhiteSpace(uri.Query))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return null;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        string? projectionTypeFqn = null;");
        _ = sb.AppendLine("        foreach (string pair in uri.Query.TrimStart('?').Split('&', StringSplitOptions.RemoveEmptyEntries))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            string[] segments = pair.Split('=', 2);");
        _ = sb.AppendLine("            string key = Uri.UnescapeDataString(segments[0]);");
        _ = sb.AppendLine("            string value = segments.Length > 1 ? Uri.UnescapeDataString(segments[1]) : string.Empty;");
        _ = sb.AppendLine("            if (string.IsNullOrWhiteSpace(value))");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                continue;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            if (string.Equals(key, \"viewKey\", StringComparison.OrdinalIgnoreCase))");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                return value;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            if (string.Equals(key, \"projectionTypeFqn\", StringComparison.OrdinalIgnoreCase))");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                projectionTypeFqn = value;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        return string.IsNullOrWhiteSpace(projectionTypeFqn)");
        _ = sb.AppendLine("            ? null");
        _ = sb.AppendLine("            : \"" + EscapeString(model.BoundedContext ?? "Default") + ":\" + projectionTypeFqn;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    protected override void BuildRenderTree(RenderTreeBuilder builder)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        int seq = 0;");
        _ = sb.AppendLine("        builder.OpenComponent<PageTitle>(seq++);");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"ChildContent\", (RenderFragment)(__pageTitle => __pageTitle.AddContent(0, \"" + pageTitleText + "\")));");
        _ = sb.AppendLine("        builder.CloseComponent();");
        _ = sb.AppendLine("        builder.OpenComponent<" + rendererFqn + ">(seq++);");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"RenderMode\", (CommandRenderMode?)CommandRenderMode.FullPage);");
        _ = sb.AppendLine("        builder.CloseComponent();");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EscapeString(string? value) {
        if (string.IsNullOrEmpty(value)) {
            return string.Empty;
        }

        return SymbolDisplay.FormatLiteral(value!, quote: false);
    }
}
