using System.Text;

using Hexalith.FrontComposer.SourceTools.Transforms;

namespace Hexalith.FrontComposer.SourceTools.Emitters;

/// <summary>
/// Emits the Fluxor <c>LifecycleState</c> record, <c>LifecycleFeature</c>, and reducers for a command.
/// </summary>
public static class CommandFluxorFeatureEmitter {
    /// <summary>
    /// Generates the feature, state, and reducers source code.
    /// </summary>
    public static string Emit(CommandFluxorModel model) {
        var sb = new StringBuilder(2048);
        _ = sb.AppendLine("// Generated by FrontComposer source generator");
        _ = sb.AppendLine("// Do not edit directly");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using Hexalith.FrontComposer.Contracts.Lifecycle;");
        _ = sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace) {
            _ = sb.AppendLine("namespace " + model.Namespace + ";");
            _ = sb.AppendLine();
        }

        // State record. Story 2-5 Task 5.2b (ADR-026 alignment) — field rename
        // Error → RejectionReason, Resolution → RejectionResolution so the framework-emitted
        // feature state aligns with the adopter-side StubCommandServiceOptions naming.
        _ = sb.AppendLine("/// <summary>Fluxor lifecycle state for <see cref=\"" + model.TypeName + "\"/>.</summary>");
        _ = sb.AppendLine("public sealed record " + model.StateName + "(");
        _ = sb.AppendLine("    CommandLifecycleState State,");
        _ = sb.AppendLine("    string? CorrelationId,");
        _ = sb.AppendLine("    string? MessageId,");
        _ = sb.AppendLine("    string? RejectionReason,");
        _ = sb.AppendLine("    string? RejectionResolution);");
        _ = sb.AppendLine();

        // Feature class
        _ = sb.AppendLine("/// <summary>Fluxor feature that owns <see cref=\"" + model.StateName + "\"/>.</summary>");
        _ = sb.AppendLine("public class " + model.FeatureName + " : Fluxor.Feature<" + model.StateName + ">");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    /// <inheritdoc />");
        _ = sb.AppendLine("    public override string GetName() => \"" + model.FeatureQualifiedName + "\";");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <inheritdoc />");
        _ = sb.AppendLine("    protected override " + model.StateName + " GetInitialState()");
        _ = sb.AppendLine("        => new(CommandLifecycleState.Idle, null, null, null, null);");
        _ = sb.AppendLine("}");
        _ = sb.AppendLine();

        // Reducers
        _ = sb.AppendLine("/// <summary>Reducers for <see cref=\"" + model.StateName + "\"/>.</summary>");
        _ = sb.AppendLine("public static class " + model.ReducersClassName);
        _ = sb.AppendLine("{");
        string state = model.StateName;
        string actions = model.ActionsWrapperName;

        _ = sb.AppendLine("    [Fluxor.ReducerMethod]");
        _ = sb.AppendLine("    public static " + state + " OnSubmitted(" + state + " state, " + actions + ".SubmittedAction action)");
        _ = sb.AppendLine("        => state with { State = CommandLifecycleState.Submitting, CorrelationId = action.CorrelationId, RejectionReason = null, RejectionResolution = null };");
        _ = sb.AppendLine();
        // CorrelationId guard prevents stale in-flight callbacks from a prior submit from overwriting
        // the state of a new submit (see code-review 2026-04-15, patch P2).
        _ = sb.AppendLine("    [Fluxor.ReducerMethod]");
        _ = sb.AppendLine("    public static " + state + " OnAcknowledged(" + state + " state, " + actions + ".AcknowledgedAction action)");
        _ = sb.AppendLine("        => state.CorrelationId != action.CorrelationId");
        _ = sb.AppendLine("            ? state");
        _ = sb.AppendLine("            : state with { State = CommandLifecycleState.Acknowledged, MessageId = action.MessageId };");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    [Fluxor.ReducerMethod]");
        _ = sb.AppendLine("    public static " + state + " OnSyncing(" + state + " state, " + actions + ".SyncingAction action)");
        _ = sb.AppendLine("        => state.CorrelationId != action.CorrelationId");
        _ = sb.AppendLine("            ? state");
        _ = sb.AppendLine("            : state with { State = CommandLifecycleState.Syncing };");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    [Fluxor.ReducerMethod]");
        _ = sb.AppendLine("    public static " + state + " OnConfirmed(" + state + " state, " + actions + ".ConfirmedAction action)");
        _ = sb.AppendLine("        => state.CorrelationId != action.CorrelationId");
        _ = sb.AppendLine("            ? state");
        _ = sb.AppendLine("            : state with { State = CommandLifecycleState.Confirmed };");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    [Fluxor.ReducerMethod]");
        _ = sb.AppendLine("    public static " + state + " OnRejected(" + state + " state, " + actions + ".RejectedAction action)");
        _ = sb.AppendLine("        => state.CorrelationId != action.CorrelationId");
        _ = sb.AppendLine("            ? state");
        _ = sb.AppendLine("            : state with { State = CommandLifecycleState.Rejected, RejectionReason = action.Reason, RejectionResolution = action.Resolution };");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <summary>");
        _ = sb.AppendLine("    /// Resets lifecycle state to Idle (used after rejection to allow retry, or on form disposal).");
        _ = sb.AppendLine("    /// Guarded by CorrelationId so concurrent form instances sharing this feature state do not");
        _ = sb.AppendLine("    /// wipe each other's in-flight submissions. Patch 2026-04-16 P-11.");
        _ = sb.AppendLine("    /// </summary>");
        _ = sb.AppendLine("    [Fluxor.ReducerMethod]");
        _ = sb.AppendLine("    public static " + state + " OnResetToIdle(" + state + " state, " + actions + ".ResetToIdleAction action)");
        _ = sb.AppendLine("        => state.CorrelationId != action.CorrelationId");
        _ = sb.AppendLine("            ? state");
        _ = sb.AppendLine("            : new(CommandLifecycleState.Idle, null, null, null, null);");
        _ = sb.AppendLine("}");

        return sb.ToString();
    }
}
