using System.Text;

using Hexalith.FrontComposer.SourceTools.Transforms;

namespace Hexalith.FrontComposer.SourceTools.Emitters;

/// <summary>
/// Emits a Blazor command form partial class (.g.razor.cs) from a <see cref="CommandFormModel"/>.
/// </summary>
/// <remarks>
/// Decision D3: wraps the form in a standard Blazor <c>&lt;EditForm&gt;</c> -- <c>FluentEditForm</c>
/// does not exist in Fluent UI v5. Decision D11: emits <c>&lt;DataAnnotationsValidator /&gt;</c> so
/// adopters get validation via <c>[Required]</c>, <c>[Range]</c>, etc. without pulling in FluentValidation.
/// Decision D7: localizer is runtime-resolved through the emitted <c>ResolveLabel</c> helper.
/// Decision D13: visual feedback is limited to a <c>FluentProgressRing</c> inside the submit button
/// while the state is <c>Submitting</c>; richer lifecycle feedback lives in Story 2-4.
/// </remarks>
public static class CommandFormEmitter {
    /// <summary>
    /// Generates the command form partial class source.
    /// </summary>
    /// <param name="form">Form-rendering metadata.</param>
    /// <param name="fluxor">Companion Fluxor metadata that names the state, actions wrapper, and feature type.</param>
    /// <returns>The generated C# source code.</returns>
    public static string Emit(CommandFormModel form, CommandFluxorModel fluxor) {
        var sb = new StringBuilder(4096);

        _ = sb.AppendLine("// Generated by FrontComposer source generator");
        _ = sb.AppendLine("// Do not edit directly");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine("#pragma warning disable ASP0006 // seq++ pattern inside BuildRenderTree");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine("using System.Globalization;");
        _ = sb.AppendLine("using System.Linq;");
        _ = sb.AppendLine("using System.Threading;");
        _ = sb.AppendLine("using System.Threading.Tasks;");
        _ = sb.AppendLine("using Fluxor;");
        _ = sb.AppendLine("using Hexalith.FrontComposer.Contracts.Communication;");
        _ = sb.AppendLine("using Hexalith.FrontComposer.Contracts.Lifecycle;");
        _ = sb.AppendLine("using Hexalith.FrontComposer.Contracts.Rendering;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components.Authorization;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components.Forms;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components.Rendering;");
        _ = sb.AppendLine("using Microsoft.Extensions.Localization;");
        _ = sb.AppendLine("using Microsoft.Extensions.Logging;");
        _ = sb.AppendLine("using Microsoft.FluentUI.AspNetCore.Components;");
        // Story 2-4 D21 — emitter-written using so FcLifecycleWrapper resolves in the generated .g.cs
        // without relying on _Imports.razor (which source generators do not consult).
        _ = sb.AppendLine("using Hexalith.FrontComposer.Shell.Components.Lifecycle;");
        _ = sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(form.Namespace);
        if (hasNamespace) {
            _ = sb.AppendLine("namespace " + form.Namespace + ";");
            _ = sb.AppendLine();
        }

        string componentName = form.TypeName + "Form";
        string escapedButtonLabel = EscapeString(form.ButtonLabel);
        string commandFqn = form.CommandFullyQualifiedName;
        bool hasAuthorizationPolicy = !string.IsNullOrWhiteSpace(form.AuthorizationPolicyName);

        _ = sb.AppendLine("/// <summary>");
        _ = sb.AppendLine("/// Auto-generated command form for <see cref=\"" + form.TypeName + "\"/>.");
        _ = sb.AppendLine("/// </summary>");
        _ = sb.AppendLine("public partial class " + componentName + " : ComponentBase, IDisposable");
        _ = sb.AppendLine("{");

        _ = sb.AppendLine("    [Parameter] public " + commandFqn + "? InitialValue { get; set; }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <summary>Story 2-2 ADR-016: when true, derivable fields are not rendered (renderer pre-fills them).</summary>");
        _ = sb.AppendLine("    [Parameter] public bool DerivableFieldsHidden { get; set; }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <summary>Story 2-2 ADR-016: when non-null, only fields whose property name is in the set are rendered.</summary>");
        _ = sb.AppendLine("    [Parameter] public string[]? ShowFieldsOnly { get; set; }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <summary>Story 2-2 ADR-016: invoked after the form dispatches ConfirmedAction so the renderer can close popovers / navigate.</summary>");
        _ = sb.AppendLine("    [Parameter] public EventCallback OnConfirmed { get; set; }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <summary>Story 2-2 ADR-016 / Decision D36: renderer registers this callback on first render so the 0-field Inline button can synthesize a submit.</summary>");
        _ = sb.AppendLine("    [Parameter] public Action<Action>? RegisterExternalSubmit { get; set; }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <summary>Story 2-2 ADR-016: renderer hook invoked immediately before dispatch so derivable values can be refreshed per submit.</summary>");
        _ = sb.AppendLine("    [Parameter] public Func<Task>? BeforeSubmit { get; set; }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <summary>Story 2-5 Task 5.3: fired once after the form's EditContext is constructed so the renderer can wire validation gates and abandonment protection.</summary>");
        _ = sb.AppendLine("    [Parameter] public EventCallback<EditContext> OnEditContextReady { get; set; }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    [Inject] private IState<" + fluxor.StateName + "> LifecycleState { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private IDispatcher Dispatcher { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private ILastUsedSubscriberRegistry LastUsedSubscriberRegistry { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private global::Hexalith.FrontComposer.Contracts.Lifecycle.ILifecycleBridgeRegistry LifecycleBridgeRegistry { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private ICommandService CommandService { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private global::Hexalith.FrontComposer.Shell.State.PendingCommands.IPendingCommandStateService PendingCommandState { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private IStringLocalizer<" + commandFqn + "> Localizer { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private ILogger<" + componentName + ">? Logger { get; set; }");
        // Story 5-2 T5 — server-driven warning publication + auth-redirect seam (validation is applied via a stateless static helper).
        _ = sb.AppendLine("    [Inject] private global::Hexalith.FrontComposer.Shell.Services.Feedback.ICommandFeedbackPublisher CommandFeedbackPublisher { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private global::Hexalith.FrontComposer.Contracts.Communication.IAuthRedirector AuthRedirector { get; set; } = default!;");
        if (hasAuthorizationPolicy) {
            _ = sb.AppendLine("    [Inject] private global::Hexalith.FrontComposer.Shell.Services.Authorization.ICommandAuthorizationEvaluator CommandAuthorizationEvaluator { get; set; } = default!;");
            _ = sb.AppendLine("    [Inject] private IStringLocalizer<global::Hexalith.FrontComposer.Shell.Resources.FcShellResources> CommandAuthorizationLocalizer { get; set; } = default!;");
            _ = sb.AppendLine("    [Inject] private AuthenticationStateProvider AuthenticationStateProvider { get; set; } = default!;");
        }
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private " + commandFqn + " _model = new();");
        _ = sb.AppendLine("    private EditContext? _editContext;");
        _ = sb.AppendLine("    private ValidationMessageStore? _serverValidationMessages;");
        _ = sb.AppendLine("    private System.Collections.Generic.IReadOnlyList<string> _serverFormLevelErrors = System.Array.Empty<string>();");
        _ = sb.AppendLine("    private global::Hexalith.FrontComposer.Shell.Services.Feedback.CommandFeedbackWarning? _serverWarning;");
        _ = sb.AppendLine("    private CancellationTokenSource? _cts;");
        _ = sb.AppendLine("    private bool _disposed;");
        _ = sb.AppendLine("    private bool _externalSubmitRegistered;");
        _ = sb.AppendLine("    private string? _submittedCorrelationId;");
        if (hasAuthorizationPolicy) {
            _ = sb.AppendLine("    private bool _authorizationPresentationReady;");
            _ = sb.AppendLine("    private bool _authorizationPresentationAllowed;");
            // Pass 3 — sequence guard: each refresh stamps the counter; only the latest completion applies its result.
            _ = sb.AppendLine("    private int _authorizationRefreshSequence;");
            string authorizationPolicyLiteral = "\"" + EscapeString(form.AuthorizationPolicyName!) + "\"";
            string boundedContextLiteral = string.IsNullOrWhiteSpace(form.BoundedContext)
                ? "null"
                : "\"" + EscapeString(form.BoundedContext!) + "\"";
            _ = sb.AppendLine("    private const string AuthorizationPolicyName = " + authorizationPolicyLiteral + ";");
            _ = sb.AppendLine("    private const string? BoundedContextName = " + boundedContextLiteral + ";");
        }
        // Story 5-2 — per-command static allowlist (reflection default, stateless, safely cached).
        _ = sb.AppendLine("    private static readonly global::Hexalith.FrontComposer.Contracts.Communication.ICommandValidationFieldAllowlist _serverValidationAllowlist = new global::Hexalith.FrontComposer.Shell.Services.Validation.ReflectionCommandValidationFieldAllowlist<" + commandFqn + ">();");
        _ = sb.AppendLine("    /// <summary>Indicates the form has been modified since creation. Used by later stories to warn on navigation.</summary>");
        _ = sb.AppendLine("    public bool IsDirty { get; private set; }");
        _ = sb.AppendLine();

        EmitFieldBackingFields(sb, form);

        _ = sb.AppendLine("    /// <inheritdoc />");
        _ = sb.AppendLine("    protected override void OnInitialized()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        _model = InitialValue ?? new();");
        _ = sb.AppendLine("        _editContext = new EditContext(_model);");
        _ = sb.AppendLine("        _serverValidationMessages = new ValidationMessageStore(_editContext);");
        _ = sb.AppendLine("        _editContext.OnFieldChanged += OnEditContextFieldChanged;");
        _ = sb.AppendLine("        LifecycleState.StateChanged += OnStateChanged;");
        _ = sb.AppendLine("        // Story 2-5 Task 5.3 — surface the EditContext to the renderer so it can wire D24 validation + abandonment guard.");
        _ = sb.AppendLine("        if (OnEditContextReady.HasDelegate) { _ = OnEditContextReady.InvokeAsync(_editContext); }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        if (hasAuthorizationPolicy) {
            _ = sb.AppendLine("    /// <inheritdoc />");
            _ = sb.AppendLine("    protected override async Task OnInitializedAsync()");
            _ = sb.AppendLine("    {");
            _ = sb.AppendLine("        // Initialize the cancellation source synchronously so the auth probe and disposal can race cleanly.");
            _ = sb.AppendLine("        _cts ??= new CancellationTokenSource();");
            _ = sb.AppendLine("        AuthenticationStateProvider.AuthenticationStateChanged += OnAuthenticationStateChanged;");
            _ = sb.AppendLine("        await RefreshPresentationAuthorizationAsync().ConfigureAwait(false);");
            _ = sb.AppendLine("    }");
            _ = sb.AppendLine();
            _ = sb.AppendLine("    private void OnAuthenticationStateChanged(Task<AuthenticationState> _)");
            _ = sb.AppendLine("    {");
            _ = sb.AppendLine("        if (_disposed) return;");
            _ = sb.AppendLine("        // Pass 3 — wrap the InvokeAsync call itself (not just the lambda body) so a synchronous");
            _ = sb.AppendLine("        // ObjectDisposedException from a torn-down RendererSynchronizationContext does not become");
            _ = sb.AppendLine("        // an UnobservedTaskException at process level.");
            _ = sb.AppendLine("        try");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            _ = InvokeAsync(async () =>");
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine("                try { await RefreshPresentationAuthorizationAsync().ConfigureAwait(false); }");
            _ = sb.AppendLine("                catch (Exception ex) when (ex is not OperationCanceledException) { Logger?.LogWarning(ex, \"Refresh after auth-state-changed failed.\"); }");
            _ = sb.AppendLine("            });");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        catch (ObjectDisposedException) { /* Renderer torn down between dispose and event firing; safe to ignore. */ }");
            _ = sb.AppendLine("    }");
            _ = sb.AppendLine();
            _ = sb.AppendLine("    private async Task RefreshPresentationAuthorizationAsync()");
            _ = sb.AppendLine("    {");
            _ = sb.AppendLine("        // Pass 3 — synchronously force Ready=false BEFORE the await so the button");
            _ = sb.AppendLine("        // is disabled during the in-flight check (covers the auth-state-changed-during-refresh window).");
            _ = sb.AppendLine("        _authorizationPresentationReady = false;");
            _ = sb.AppendLine("        // Pass 3 — sequence guard: stamp before await, compare after; only the latest completion applies.");
            _ = sb.AppendLine("        int sequence = System.Threading.Interlocked.Increment(ref _authorizationRefreshSequence);");
            _ = sb.AppendLine("        // Pass 3 — capture _cts once so concurrent disposal does not race the post-await access.");
            _ = sb.AppendLine("        CancellationTokenSource? cts = _cts;");
            _ = sb.AppendLine("        var token = cts?.Token ?? CancellationToken.None;");
            _ = sb.AppendLine("        var authorization = await CommandAuthorizationEvaluator.EvaluateAsync(");
            _ = sb.AppendLine("            CreateAuthorizationRequest(),");
            _ = sb.AppendLine("            token).ConfigureAwait(false);");
            _ = sb.AppendLine("        if (_disposed) return;");
            _ = sb.AppendLine("        // Pass 3 — sequence guard: if a newer refresh has been started, drop this stale result.");
            _ = sb.AppendLine("        if (sequence != System.Threading.Volatile.Read(ref _authorizationRefreshSequence)) return;");
            _ = sb.AppendLine("        bool isPending = authorization.Kind == global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationDecisionKind.Pending;");
            _ = sb.AppendLine("        _authorizationPresentationReady = !isPending;");
            _ = sb.AppendLine("        _authorizationPresentationAllowed = authorization.IsAllowed;");
            _ = sb.AppendLine("        if (!authorization.IsAllowed && !isPending)");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            SetAuthorizationWarning(authorization.Reason);");
            _ = sb.AppendLine("            Logger?.LogWarning(\"Command authorization blocked. CorrelationId={CorrelationId} Reason={Reason}\", authorization.CorrelationId, authorization.Reason);");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        else if (isPending)");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            // Pass 3 — surface a localized 'Checking permission...' hint so users see why the button is disabled.");
            _ = sb.AppendLine("            SetAuthorizationCheckingHint();");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        else");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            _serverWarning = null;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        await InvokeAsync(StateHasChanged).ConfigureAwait(false);");
            _ = sb.AppendLine("    }");
            _ = sb.AppendLine();
            _ = sb.AppendLine("    private global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationRequest CreateAuthorizationRequest()");
            _ = sb.AppendLine("        => new(");
            _ = sb.AppendLine("            typeof(" + commandFqn + "),");
            _ = sb.AppendLine("            AuthorizationPolicyName,");
            _ = sb.AppendLine("            _model,");
            _ = sb.AppendLine("            BoundedContextName,");
            _ = sb.AppendLine("            \"" + EscapeString(form.ButtonLabel) + "\",");
            _ = sb.AppendLine("            global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationSurface.GeneratedForm);");
            _ = sb.AppendLine();
            _ = sb.AppendLine("    private string ResolveAuthorizationLocalized(string key, string fallback, params object[] args)");
            _ = sb.AppendLine("    {");
            _ = sb.AppendLine("        var localized = args is { Length: > 0 } ? CommandAuthorizationLocalizer[key, args] : CommandAuthorizationLocalizer[key];");
            _ = sb.AppendLine("        return localized.ResourceNotFound ? fallback : localized.Value;");
            _ = sb.AppendLine("    }");
            _ = sb.AppendLine();
            _ = sb.AppendLine("    private void SetAuthorizationWarning(global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationReason reason)");
            _ = sb.AppendLine("    {");
            _ = sb.AppendLine("        // DN7 — distinguish infrastructure failures from user-denied so users see a retry hint instead of a permission error.");
            _ = sb.AppendLine("        // Pass 3 DN-7-3-3-1 — Unauthenticated routes to a distinct sign-in copy variant.");
            _ = sb.AppendLine("        bool infrastructureFailure = reason is");
            _ = sb.AppendLine("            global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationReason.MissingService");
            _ = sb.AppendLine("            or global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationReason.MissingPolicy");
            _ = sb.AppendLine("            or global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationReason.StaleTenantContext");
            _ = sb.AppendLine("            or global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationReason.HandlerFailed");
            _ = sb.AppendLine("            or global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationReason.Canceled");
            _ = sb.AppendLine("            or global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationReason.CatalogInconsistent;");
            _ = sb.AppendLine("        bool unauthenticated = reason == global::Hexalith.FrontComposer.Shell.Services.Authorization.CommandAuthorizationReason.Unauthenticated;");
            _ = sb.AppendLine("        string titleKey;");
            _ = sb.AppendLine("        string bodyKey;");
            _ = sb.AppendLine("        string fallbackTitle;");
            _ = sb.AppendLine("        string fallbackBody;");
            _ = sb.AppendLine("        if (unauthenticated)");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            titleKey = \"UnauthenticatedCommandWarningTitle\";");
            _ = sb.AppendLine("            bodyKey = \"UnauthenticatedCommandWarningMessage\";");
            _ = sb.AppendLine("            fallbackTitle = \"Sign-in required\";");
            _ = sb.AppendLine("            fallbackBody = \"Please sign in to {0}.\";");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        else if (infrastructureFailure)");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            titleKey = \"AuthorizationActionUnavailableTitle\";");
            _ = sb.AppendLine("            bodyKey = \"AuthorizationActionUnavailableMessage\";");
            _ = sb.AppendLine("            fallbackTitle = \"Action temporarily unavailable\";");
            _ = sb.AppendLine("            fallbackBody = \"Please retry. If the problem persists, contact support.\";");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        else");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            titleKey = \"UnauthorizedCommandWarningTitle\";");
            _ = sb.AppendLine("            bodyKey = \"UnauthorizedCommandWarningMessage\";");
            _ = sb.AppendLine("            fallbackTitle = \"You don't have permission to perform this action\";");
            _ = sb.AppendLine("            fallbackBody = \"You do not have permission to {0}.\";");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        string warningTitle = ResolveAuthorizationLocalized(titleKey, fallbackTitle);");
            _ = sb.AppendLine("        // Infrastructure-failure body intentionally has no {0} placeholder; pass no args so a custom localizer cannot throw FormatException.");
            _ = sb.AppendLine("        string warningBody = infrastructureFailure");
            _ = sb.AppendLine("            ? ResolveAuthorizationLocalized(bodyKey, fallbackBody)");
            _ = sb.AppendLine("            : ResolveAuthorizationLocalized(bodyKey, fallbackBody, \"" + EscapeString(form.ButtonLabel) + "\");");
            _ = sb.AppendLine("        _serverWarning = new global::Hexalith.FrontComposer.Shell.Services.Feedback.CommandFeedbackWarning(");
            _ = sb.AppendLine("            global::Hexalith.FrontComposer.Contracts.Communication.CommandWarningKind.Forbidden,");
            _ = sb.AppendLine("            warningTitle,");
            _ = sb.AppendLine("            warningBody,");
            _ = sb.AppendLine("            null,");
            _ = sb.AppendLine("            null);");
            _ = sb.AppendLine("    }");
            _ = sb.AppendLine();
            _ = sb.AppendLine("    private void SetAuthorizationCheckingHint()");
            _ = sb.AppendLine("    {");
            _ = sb.AppendLine("        // Pass 3 DN-7-3-3-5 — surface a localized 'Checking permission...' hint while the evaluator is mid-flight or returns Pending.");
            _ = sb.AppendLine("        string hintTitle = ResolveAuthorizationLocalized(\"AuthorizationCheckingPermissionTitle\", \"Checking permission...\");");
            _ = sb.AppendLine("        string hintBody = ResolveAuthorizationLocalized(\"AuthorizationCheckingPermissionMessage\", \"Verifying you can {0}. This usually takes a moment.\", \"" + EscapeString(form.ButtonLabel) + "\");");
            _ = sb.AppendLine("        _serverWarning = new global::Hexalith.FrontComposer.Shell.Services.Feedback.CommandFeedbackWarning(");
            _ = sb.AppendLine("            global::Hexalith.FrontComposer.Contracts.Communication.CommandWarningKind.Pending,");
            _ = sb.AppendLine("            hintTitle,");
            _ = sb.AppendLine("            hintBody,");
            _ = sb.AppendLine("            null,");
            _ = sb.AppendLine("            null);");
            _ = sb.AppendLine("    }");
            _ = sb.AppendLine();
        }
        _ = sb.AppendLine("    private void OnEditContextFieldChanged(object? sender, FieldChangedEventArgs e) {");
        _ = sb.AppendLine("        IsDirty = true;");
        _ = sb.AppendLine("        // Story 5-2 D5 — clear stale server-side validation for the edited field.");
        _ = sb.AppendLine("        _serverValidationMessages?.Clear(e.FieldIdentifier);");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private CommandLifecycleState _previousLifecycleState = CommandLifecycleState.Idle;");
        _ = sb.AppendLine("    private void OnStateChanged(object? sender, EventArgs e) {");
        _ = sb.AppendLine("        // Story 2-2 ADR-016: surface Confirmed transition to the renderer via OnConfirmed callback.");
        _ = sb.AppendLine("        // Guard by correlation id so sibling forms of the same command type do not react to");
        _ = sb.AppendLine("        // another instance's successful submit.");
        _ = sb.AppendLine("        var current = LifecycleState.Value.State;");
        _ = sb.AppendLine("        var currentCorrelationId = LifecycleState.Value.CorrelationId;");
        _ = sb.AppendLine("        if (current == CommandLifecycleState.Confirmed");
        _ = sb.AppendLine("            && _previousLifecycleState != CommandLifecycleState.Confirmed");
        _ = sb.AppendLine("            && OnConfirmed.HasDelegate");
        _ = sb.AppendLine("            && !string.IsNullOrEmpty(_submittedCorrelationId)");
        _ = sb.AppendLine("            && string.Equals(currentCorrelationId, _submittedCorrelationId, StringComparison.Ordinal)) {");
        _ = sb.AppendLine("            _ = OnConfirmed.InvokeAsync(null);");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        _previousLifecycleState = current;");
        _ = sb.AppendLine("        InvokeAsync(StateHasChanged);");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <inheritdoc />");
        _ = sb.AppendLine("    protected override void OnAfterRender(bool firstRender) {");
        _ = sb.AppendLine("        if (firstRender && !_externalSubmitRegistered && RegisterExternalSubmit is not null) {");
        _ = sb.AppendLine("            _externalSubmitRegistered = true;");
        _ = sb.AppendLine("            // Story 2-2 ADR-016 rule 6 + Decision D36 — supply the renderer with a synthetic-submit invoker.");
        _ = sb.AppendLine("            RegisterExternalSubmit(() => _ = OnValidSubmitAsync());");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <summary>");
        _ = sb.AppendLine("    /// Resolves a field label following the AC3 precedence: an explicit");
        _ = sb.AppendLine("    /// <c>[Display(Name)]</c> wins, otherwise the runtime <see cref=\"IStringLocalizer\"/>");
        _ = sb.AppendLine("    /// is consulted, and finally the humanized compile-time label is used as a fallback.");
        _ = sb.AppendLine("    /// Patch 2026-04-16 P-09 (precedence) + P-04 (narrow catch).");
        _ = sb.AppendLine("    /// </summary>");
        _ = sb.AppendLine("    private string ResolveLabel(string propertyName, string staticLabel, bool hasExplicitDisplay)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (hasExplicitDisplay)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return staticLabel;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        try");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            var localized = Localizer[propertyName];");
        _ = sb.AppendLine("            if (!localized.ResourceNotFound && !string.IsNullOrEmpty(localized.Value))");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                return localized.Value;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        catch (Exception ex) when (ex is not OperationCanceledException)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            // Localizer misconfiguration (missing resource manager, culture load failure) is non-fatal.");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        return staticLabel;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private static bool IsDerivableField(string propertyName) => propertyName switch");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        \"MessageId\" or \"CommandId\" or \"CorrelationId\" or \"TenantId\" or \"UserId\" or \"Timestamp\" or \"CreatedAt\" or \"ModifiedAt\" => true,");
        _ = sb.AppendLine("        _ => false,");
        _ = sb.AppendLine("    };");
        _ = sb.AppendLine();

        EmitClientParseErrorHelper(sb, form);
        EmitSubmitMethod(sb, form, fluxor);
        EmitDispose(sb, hasAuthorizationPolicy);
        EmitBuildRenderTree(sb, form, fluxor, escapedButtonLabel);
        EmitRejectionCopyHelpers(sb, escapedButtonLabel);
        EmitNumericConverters(sb, form);

        _ = sb.AppendLine("}");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#pragma warning restore ASP0006");

        return sb.ToString();
    }

    private static void EmitFieldBackingFields(StringBuilder sb, CommandFormModel form) {
        foreach (FormFieldModel field in form.Fields) {
            if (field.TypeCategory == FormFieldTypeCategory.NumberInput
                || field.TypeCategory == FormFieldTypeCategory.DecimalInput) {
                _ = sb.AppendLine("    private string? _" + field.PropertyName + "String;");
                _ = sb.AppendLine("    private string? _" + field.PropertyName + "ParseError;");
            }
        }

        if (form.Fields.Count > 0) {
            _ = sb.AppendLine();
        }
    }

    private static void EmitClientParseErrorHelper(StringBuilder sb, CommandFormModel form) {
        _ = sb.AppendLine("    private bool HasClientParseErrors()");
        _ = sb.AppendLine("    {");

        string[] parseErrorFields = [.. form.Fields
            .Where(field => field.TypeCategory is FormFieldTypeCategory.NumberInput or FormFieldTypeCategory.DecimalInput)
            .Select(field => field.PropertyName)];

        if (parseErrorFields.Length == 0) {
            _ = sb.AppendLine("        return false;");
        }
        else {
            _ = sb.Append("        return ");
            for (int i = 0; i < parseErrorFields.Length; i++) {
                if (i > 0) {
                    _ = sb.AppendLine();
                    _ = sb.Append("            || ");
                }

                _ = sb.Append("!string.IsNullOrEmpty(_")
                    .Append(parseErrorFields[i])
                    .Append("ParseError)");
            }

            _ = sb.AppendLine(";");
        }

        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
    }

    private static void EmitSubmitMethod(StringBuilder sb, CommandFormModel form, CommandFluxorModel fluxor) {
        string commandFqn = form.CommandFullyQualifiedName;
        bool hasAuthorizationPolicy = !string.IsNullOrWhiteSpace(form.AuthorizationPolicyName);

        _ = sb.AppendLine("    private async Task OnValidSubmitAsync()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        // Story 2-2 code-review P35 — guard against invocation via RegisterExternalSubmit after form disposal.");
        _ = sb.AppendLine("        if (_disposed) return;");
        _ = sb.AppendLine("        // State-guard against rapid double-click: only allow submit from terminal or idle state.");
        _ = sb.AppendLine("        // (See code-review 2026-04-15, patch P19.)");
        _ = sb.AppendLine("        var currentState = LifecycleState.Value.State;");
        _ = sb.AppendLine("        if (currentState != CommandLifecycleState.Idle");
        _ = sb.AppendLine("            && currentState != CommandLifecycleState.Rejected");
        _ = sb.AppendLine("            && currentState != CommandLifecycleState.Confirmed)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        if (HasClientParseErrors())");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            _editContext?.NotifyValidationStateChanged();");
        _ = sb.AppendLine("            return;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        // Story 2-2 code-review P36 — allocate new CTS BEFORE awaiting BeforeSubmit so disposal can cancel it.");
        _ = sb.AppendLine("        CancellationTokenSource? previous = _cts;");
        _ = sb.AppendLine("        _cts = new CancellationTokenSource();");
        _ = sb.AppendLine("        if (previous is not null)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            try { previous.Cancel(); } catch (ObjectDisposedException) { }");
        _ = sb.AppendLine("            previous.Dispose();");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        if (hasAuthorizationPolicy) {
            // Pass 3 P-B70 — auth check FIRST, before clearing validation state, so denied submits keep prior validation messages visible.
            // Pass 3 DN-7-3-3-1 also clears _serverWarning here so the prior warning (if any) does not leak into the success path.
            _ = sb.AppendLine("        // Pass 3 — clear auth-warning slot only; validation state stays put until we know auth passes.");
            _ = sb.AppendLine("        _serverWarning = null;");
            _ = sb.AppendLine("        var authorization = await CommandAuthorizationEvaluator.EvaluateAsync(");
            _ = sb.AppendLine("            CreateAuthorizationRequest(),");
            _ = sb.AppendLine("            _cts.Token).ConfigureAwait(false);");
            _ = sb.AppendLine("        if (_disposed || _cts.IsCancellationRequested) return;");
            _ = sb.AppendLine("        if (!authorization.IsAllowed)");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            SetAuthorizationWarning(authorization.Reason);");
            _ = sb.AppendLine("            if (_serverWarning is not null)");
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine("                CommandFeedbackPublisher.PublishWarning(_serverWarning);");
            _ = sb.AppendLine("            }");
            _ = sb.AppendLine("            await InvokeAsync(StateHasChanged).ConfigureAwait(false);");
            _ = sb.AppendLine("            Logger?.LogWarning(\"Command authorization blocked. CorrelationId={CorrelationId} Reason={Reason}\", authorization.CorrelationId, authorization.Reason);");
            _ = sb.AppendLine("            return;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine();
        }
        _ = sb.AppendLine("        // Story 5-2 D5 — clear server-driven validation state from the prior submit (auth has already passed if a policy is in scope).");
        _ = sb.AppendLine("        _serverValidationMessages?.Clear();");
        _ = sb.AppendLine("        if (_serverFormLevelErrors.Count > 0)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            _serverFormLevelErrors = System.Array.Empty<string>();");
        _ = sb.AppendLine("        }");
        if (!hasAuthorizationPolicy) {
            _ = sb.AppendLine("        _serverWarning = null;");
        }

        _ = sb.AppendLine("        _editContext?.NotifyValidationStateChanged();");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        if (BeforeSubmit is not null)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            await BeforeSubmit().ConfigureAwait(false);");
        _ = sb.AppendLine("            if (_disposed || _cts.IsCancellationRequested) return;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        if (hasAuthorizationPolicy) {
            // Pass 3 / Pass-2 P2 — second authorization check AFTER BeforeSubmit (which may include destructive confirmation dialog).
            // Catches sign-out / tenant switch / policy revocation that occurred while the dialog was open or while a derivable-field
            // BeforeSubmit was running. Resource-based policies that read the post-mutation _model see fresh state here.
            _ = sb.AppendLine("        // Pass 3 P2 — re-authorize after BeforeSubmit returns. Sign-out / tenant switch / policy revocation may have happened mid-await.");
            _ = sb.AppendLine("        var authorizationPostBeforeSubmit = await CommandAuthorizationEvaluator.EvaluateAsync(");
            _ = sb.AppendLine("            CreateAuthorizationRequest(),");
            _ = sb.AppendLine("            _cts.Token).ConfigureAwait(false);");
            _ = sb.AppendLine("        if (_disposed || _cts.IsCancellationRequested) return;");
            _ = sb.AppendLine("        if (!authorizationPostBeforeSubmit.IsAllowed)");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            SetAuthorizationWarning(authorizationPostBeforeSubmit.Reason);");
            _ = sb.AppendLine("            if (_serverWarning is not null)");
            _ = sb.AppendLine("            {");
            _ = sb.AppendLine("                CommandFeedbackPublisher.PublishWarning(_serverWarning);");
            _ = sb.AppendLine("            }");
            _ = sb.AppendLine("            await InvokeAsync(StateHasChanged).ConfigureAwait(false);");
            _ = sb.AppendLine("            Logger?.LogWarning(\"Command authorization blocked after BeforeSubmit. CorrelationId={CorrelationId} Reason={Reason}\", authorizationPostBeforeSubmit.CorrelationId, authorizationPostBeforeSubmit.Reason);");
            _ = sb.AppendLine("            return;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine();
        }

        _ = sb.AppendLine("        var correlationId = Guid.NewGuid().ToString();");
        _ = sb.AppendLine("        _submittedCorrelationId = correlationId;");
        _ = sb.AppendLine("        var cts = _cts;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        // Story 2-3 D5 — lazily activate the lifecycle bridge so ILifecycleStateService receives");
        _ = sb.AppendLine("        // the typed Fluxor actions. Idempotent + per-circuit; mirrors Story 2-2 D35.");
        _ = sb.AppendLine("        LifecycleBridgeRegistry.Ensure<" + form.TypeName + "LifecycleBridge>();");
        _ = sb.AppendLine("        // Story 2-2 D35 — lazily activate the generated subscriber before the first SubmittedAction dispatch.");
        _ = sb.AppendLine("        LastUsedSubscriberRegistry.Ensure<" + form.TypeName + "LastUsedSubscriber>();");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        Dispatcher.Dispatch(new " + fluxor.ActionsWrapperName + ".SubmittedAction(correlationId, _model));");
        _ = sb.AppendLine("        await InvokeAsync(StateHasChanged);");
        _ = sb.AppendLine("        Logger?.LogInformation(\"Command submitted. CorrelationId={CorrelationId}\", correlationId);");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        try");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            var result = await CommandService.DispatchAsync(");
        _ = sb.AppendLine("                _model,");
        _ = sb.AppendLine("                onLifecycleChange: (state, _) =>");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    // Guard against callbacks arriving after form disposal or cancellation (patch P10).");
        _ = sb.AppendLine("                    if (_disposed || cts.IsCancellationRequested) return;");
        _ = sb.AppendLine("                    switch (state)");
        _ = sb.AppendLine("                    {");
        _ = sb.AppendLine("                        case CommandLifecycleState.Syncing:");
        _ = sb.AppendLine("                            Dispatcher.Dispatch(new " + fluxor.ActionsWrapperName + ".SyncingAction(correlationId));");
        _ = sb.AppendLine("                            break;");
        _ = sb.AppendLine("                        case CommandLifecycleState.Confirmed:");
        _ = sb.AppendLine("                            Dispatcher.Dispatch(new " + fluxor.ActionsWrapperName + ".ConfirmedAction(correlationId));");
        _ = sb.AppendLine("                            break;");
        _ = sb.AppendLine("                    }");
        _ = sb.AppendLine("                },");
        _ = sb.AppendLine("                cancellationToken: cts.Token);");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            // Story 5-5 P6 — generator-known framework metadata is limited to CorrelationId,");
        _ = sb.AppendLine("            // MessageId, and CommandTypeName at form-emit time. ProjectionTypeName / LaneKey /");
        _ = sb.AppendLine("            // EntityKey / ExpectedStatusSlot / PriorStatusSlot would require runtime context");
        _ = sb.AppendLine("            // that the source generator does not have; adopters that need framework-controlled");
        _ = sb.AppendLine("            // entity-key fallback matching must populate them via a custom dispatch hook. The");
        _ = sb.AppendLine("            // MessageId path remains the primary resolution route because EventStore echoes the");
        _ = sb.AppendLine("            // ULID in projection rows.");
        _ = sb.AppendLine("            global::Hexalith.FrontComposer.Shell.State.PendingCommands.PendingCommandRegistrationResult? pendingRegistration = null;");
        _ = sb.AppendLine("            if (string.Equals(result.Status, \"Accepted\", StringComparison.OrdinalIgnoreCase))");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                pendingRegistration = PendingCommandState.Register(new global::Hexalith.FrontComposer.Shell.State.PendingCommands.PendingCommandRegistration(");
        _ = sb.AppendLine("                    CorrelationId: correlationId,");
        _ = sb.AppendLine("                    MessageId: result.MessageId,");
        _ = sb.AppendLine("                    CommandTypeName: typeof(" + commandFqn + ").FullName ?? nameof(" + commandFqn + ")));");
        _ = sb.AppendLine("                if (pendingRegistration.Status is global::Hexalith.FrontComposer.Shell.State.PendingCommands.PendingCommandRegistrationStatus.InvalidMessageId");
        _ = sb.AppendLine("                    or global::Hexalith.FrontComposer.Shell.State.PendingCommands.PendingCommandRegistrationStatus.ConflictingMetadata)");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    Logger?.LogWarning(\"Pending command registration skipped. CorrelationId={CorrelationId} Status={Status}\", correlationId, pendingRegistration.Status);");
        _ = sb.AppendLine("                }");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            // Story 5-5 P17 / P18 / P2-P2 / P2-P3 — skip duplicate AcknowledgedAction dispatch only when:");
        _ = sb.AppendLine("            //   - InvalidMessageId: pending registry rejected the MessageId as malformed; lifecycle has nothing to acknowledge.");
        _ = sb.AppendLine("            //   - ConflictingMetadata: the registration was rejected because metadata conflicts with an existing entry; the new correlationId is unknown to the pending state.");
        _ = sb.AppendLine("            //   - MergedTerminal with the SAME correlationId: re-mount of the original form on a terminal entry; would re-acknowledge a known-terminal lifecycle.");
        _ = sb.AppendLine("            // MergedTerminal with a DIFFERENT correlationId means a second form submission for the same MessageId; the new correlationId must advance through Acknowledged so its Fluxor state does not stay in Submitting.");
        _ = sb.AppendLine("            bool skipAcknowledged = pendingRegistration is { Status:");
        _ = sb.AppendLine("                global::Hexalith.FrontComposer.Shell.State.PendingCommands.PendingCommandRegistrationStatus.InvalidMessageId");
        _ = sb.AppendLine("                or global::Hexalith.FrontComposer.Shell.State.PendingCommands.PendingCommandRegistrationStatus.ConflictingMetadata };");
        _ = sb.AppendLine("            if (!skipAcknowledged && pendingRegistration is { Status: global::Hexalith.FrontComposer.Shell.State.PendingCommands.PendingCommandRegistrationStatus.MergedTerminal, Entry: { } mergedEntry } && string.Equals(mergedEntry.CorrelationId, correlationId, System.StringComparison.Ordinal))");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                skipAcknowledged = true;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("            if (!skipAcknowledged)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                Dispatcher.Dispatch(new " + fluxor.ActionsWrapperName + ".AcknowledgedAction(correlationId, result.MessageId));");
        _ = sb.AppendLine("                Logger?.LogInformation(\"Command acknowledged. CorrelationId={CorrelationId} MessageId={MessageId}\", correlationId, result.MessageId);");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("            else");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                Logger?.LogInformation(\"Command acknowledged dispatch skipped (pending status: {Status}). CorrelationId={CorrelationId}\", pendingRegistration?.Status, correlationId);");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        catch (CommandValidationException ex)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            // Story 5-2 D5 — server-side 400 validation. Map allowlisted fields onto the");
        _ = sb.AppendLine("            // ValidationMessageStore; surface unknown / global errors form-level. Lifecycle returns to Idle so the user can correct and re-submit (patch P11 mirrors the cancellation path).");
        _ = sb.AppendLine("            if (_editContext is not null && _serverValidationMessages is not null)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                _serverFormLevelErrors = global::Hexalith.FrontComposer.Shell.Services.Validation.ServerValidationApplicator.Apply(_serverValidationMessages, ex, _serverValidationAllowlist, _model!);");
        _ = sb.AppendLine("                _editContext.NotifyValidationStateChanged();");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("            Dispatcher.Dispatch(new " + fluxor.ActionsWrapperName + ".ResetToIdleAction(correlationId));");
        _ = sb.AppendLine("            Logger?.LogInformation(\"Command validation failed. CorrelationId={CorrelationId} Title={Title}\", correlationId, ex.Problem.Title);");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        catch (CommandWarningException ex)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            // Story 5-2 D6 — 403/404/429 surface through a separate warning channel. Lifecycle is");
        _ = sb.AppendLine("            // reset to Idle so the user can react (e.g. wait out a Retry-After) and try again.");
        _ = sb.AppendLine("            _serverWarning = new global::Hexalith.FrontComposer.Shell.Services.Feedback.CommandFeedbackWarning(");
        _ = sb.AppendLine("                ex.Kind,");
        _ = sb.AppendLine("                ex.Problem.Title,");
        _ = sb.AppendLine("                ex.Problem.Detail,");
        _ = sb.AppendLine("                ex.Problem.EntityLabel,");
        _ = sb.AppendLine("                ex.RetryAfter);");
        _ = sb.AppendLine("            CommandFeedbackPublisher.PublishWarning(_serverWarning);");
        _ = sb.AppendLine("            Dispatcher.Dispatch(new " + fluxor.ActionsWrapperName + ".ResetToIdleAction(correlationId));");
        _ = sb.AppendLine("            await InvokeAsync(StateHasChanged);");
        _ = sb.AppendLine("            Logger?.LogWarning(\"Command warning ({WarningKind}). CorrelationId={CorrelationId} Title={Title}\", ex.Kind, correlationId, ex.Problem.Title);");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        catch (AuthRedirectRequiredException ex)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            // Story 5-2 D8 — 401: invoke the framework auth redirector. No cache mutation, no");
        _ = sb.AppendLine("            // lifecycle rejection, no validation pollution. Lifecycle is reset to Idle so");
        _ = sb.AppendLine("            // the form does not stay locked while the host handles the redirect.");
        _ = sb.AppendLine("            Dispatcher.Dispatch(new " + fluxor.ActionsWrapperName + ".ResetToIdleAction(correlationId));");
        _ = sb.AppendLine("            Logger?.LogInformation(\"Command requires authentication redirect. CorrelationId={CorrelationId} Reason={Reason}\", correlationId, ex.Message);");
        _ = sb.AppendLine("            await AuthRedirector.RedirectAsync(returnUrl: null, cancellationToken: cts.Token).ConfigureAwait(false);");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        catch (CommandRejectedException ex)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            Dispatcher.Dispatch(new " + fluxor.ActionsWrapperName + ".RejectedAction(correlationId, ex.Message, ex.Resolution));");
        _ = sb.AppendLine("            // Notify validation pipeline so any stale error state redraws (patch P16).");
        _ = sb.AppendLine("            _editContext?.NotifyValidationStateChanged();");
        _ = sb.AppendLine("            Logger?.LogWarning(\"Command rejected. CorrelationId={CorrelationId} Reason={Reason}\", correlationId, ex.Message);");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        catch (OperationCanceledException)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            // Form disposed during submission; the Dispose path already handles state cleanup.");
        _ = sb.AppendLine("            if (!_disposed)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                // Submit was cancelled without disposal -- reset lifecycle so the user can retry (patch P11).");
        _ = sb.AppendLine("                // Patch 2026-04-16 P-11: carry the submit correlation so sibling forms ignore this reset.");
        _ = sb.AppendLine("                Dispatcher.Dispatch(new " + fluxor.ActionsWrapperName + ".ResetToIdleAction(correlationId));");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
    }

    private static void EmitDispose(StringBuilder sb, bool hasAuthorizationPolicy) {
        _ = sb.AppendLine("    /// <inheritdoc />");
        _ = sb.AppendLine("    public void Dispose()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        // Idempotent dispose (patch P18). Blazor can invoke Dispose more than once on teardown.");
        _ = sb.AppendLine("        if (_disposed) return;");
        _ = sb.AppendLine("        _disposed = true;");
        _ = sb.AppendLine("        try { _cts?.Cancel(); } catch (ObjectDisposedException) { }");
        _ = sb.AppendLine("        _cts?.Dispose();");
        _ = sb.AppendLine("        _cts = null;");
        _ = sb.AppendLine("        if (_editContext is not null)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            _editContext.OnFieldChanged -= OnEditContextFieldChanged;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        LifecycleState.StateChanged -= OnStateChanged;");
        if (hasAuthorizationPolicy) {
            _ = sb.AppendLine("        if (AuthenticationStateProvider is not null)");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            AuthenticationStateProvider.AuthenticationStateChanged -= OnAuthenticationStateChanged;");
            _ = sb.AppendLine("        }");
        }
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
    }

    private static void EmitBuildRenderTree(StringBuilder sb, CommandFormModel form, CommandFluxorModel fluxor, string escapedButtonLabel) {
        bool hasAuthorizationPolicy = !string.IsNullOrWhiteSpace(form.AuthorizationPolicyName);

        _ = sb.AppendLine("    /// <inheritdoc />");
        _ = sb.AppendLine("    protected override void BuildRenderTree(RenderTreeBuilder builder)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        int seq = 0;");
        _ = sb.AppendLine("        builder.OpenElement(seq++, \"div\");");
        _ = sb.AppendLine("        // AC3 density: Comfortable by default (patch P13).");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"class\", \"fc-command-form fc-density-comfortable\");");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"aria-label\", \"" + escapedButtonLabel + " command form\");");
        _ = sb.AppendLine();
        // Story 2-4 ADR-020 / Task 4.1b — wrap the EditForm in FcLifecycleWrapper so lifecycle
        // feedback (spinner, pulse, still-syncing, action prompt, confirmed/rejected message bar)
        // renders around every generated form without service-locator plumbing.
        _ = sb.AppendLine("        builder.OpenComponent<FcLifecycleWrapper>(seq++);");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"CorrelationId\", _submittedCorrelationId);");
        // Story 2-5 Task 5.2 + D4 — emitted attributes forward rejection copy + domain-language title
        // computed from the Fluxor feature state's RejectionReason/RejectionResolution fields.
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"RejectionMessage\", BuildFcLifecycleRejectionCopy());");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"RejectionTitle\", BuildFcLifecycleRejectionTitle());");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"ChildContent\", (RenderFragment)(__wrap =>");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            int wseq = 0;");
        _ = sb.AppendLine("            __wrap.OpenComponent<EditForm>(wseq++);");
        _ = sb.AppendLine("            __wrap.AddAttribute(wseq++, \"EditContext\", _editContext);");
        _ = sb.AppendLine("            __wrap.AddAttribute(wseq++, \"OnValidSubmit\", EventCallback.Factory.Create<EditContext>(this, _ => OnValidSubmitAsync()));");
        _ = sb.AppendLine("        RenderFragment<EditContext> formBody = _ => (RenderFragment)(__b =>");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            int cseq = 0;");
        _ = sb.AppendLine("            __b.OpenComponent<DataAnnotationsValidator>(cseq++);");
        _ = sb.AppendLine("            __b.CloseComponent();");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            __b.OpenComponent<FluentValidationSummary>(cseq++);");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Model\", (object)_model);");
        _ = sb.AppendLine("            __b.CloseComponent();");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            if (_serverFormLevelErrors.Count > 0)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                __b.OpenComponent<FluentMessageBar>(cseq++);");
        _ = sb.AppendLine("                __b.AddAttribute(cseq++, \"Intent\", MessageBarIntent.Error);");
        _ = sb.AppendLine("                __b.AddAttribute(cseq++, \"Title\", \"Validation failed\");");
        _ = sb.AppendLine("                __b.AddAttribute(cseq++, \"AllowDismiss\", true);");
        _ = sb.AppendLine("                __b.AddAttribute(cseq++, \"ChildContent\", (RenderFragment)(__msg =>");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    int mseq = 0;");
        _ = sb.AppendLine("                    foreach (string error in _serverFormLevelErrors)");
        _ = sb.AppendLine("                    {");
        _ = sb.AppendLine("                        __msg.OpenElement(mseq++, \"div\");");
        _ = sb.AppendLine("                        __msg.AddContent(mseq++, error);");
        _ = sb.AppendLine("                        __msg.CloseElement();");
        _ = sb.AppendLine("                    }");
        _ = sb.AppendLine("                }));");
        _ = sb.AppendLine("                __b.CloseComponent();");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            if (_serverWarning is not null)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                __b.OpenComponent<FluentMessageBar>(cseq++);");
        _ = sb.AppendLine("                __b.AddAttribute(cseq++, \"Intent\", MessageBarIntent.Warning);");
        _ = sb.AppendLine("                __b.AddAttribute(cseq++, \"Title\", _serverWarning.Title ?? _serverWarning.Kind.ToString());");
        _ = sb.AppendLine("                __b.AddAttribute(cseq++, \"AllowDismiss\", true);");
        _ = sb.AppendLine("                __b.AddAttribute(cseq++, \"ChildContent\", (RenderFragment)(__msg =>");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    int mseq = 0;");
        _ = sb.AppendLine("                    string body = _serverWarning.Detail ?? _serverWarning.EntityLabel ?? \"Please review the warning and try again.\";");
        _ = sb.AppendLine("                    __msg.AddContent(mseq++, body);");
        _ = sb.AppendLine("                    if (_serverWarning.RetryAfter is not null)");
        _ = sb.AppendLine("                    {");
        _ = sb.AppendLine("                        __msg.OpenElement(mseq++, \"div\");");
        _ = sb.AppendLine("                        __msg.AddContent(mseq++, $\"Retry after {_serverWarning.RetryAfter.Value.TotalSeconds:0} seconds.\");");
        _ = sb.AppendLine("                        __msg.CloseElement();");
        _ = sb.AppendLine("                    }");
        _ = sb.AppendLine("                }));");
        _ = sb.AppendLine("                __b.CloseComponent();");
        _ = sb.AppendLine("            }");

        foreach (FormFieldModel field in form.Fields) {
            EmitField(sb, field);
        }

        // Submit button
        _ = sb.AppendLine();
        _ = sb.AppendLine("            __b.OpenComponent<FluentButton>(cseq++);");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Type\", ButtonType.Submit);");
        _ = sb.AppendLine("            // Enable submit in Idle, Confirmed, or Rejected (terminals allow retry) -- patch P3.");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Disabled\",");
        if (hasAuthorizationPolicy) {
            // Wrap the lifecycle group in explicit parens so a future reorder of the && chain cannot
            // silently flip the gate semantics (Pass-2 P17 / B1 / E1 / A26).
            _ = sb.AppendLine("                (LifecycleState.Value.State != CommandLifecycleState.Idle");
            _ = sb.AppendLine("                && LifecycleState.Value.State != CommandLifecycleState.Confirmed");
            _ = sb.AppendLine("                && LifecycleState.Value.State != CommandLifecycleState.Rejected)");
            _ = sb.AppendLine("                || !_authorizationPresentationReady");
            _ = sb.AppendLine("                || !_authorizationPresentationAllowed);");
        }
        else {
            _ = sb.AppendLine("                LifecycleState.Value.State != CommandLifecycleState.Idle");
            _ = sb.AppendLine("                && LifecycleState.Value.State != CommandLifecycleState.Confirmed");
            _ = sb.AppendLine("                && LifecycleState.Value.State != CommandLifecycleState.Rejected);");
        }
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"ChildContent\", (RenderFragment)(__btn =>");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                int bseq = 0;");
        _ = sb.AppendLine("                if (LifecycleState.Value.State == CommandLifecycleState.Submitting)");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    __btn.OpenComponent<FluentSpinner>(bseq++);");
        _ = sb.AppendLine("                    __btn.AddAttribute(bseq++, \"Style\", \"width: 20px; height: 20px; margin-right: 8px;\");");
        _ = sb.AppendLine("                    __btn.CloseComponent();");
        _ = sb.AppendLine("                }");
        _ = sb.AppendLine("                __btn.AddContent(bseq++, \"" + escapedButtonLabel + "\");");
        _ = sb.AppendLine("            }));");
        _ = sb.AppendLine("            __b.CloseComponent();");
        _ = sb.AppendLine("        });");
        _ = sb.AppendLine("            __wrap.AddAttribute(wseq++, \"ChildContent\", formBody);");
        _ = sb.AppendLine("            __wrap.CloseComponent();");
        _ = sb.AppendLine("        }));");
        _ = sb.AppendLine("        builder.CloseComponent();");
        _ = sb.AppendLine("        builder.CloseElement();");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
    }

    private static void EmitField(StringBuilder sb, FormFieldModel field) {
        string propertyName = field.PropertyName;
        string staticLabel = EscapeString(field.StaticLabel);
        string isRequired = field.IsRequired ? "true" : "false";
        string hasExplicitDisplay = field.HasExplicitDisplayName ? "true" : "false";

        _ = sb.AppendLine();
        _ = sb.AppendLine("            // Field: " + propertyName);
        // Story 2-2 ADR-016: ShowFieldsOnly gate. When non-null, render only fields in the set.
        _ = sb.AppendLine("            if ((!DerivableFieldsHidden || !IsDerivableField(\"" + propertyName + "\"))");
        _ = sb.AppendLine("                && (ShowFieldsOnly is null || System.Array.IndexOf(ShowFieldsOnly, \"" + propertyName + "\") >= 0))");
        _ = sb.AppendLine("            {");

        switch (field.TypeCategory) {
            case FormFieldTypeCategory.TextInput:
                EmitTextInput(sb, propertyName, staticLabel, isRequired, hasExplicitDisplay, field.IsNullable, inputType: null, placeholder: null, monospace: false);
                break;
            case FormFieldTypeCategory.NumberInput:
                EmitNumericInput(sb, field, decimalMode: false);
                break;
            case FormFieldTypeCategory.DecimalInput:
                EmitNumericInput(sb, field, decimalMode: true);
                break;
            case FormFieldTypeCategory.Switch:
                EmitSwitch(sb, propertyName, staticLabel, hasExplicitDisplay);
                break;
            case FormFieldTypeCategory.DatePicker:
                EmitDatePicker(sb, field);
                break;
            case FormFieldTypeCategory.Select:
                EmitEnumSelect(sb, field);
                break;
            case FormFieldTypeCategory.MonospaceText:
                EmitTextInput(sb, propertyName, staticLabel, isRequired, hasExplicitDisplay, field.IsNullable, inputType: null, placeholder: null, monospace: true);
                break;
            case FormFieldTypeCategory.TimeInput:
                // Task 3B.1: TimeOnly renders as FluentTextInput with TextInputType.Time + HH:mm placeholder (patch 2026-04-16 P-06).
                EmitTextInput(sb, propertyName, staticLabel, isRequired, hasExplicitDisplay, field.IsNullable, inputType: "Time", placeholder: "HH:mm", monospace: false);
                break;
            case FormFieldTypeCategory.Placeholder:
                EmitPlaceholder(sb, field);
                break;
        }

        _ = sb.AppendLine("            }");
    }

    private static void EmitTextInput(
        StringBuilder sb,
        string propertyName,
        string staticLabel,
        string isRequired,
        string hasExplicitDisplay,
        bool isNullable,
        string? inputType,
        string? placeholder,
        bool monospace) {
        // Patch 2026-04-16 P-07: preserve null for nullable string? fields so `[Required]` semantics stay intact.
        string valueAssignment = isNullable
            ? "_model." + propertyName + " = v"
            : "_model." + propertyName + " = v ?? string.Empty";

        _ = sb.AppendLine("            __b.OpenComponent<FluentTextInput>(cseq++);");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Value\", _model." + propertyName + ");");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"ValueChanged\", EventCallback.Factory.Create<string?>(this, v => " + valueAssignment + "));");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Label\", ResolveLabel(\"" + propertyName + "\", \"" + staticLabel + "\", " + hasExplicitDisplay + "));");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Required\", " + isRequired + ");");
        if (inputType is not null) {
            _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"TextInputType\", TextInputType." + inputType + ");");
        }

        if (placeholder is not null) {
            _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Placeholder\", \"" + EscapeString(placeholder) + "\");");
        }

        if (monospace) {
            _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Class\", \"fc-monospace\");");
        }

        _ = sb.AppendLine("            __b.CloseComponent();");
    }

    private static void EmitNumericInput(StringBuilder sb, FormFieldModel field, bool decimalMode) {
        string propertyName = field.PropertyName;
        string staticLabel = EscapeString(field.StaticLabel);
        string isRequired = field.IsRequired ? "true" : "false";
        string hasExplicitDisplay = field.HasExplicitDisplayName ? "true" : "false";

        _ = sb.AppendLine("            __b.OpenComponent<FluentTextInput>(cseq++);");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Value\", _" + propertyName + "String ?? _model." + propertyName + ".ToString(CultureInfo.CurrentCulture));");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"ValueChanged\", EventCallback.Factory.Create<string?>(this, v => On" + propertyName + "Changed(v)));");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Label\", ResolveLabel(\"" + propertyName + "\", \"" + staticLabel + "\", " + hasExplicitDisplay + "));");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Required\", " + isRequired + ");");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"TextInputType\", TextInputType.Number);");
        if (decimalMode) {
            _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"InputMode\", TextInputMode.Decimal);");
        }

        _ = sb.AppendLine("            if (!string.IsNullOrEmpty(_" + propertyName + "ParseError))");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                __b.AddAttribute(cseq++, \"Message\", _" + propertyName + "ParseError);");
        _ = sb.AppendLine("                __b.AddAttribute(cseq++, \"MessageState\", MessageState.Error);");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("            __b.CloseComponent();");
    }

    private static void EmitSwitch(StringBuilder sb, string propertyName, string staticLabel, string hasExplicitDisplay) {
        _ = sb.AppendLine("            __b.OpenComponent<FluentSwitch>(cseq++);");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Value\", _model." + propertyName + ");");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"ValueChanged\", EventCallback.Factory.Create<bool>(this, v => _model." + propertyName + " = v));");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Label\", ResolveLabel(\"" + propertyName + "\", \"" + staticLabel + "\", " + hasExplicitDisplay + "));");
        _ = sb.AppendLine("            __b.CloseComponent();");
    }

    private static void EmitDatePicker(StringBuilder sb, FormFieldModel field) {
        string propertyName = field.PropertyName;
        string staticLabel = EscapeString(field.StaticLabel);
        string hasExplicitDisplay = field.HasExplicitDisplayName ? "true" : "false";
        string valueType = field.TypeName switch {
            "DateTime" => "DateTime",
            "DateTimeOffset" => "DateTimeOffset",
            "DateOnly" => "DateOnly",
            _ => "DateTime",
        };

        string genericArg = field.IsNullable ? valueType + "?" : valueType;

        _ = sb.AppendLine("            __b.OpenComponent<FluentDatePicker<" + genericArg + ">>(cseq++);");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Value\", _model." + propertyName + ");");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"ValueChanged\", EventCallback.Factory.Create<" + genericArg + ">(this, v => _model." + propertyName + " = v));");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Label\", ResolveLabel(\"" + propertyName + "\", \"" + staticLabel + "\", " + hasExplicitDisplay + "));");
        _ = sb.AppendLine("            __b.CloseComponent();");
    }

    private static void EmitEnumSelect(StringBuilder sb, FormFieldModel field) {
        string propertyName = field.PropertyName;
        string staticLabel = EscapeString(field.StaticLabel);
        string hasExplicitDisplay = field.HasExplicitDisplayName ? "true" : "false";
        string enumFqn = field.EnumFullyQualifiedName ?? "object";

        _ = sb.AppendLine("            __b.OpenComponent<FluentSelect<" + enumFqn + ", " + enumFqn + ">>(cseq++);");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Items\", (System.Collections.Generic.IEnumerable<" + enumFqn + ">)System.Enum.GetValues<" + enumFqn + ">());");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Value\", _model." + propertyName + ");");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"ValueChanged\", EventCallback.Factory.Create<" + enumFqn + ">(this, v => _model." + propertyName + " = v));");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Label\", ResolveLabel(\"" + propertyName + "\", \"" + staticLabel + "\", " + hasExplicitDisplay + "));");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"OptionText\", (Func<" + enumFqn + ", string>)(e => HumanizeEnumLabel(e.ToString() ?? string.Empty)));");
        _ = sb.AppendLine("            __b.CloseComponent();");
    }

    private static void EmitPlaceholder(StringBuilder sb, FormFieldModel field) {
        string propertyName = field.PropertyName;
        string typeName = EscapeString(field.TypeName);

        _ = sb.AppendLine("            __b.OpenComponent<global::Hexalith.FrontComposer.Shell.Components.Rendering.FcFieldPlaceholder>(cseq++);");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"FieldName\", \"" + EscapeString(propertyName) + "\");");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"TypeName\", \"" + typeName + "\");");
        _ = sb.AppendLine("            __b.CloseComponent();");
    }

    /// <summary>
    /// Story 2-5 Task 5.2 — emits helper methods that forward the Fluxor feature state's rejection
    /// copy to <c>FcLifecycleWrapper.RejectionMessage</c> / <c>RejectionTitle</c>. Plain-text join
    /// (never <c>MarkupString</c>) preserves the D14 XSS invariant.
    /// </summary>
    private static void EmitRejectionCopyHelpers(StringBuilder sb, string escapedButtonLabel) {
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <summary>Story 2-5 D4 — joins Fluxor-state Reason + Resolution with '. ' separator; null outside Rejected.</summary>");
        _ = sb.AppendLine("    private string? BuildFcLifecycleRejectionCopy()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (LifecycleState.Value.State != CommandLifecycleState.Rejected) return null;");
        _ = sb.AppendLine("        var reason = LifecycleState.Value.RejectionReason;");
        _ = sb.AppendLine("        var resolution = LifecycleState.Value.RejectionResolution;");
        _ = sb.AppendLine("        if (string.IsNullOrWhiteSpace(reason) && string.IsNullOrWhiteSpace(resolution)) return null;");
        _ = sb.AppendLine("        if (string.IsNullOrWhiteSpace(resolution)) return reason;");
        _ = sb.AppendLine("        if (string.IsNullOrWhiteSpace(reason)) return resolution;");
        _ = sb.AppendLine("        return reason + \". \" + resolution;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <summary>Story 2-5 D4 — domain-language rejection title ('{DisplayLabel} failed'); null outside Rejected.</summary>");
        _ = sb.AppendLine("    private string? BuildFcLifecycleRejectionTitle()");
        _ = sb.AppendLine("        => LifecycleState.Value.State == CommandLifecycleState.Rejected");
        _ = sb.AppendLine("           ? \"" + escapedButtonLabel + " failed\"");
        _ = sb.AppendLine("           : null;");
        _ = sb.AppendLine();
    }

    private static void EmitNumericConverters(StringBuilder sb, CommandFormModel form) {
        bool emittedHumanize = false;
        foreach (FormFieldModel field in form.Fields) {
            if (field.TypeCategory != FormFieldTypeCategory.Select) {
                continue;
            }

            if (!emittedHumanize) {
                EmitHumanizeHelper(sb);
                emittedHumanize = true;
            }
        }

        foreach (FormFieldModel field in form.Fields) {
            if (field.TypeCategory != FormFieldTypeCategory.NumberInput
                && field.TypeCategory != FormFieldTypeCategory.DecimalInput) {
                continue;
            }

            bool isInteger = field.TypeCategory == FormFieldTypeCategory.NumberInput;
            string numericType = field.TypeName switch {
                "Int32" => "int",
                "Int64" => "long",
                "Decimal" => "decimal",
                "Double" => "double",
                "Single" => "float",
                _ => "int",
            };

            // Restricted NumberStyles (patch P14): integer path forbids exponents/currency;
            // float path allows decimal separators + thousands but still disallows currency / parentheses.
            string numberStyles = isInteger
                ? "NumberStyles.Integer | NumberStyles.AllowLeadingSign | NumberStyles.AllowTrailingWhite | NumberStyles.AllowLeadingWhite"
                : "NumberStyles.Float | NumberStyles.AllowThousands";

            bool propertyIsNullable = field.IsNullable;

            _ = sb.AppendLine();
            _ = sb.AppendLine("    private void On" + field.PropertyName + "Changed(string? value)");
            _ = sb.AppendLine("    {");
            _ = sb.AppendLine("        _" + field.PropertyName + "String = value;");
            _ = sb.AppendLine("        if (string.IsNullOrWhiteSpace(value))");
            _ = sb.AppendLine("        {");
            if (propertyIsNullable) {
                _ = sb.AppendLine("            _model." + field.PropertyName + " = null;");
                _ = sb.AppendLine("            _" + field.PropertyName + "ParseError = null;");
            }
            else {
                // Empty is ambiguous for a non-nullable value type; leave the previous value untouched
                // and flag the input as required (patch P4).
                _ = sb.AppendLine("            _" + field.PropertyName + "ParseError = \"A number is required.\";");
            }

            _ = sb.AppendLine("            return;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        if (" + numericType + ".TryParse(value, " + numberStyles + ", CultureInfo.CurrentCulture, out var parsed))");
            _ = sb.AppendLine("        {");
            // Reject non-finite for floating-point types so NaN / Infinity cannot round-trip.
            if (numericType is "double" or "float") {
                _ = sb.AppendLine("            if (" + numericType + ".IsFinite(parsed))");
                _ = sb.AppendLine("            {");
                _ = sb.AppendLine("                _model." + field.PropertyName + " = parsed;");
                _ = sb.AppendLine("                _" + field.PropertyName + "ParseError = null;");
                _ = sb.AppendLine("            }");
                _ = sb.AppendLine("            else");
                _ = sb.AppendLine("            {");
                _ = sb.AppendLine("                _" + field.PropertyName + "ParseError = \"NaN and Infinity are not allowed.\";");
                _ = sb.AppendLine("            }");
            }
            else {
                _ = sb.AppendLine("            _model." + field.PropertyName + " = parsed;");
                _ = sb.AppendLine("            _" + field.PropertyName + "ParseError = null;");
            }

            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        else");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            _" + field.PropertyName + "ParseError = \"Invalid number format.\";");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("    }");
        }
    }

    private static void EmitHumanizeHelper(StringBuilder sb) {
        int maxLen = CommandFormTransform.EnumOptionLabelMaxLength;
        _ = sb.AppendLine();
        // Story 2-2 code-review P38 — char.IsUpper covers non-ASCII uppercase (Ü, Ñ, É).
        // Story 2-2 code-review P37 — truncate on rune boundary to avoid splitting UTF-16 surrogate pairs.
        _ = sb.AppendLine("    private static string HumanizeEnumLabel(string value)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (string.IsNullOrEmpty(value)) return value;");
        _ = sb.AppendLine("        var sb = new System.Text.StringBuilder(value.Length + 8);");
        _ = sb.AppendLine("        for (int i = 0; i < value.Length; i++)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            char c = value[i];");
        _ = sb.AppendLine("            if (i == 0) { sb.Append(char.ToUpperInvariant(c)); continue; }");
        _ = sb.AppendLine("            bool isUpper = char.IsUpper(c);");
        _ = sb.AppendLine("            bool prevIsLower = char.IsLower(value[i - 1]);");
        _ = sb.AppendLine("            if (isUpper && prevIsLower) { sb.Append(' '); sb.Append(c); }");
        _ = sb.AppendLine("            else { sb.Append(c); }");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        string label = sb.ToString();");
        _ = sb.AppendLine("        if (label.Length <= " + maxLen + ") return label;");
        _ = sb.AppendLine("        int cutoff = " + (maxLen - 1) + ";");
        _ = sb.AppendLine("        if (cutoff > 0 && char.IsHighSurrogate(label[cutoff - 1])) { cutoff--; }");
        _ = sb.AppendLine("        return label.Substring(0, cutoff) + \"\\u2026\";");
        _ = sb.AppendLine("    }");
    }

    /// <summary>
    /// Escapes a string for embedding in a C# double-quoted literal. Delegates to Roslyn's
    /// <see cref="Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(string, bool)"/>
    /// so Unicode control characters, lone surrogates, and all the standard escape sequences
    /// are handled correctly. Patch 2026-04-16 P-05.
    /// </summary>
    private static string EscapeString(string value) => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: false);
}
