using System.Text;

using Hexalith.FrontComposer.SourceTools.Transforms;

namespace Hexalith.FrontComposer.SourceTools.Emitters;

/// <summary>
/// Emits a Blazor command form partial class (.g.razor.cs) from a <see cref="CommandFormModel"/>.
/// </summary>
/// <remarks>
/// Decision D3: wraps the form in a standard Blazor <c>&lt;EditForm&gt;</c> -- <c>FluentEditForm</c>
/// does not exist in Fluent UI v5. Decision D11: emits <c>&lt;DataAnnotationsValidator /&gt;</c> so
/// adopters get validation via <c>[Required]</c>, <c>[Range]</c>, etc. without pulling in FluentValidation.
/// Decision D7: localizer is runtime-resolved through the emitted <c>ResolveLabel</c> helper.
/// Decision D13: visual feedback is limited to a <c>FluentProgressRing</c> inside the submit button
/// while the state is <c>Submitting</c>; richer lifecycle feedback lives in Story 2-4.
/// </remarks>
public static class CommandFormEmitter {
    /// <summary>
    /// Generates the command form partial class source.
    /// </summary>
    /// <param name="form">Form-rendering metadata.</param>
    /// <param name="fluxor">Companion Fluxor metadata that names the state, actions wrapper, and feature type.</param>
    /// <returns>The generated C# source code.</returns>
    public static string Emit(CommandFormModel form, CommandFluxorModel fluxor) {
        var sb = new StringBuilder(4096);

        _ = sb.AppendLine("// Generated by FrontComposer source generator");
        _ = sb.AppendLine("// Do not edit directly");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine("#pragma warning disable ASP0006 // seq++ pattern inside BuildRenderTree");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine("using System.Globalization;");
        _ = sb.AppendLine("using System.Linq;");
        _ = sb.AppendLine("using System.Threading;");
        _ = sb.AppendLine("using System.Threading.Tasks;");
        _ = sb.AppendLine("using Fluxor;");
        _ = sb.AppendLine("using Hexalith.FrontComposer.Contracts.Communication;");
        _ = sb.AppendLine("using Hexalith.FrontComposer.Contracts.Lifecycle;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components.Forms;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components.Rendering;");
        _ = sb.AppendLine("using Microsoft.Extensions.Localization;");
        _ = sb.AppendLine("using Microsoft.Extensions.Logging;");
        _ = sb.AppendLine("using Microsoft.FluentUI.AspNetCore.Components;");
        _ = sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(form.Namespace);
        if (hasNamespace) {
            _ = sb.AppendLine("namespace " + form.Namespace + ";");
            _ = sb.AppendLine();
        }

        string componentName = form.TypeName + "Form";
        string escapedButtonLabel = EscapeString(form.ButtonLabel);
        string commandFqn = form.CommandFullyQualifiedName;

        _ = sb.AppendLine("/// <summary>");
        _ = sb.AppendLine("/// Auto-generated command form for <see cref=\"" + form.TypeName + "\"/>.");
        _ = sb.AppendLine("/// </summary>");
        _ = sb.AppendLine("public partial class " + componentName + " : ComponentBase, IDisposable");
        _ = sb.AppendLine("{");

        _ = sb.AppendLine("    [Parameter] public " + commandFqn + "? InitialValue { get; set; }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    [Inject] private IState<" + fluxor.StateName + "> LifecycleState { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private IDispatcher Dispatcher { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private ICommandService CommandService { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private IStringLocalizer<" + commandFqn + "> Localizer { get; set; } = default!;");
        _ = sb.AppendLine("    [Inject] private ILogger<" + componentName + ">? Logger { get; set; }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private " + commandFqn + " _model = new();");
        _ = sb.AppendLine("    private EditContext? _editContext;");
        _ = sb.AppendLine("    private CancellationTokenSource? _cts;");
        _ = sb.AppendLine("    /// <summary>Indicates the form has been modified since creation. Used by later stories to warn on navigation.</summary>");
        _ = sb.AppendLine("    public bool IsDirty { get; private set; }");
        _ = sb.AppendLine();

        EmitFieldBackingFields(sb, form);

        _ = sb.AppendLine("    /// <inheritdoc />");
        _ = sb.AppendLine("    protected override void OnInitialized()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        _model = InitialValue ?? new();");
        _ = sb.AppendLine("        _editContext = new EditContext(_model);");
        _ = sb.AppendLine("        _editContext.OnFieldChanged += OnEditContextFieldChanged;");
        _ = sb.AppendLine("        LifecycleState.StateChanged += OnStateChanged;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private void OnEditContextFieldChanged(object? sender, FieldChangedEventArgs e) { IsDirty = true; }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private void OnStateChanged(object? sender, EventArgs e) => InvokeAsync(StateHasChanged);");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <summary>Resolves a field label via <see cref=\"IStringLocalizer\"/>, falling back to the compile-time label.</summary>");
        _ = sb.AppendLine("    private string ResolveLabel(string propertyName, string staticLabel)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        try");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            var localized = Localizer?[propertyName];");
        _ = sb.AppendLine("            if (localized is not null && !localized.ResourceNotFound && !string.IsNullOrEmpty(localized.Value))");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                return localized.Value;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        catch { /* localizer failures are non-fatal. */ }");
        _ = sb.AppendLine("        return staticLabel;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        EmitSubmitMethod(sb, form, fluxor);
        EmitDispose(sb);
        EmitBuildRenderTree(sb, form, fluxor, escapedButtonLabel);
        EmitNumericConverters(sb, form);

        _ = sb.AppendLine("}");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#pragma warning restore ASP0006");

        return sb.ToString();
    }

    private static void EmitFieldBackingFields(StringBuilder sb, CommandFormModel form) {
        foreach (FormFieldModel field in form.Fields) {
            if (field.TypeCategory == FormFieldTypeCategory.NumberInput
                || field.TypeCategory == FormFieldTypeCategory.DecimalInput) {
                _ = sb.AppendLine("    private string? _" + field.PropertyName + "String;");
                _ = sb.AppendLine("    private string? _" + field.PropertyName + "ParseError;");
            }
        }

        if (form.Fields.Count > 0) {
            _ = sb.AppendLine();
        }
    }

    private static void EmitSubmitMethod(StringBuilder sb, CommandFormModel form, CommandFluxorModel fluxor) {
        _ = sb.AppendLine("    private async Task OnValidSubmitAsync()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        _cts?.Cancel();");
        _ = sb.AppendLine("        _cts = new CancellationTokenSource();");
        _ = sb.AppendLine("        var correlationId = Guid.NewGuid().ToString();");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        Dispatcher.Dispatch(new " + fluxor.ActionsWrapperName + ".SubmittedAction(correlationId, _model));");
        _ = sb.AppendLine("        await InvokeAsync(StateHasChanged);");
        _ = sb.AppendLine("        Logger?.LogInformation(\"Command submitted. CorrelationId={CorrelationId}\", correlationId);");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        try");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            var result = await CommandService.DispatchAsync(");
        _ = sb.AppendLine("                _model,");
        _ = sb.AppendLine("                onLifecycleChange: (state, _) =>");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    switch (state)");
        _ = sb.AppendLine("                    {");
        _ = sb.AppendLine("                        case CommandLifecycleState.Syncing:");
        _ = sb.AppendLine("                            Dispatcher.Dispatch(new " + fluxor.ActionsWrapperName + ".SyncingAction(correlationId));");
        _ = sb.AppendLine("                            break;");
        _ = sb.AppendLine("                        case CommandLifecycleState.Confirmed:");
        _ = sb.AppendLine("                            Dispatcher.Dispatch(new " + fluxor.ActionsWrapperName + ".ConfirmedAction(correlationId));");
        _ = sb.AppendLine("                            break;");
        _ = sb.AppendLine("                    }");
        _ = sb.AppendLine("                },");
        _ = sb.AppendLine("                cancellationToken: _cts.Token);");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            Dispatcher.Dispatch(new " + fluxor.ActionsWrapperName + ".AcknowledgedAction(correlationId, result.MessageId));");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        catch (CommandRejectedException ex)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            Dispatcher.Dispatch(new " + fluxor.ActionsWrapperName + ".RejectedAction(correlationId, ex.Message, ex.Resolution));");
        _ = sb.AppendLine("            Logger?.LogWarning(\"Command rejected. CorrelationId={CorrelationId} Reason={Reason}\", correlationId, ex.Message);");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        catch (OperationCanceledException)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            // Form disposed during submission. Ignore.");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
    }

    private static void EmitDispose(StringBuilder sb) {
        _ = sb.AppendLine("    /// <inheritdoc />");
        _ = sb.AppendLine("    public void Dispose()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        _cts?.Cancel();");
        _ = sb.AppendLine("        _cts?.Dispose();");
        _ = sb.AppendLine("        if (_editContext is not null)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            _editContext.OnFieldChanged -= OnEditContextFieldChanged;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        LifecycleState.StateChanged -= OnStateChanged;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
    }

    private static void EmitBuildRenderTree(StringBuilder sb, CommandFormModel form, CommandFluxorModel fluxor, string escapedButtonLabel) {
        _ = sb.AppendLine("    /// <inheritdoc />");
        _ = sb.AppendLine("    protected override void BuildRenderTree(RenderTreeBuilder builder)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        int seq = 0;");
        _ = sb.AppendLine("        builder.OpenElement(seq++, \"div\");");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"style\", \"max-width: 720px; margin: 0 auto;\");");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"aria-label\", \"Send " + EscapeString(form.TypeName) + " command form\");");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        builder.OpenComponent<EditForm>(seq++);");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"EditContext\", _editContext);");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"OnValidSubmit\", EventCallback.Factory.Create<EditContext>(this, _ => OnValidSubmitAsync()));");
        _ = sb.AppendLine("        RenderFragment<EditContext> formBody = _ => (RenderFragment)(__b =>");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            int cseq = 0;");
        _ = sb.AppendLine("            __b.OpenComponent<DataAnnotationsValidator>(cseq++);");
        _ = sb.AppendLine("            __b.CloseComponent();");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            __b.OpenComponent<FluentValidationSummary>(cseq++);");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Model\", (object)_model);");
        _ = sb.AppendLine("            __b.CloseComponent();");

        foreach (FormFieldModel field in form.Fields) {
            EmitField(sb, field);
        }

        // Submit button
        _ = sb.AppendLine();
        _ = sb.AppendLine("            __b.OpenComponent<FluentButton>(cseq++);");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Type\", ButtonType.Submit);");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Disabled\", LifecycleState.Value.State != CommandLifecycleState.Idle);");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"ChildContent\", (RenderFragment)(__btn =>");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                int bseq = 0;");
        _ = sb.AppendLine("                if (LifecycleState.Value.State == CommandLifecycleState.Submitting)");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    __btn.OpenComponent<FluentSpinner>(bseq++);");
        _ = sb.AppendLine("                    __btn.AddAttribute(bseq++, \"Style\", \"width: 20px; height: 20px; margin-right: 8px;\");");
        _ = sb.AppendLine("                    __btn.CloseComponent();");
        _ = sb.AppendLine("                }");
        _ = sb.AppendLine("                __btn.AddContent(bseq++, \"" + escapedButtonLabel + "\");");
        _ = sb.AppendLine("            }));");
        _ = sb.AppendLine("            __b.CloseComponent();");
        _ = sb.AppendLine("        });");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"ChildContent\", formBody);");
        _ = sb.AppendLine("        builder.CloseComponent();");
        _ = sb.AppendLine("        builder.CloseElement();");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
    }

    private static void EmitField(StringBuilder sb, FormFieldModel field) {
        string propertyName = field.PropertyName;
        string staticLabel = EscapeString(field.StaticLabel);
        string isRequired = field.IsRequired ? "true" : "false";

        _ = sb.AppendLine();
        _ = sb.AppendLine("            // Field: " + propertyName);

        switch (field.TypeCategory) {
            case FormFieldTypeCategory.TextInput:
                EmitTextInput(sb, propertyName, staticLabel, isRequired, inputType: null, monospace: false);
                break;
            case FormFieldTypeCategory.NumberInput:
                EmitNumericInput(sb, field, decimalMode: false);
                break;
            case FormFieldTypeCategory.DecimalInput:
                EmitNumericInput(sb, field, decimalMode: true);
                break;
            case FormFieldTypeCategory.Switch:
                EmitSwitch(sb, propertyName, staticLabel);
                break;
            case FormFieldTypeCategory.DatePicker:
                EmitDatePicker(sb, field);
                break;
            case FormFieldTypeCategory.Select:
                EmitEnumSelect(sb, field);
                break;
            case FormFieldTypeCategory.MonospaceText:
                EmitTextInput(sb, propertyName, staticLabel, isRequired, inputType: null, monospace: true);
                break;
            case FormFieldTypeCategory.Placeholder:
                EmitPlaceholder(sb, field);
                break;
        }
    }

    private static void EmitTextInput(StringBuilder sb, string propertyName, string staticLabel, string isRequired, string? inputType, bool monospace) {
        _ = sb.AppendLine("            __b.OpenComponent<FluentTextInput>(cseq++);");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Value\", _model." + propertyName + ");");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"ValueChanged\", EventCallback.Factory.Create<string?>(this, v => _model." + propertyName + " = v ?? string.Empty));");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Label\", ResolveLabel(\"" + propertyName + "\", \"" + staticLabel + "\"));");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Required\", " + isRequired + ");");
        if (inputType is not null) {
            _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"TextInputType\", TextInputType." + inputType + ");");
        }

        if (monospace) {
            _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Class\", \"fc-monospace\");");
        }

        _ = sb.AppendLine("            __b.CloseComponent();");
    }

    private static void EmitNumericInput(StringBuilder sb, FormFieldModel field, bool decimalMode) {
        string propertyName = field.PropertyName;
        string staticLabel = EscapeString(field.StaticLabel);
        string isRequired = field.IsRequired ? "true" : "false";

        _ = sb.AppendLine("            __b.OpenComponent<FluentTextInput>(cseq++);");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Value\", _" + propertyName + "String ?? _model." + propertyName + ".ToString(CultureInfo.CurrentCulture));");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"ValueChanged\", EventCallback.Factory.Create<string?>(this, v => On" + propertyName + "Changed(v)));");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Label\", ResolveLabel(\"" + propertyName + "\", \"" + staticLabel + "\"));");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Required\", " + isRequired + ");");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"TextInputType\", TextInputType.Number);");
        if (decimalMode) {
            _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"InputMode\", TextInputMode.Decimal);");
        }

        _ = sb.AppendLine("            if (!string.IsNullOrEmpty(_" + propertyName + "ParseError))");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                __b.AddAttribute(cseq++, \"Message\", _" + propertyName + "ParseError);");
        _ = sb.AppendLine("                __b.AddAttribute(cseq++, \"MessageState\", MessageState.Error);");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("            __b.CloseComponent();");
    }

    private static void EmitSwitch(StringBuilder sb, string propertyName, string staticLabel) {
        _ = sb.AppendLine("            __b.OpenComponent<FluentSwitch>(cseq++);");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Value\", _model." + propertyName + ");");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"ValueChanged\", EventCallback.Factory.Create<bool>(this, v => _model." + propertyName + " = v));");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Label\", ResolveLabel(\"" + propertyName + "\", \"" + staticLabel + "\"));");
        _ = sb.AppendLine("            __b.CloseComponent();");
    }

    private static void EmitDatePicker(StringBuilder sb, FormFieldModel field) {
        string propertyName = field.PropertyName;
        string staticLabel = EscapeString(field.StaticLabel);
        string valueType = field.TypeName switch {
            "DateTime" => "DateTime",
            "DateTimeOffset" => "DateTimeOffset",
            "DateOnly" => "DateOnly",
            _ => "DateTime",
        };

        string genericArg = field.IsNullable ? valueType + "?" : valueType;

        _ = sb.AppendLine("            __b.OpenComponent<FluentDatePicker<" + genericArg + ">>(cseq++);");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Value\", _model." + propertyName + ");");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"ValueChanged\", EventCallback.Factory.Create<" + genericArg + ">(this, v => _model." + propertyName + " = v));");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Label\", ResolveLabel(\"" + propertyName + "\", \"" + staticLabel + "\"));");
        _ = sb.AppendLine("            __b.CloseComponent();");
    }

    private static void EmitEnumSelect(StringBuilder sb, FormFieldModel field) {
        string propertyName = field.PropertyName;
        string staticLabel = EscapeString(field.StaticLabel);
        string enumFqn = field.EnumFullyQualifiedName ?? "object";

        _ = sb.AppendLine("            __b.OpenComponent<FluentSelect<" + enumFqn + ", " + enumFqn + ">>(cseq++);");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Items\", (System.Collections.Generic.IEnumerable<" + enumFqn + ">)System.Enum.GetValues<" + enumFqn + ">());");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Value\", _model." + propertyName + ");");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"ValueChanged\", EventCallback.Factory.Create<" + enumFqn + ">(this, v => _model." + propertyName + " = v));");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"Label\", ResolveLabel(\"" + propertyName + "\", \"" + staticLabel + "\"));");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"OptionText\", (Func<" + enumFqn + ", string>)(e => HumanizeEnumLabel(e.ToString() ?? string.Empty)));");
        _ = sb.AppendLine("            __b.CloseComponent();");
    }

    private static void EmitPlaceholder(StringBuilder sb, FormFieldModel field) {
        string propertyName = field.PropertyName;
        string typeName = EscapeString(field.TypeName);

        _ = sb.AppendLine("            __b.OpenComponent<global::Hexalith.FrontComposer.Shell.Components.Rendering.FcFieldPlaceholder>(cseq++);");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"FieldName\", \"" + EscapeString(propertyName) + "\");");
        _ = sb.AppendLine("            __b.AddAttribute(cseq++, \"TypeName\", \"" + typeName + "\");");
        _ = sb.AppendLine("            __b.CloseComponent();");
    }

    private static void EmitNumericConverters(StringBuilder sb, CommandFormModel form) {
        bool emittedHumanize = false;
        foreach (FormFieldModel field in form.Fields) {
            if (field.TypeCategory != FormFieldTypeCategory.Select) {
                continue;
            }

            if (!emittedHumanize) {
                EmitHumanizeHelper(sb);
                emittedHumanize = true;
            }
        }

        foreach (FormFieldModel field in form.Fields) {
            if (field.TypeCategory != FormFieldTypeCategory.NumberInput
                && field.TypeCategory != FormFieldTypeCategory.DecimalInput) {
                continue;
            }

            string numericType = field.TypeName switch {
                "Int32" => "int",
                "Int64" => "long",
                "Decimal" => "decimal",
                "Double" => "double",
                "Single" => "float",
                _ => "int",
            };

            _ = sb.AppendLine();
            _ = sb.AppendLine("    private void On" + field.PropertyName + "Changed(string? value)");
            _ = sb.AppendLine("    {");
            _ = sb.AppendLine("        _" + field.PropertyName + "String = value;");
            _ = sb.AppendLine("        if (string.IsNullOrWhiteSpace(value))");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            _model." + field.PropertyName + " = default;");
            _ = sb.AppendLine("            _" + field.PropertyName + "ParseError = null;");
            _ = sb.AppendLine("            return;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        if (" + numericType + ".TryParse(value, NumberStyles.Any, CultureInfo.CurrentCulture, out var parsed))");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            _model." + field.PropertyName + " = parsed;");
            _ = sb.AppendLine("            _" + field.PropertyName + "ParseError = null;");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("        else");
            _ = sb.AppendLine("        {");
            _ = sb.AppendLine("            _" + field.PropertyName + "ParseError = \"Invalid number format.\";");
            _ = sb.AppendLine("        }");
            _ = sb.AppendLine("    }");
        }

        if (form.Fields.Any(f => f.TypeCategory == FormFieldTypeCategory.NumberInput || f.TypeCategory == FormFieldTypeCategory.DecimalInput)) {
            _ = sb.AppendLine();
            _ = sb.AppendLine("    private static System.Globalization.NumberStyles NumberStyles_Any => System.Globalization.NumberStyles.Any;");
        }
    }

    private static void EmitHumanizeHelper(StringBuilder sb) {
        int maxLen = CommandFormTransform.EnumOptionLabelMaxLength;
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private static string HumanizeEnumLabel(string value)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (string.IsNullOrEmpty(value)) return value;");
        _ = sb.AppendLine("        var sb = new System.Text.StringBuilder(value.Length + 8);");
        _ = sb.AppendLine("        for (int i = 0; i < value.Length; i++)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            char c = value[i];");
        _ = sb.AppendLine("            if (i == 0) { sb.Append(char.ToUpperInvariant(c)); continue; }");
        _ = sb.AppendLine("            bool isUpper = c >= 'A' && c <= 'Z';");
        _ = sb.AppendLine("            bool prevIsLower = value[i - 1] >= 'a' && value[i - 1] <= 'z';");
        _ = sb.AppendLine("            if (isUpper && prevIsLower) { sb.Append(' '); sb.Append(c); }");
        _ = sb.AppendLine("            else { sb.Append(c); }");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        string label = sb.ToString();");
        _ = sb.AppendLine("        if (label.Length <= " + maxLen + ") return label;");
        _ = sb.AppendLine("        return label.Substring(0, " + (maxLen - 1) + ") + \"\\u2026\";");
        _ = sb.AppendLine("    }");
    }

    private static string EscapeString(string value) => value
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"")
        .Replace("\n", "\\n")
        .Replace("\r", "\\r")
        .Replace("\t", "\\t")
        .Replace("\0", "\\0");
}
