
using System.Text;

using Hexalith.FrontComposer.SourceTools.Transforms;

namespace Hexalith.FrontComposer.SourceTools.Emitters;
/// <summary>
/// Emits Fluxor Feature and State record source code from a FluxorModel.
/// </summary>
public static class FluxorFeatureEmitter {
    /// <summary>
    /// Generates the Feature + State source code.
    /// </summary>
    /// <param name="model">The Fluxor output model.</param>
    /// <returns>The generated C# source code string.</returns>
    public static string Emit(FluxorModel model) {
        var sb = new StringBuilder(1024);

        _ = sb.AppendLine("// Generated by FrontComposer source generator");
        _ = sb.AppendLine("// Do not edit directly");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System.Collections.Generic;");
        _ = sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace) {
            _ = sb.AppendLine("namespace " + model.Namespace + ";");
            _ = sb.AppendLine();
        }

        // State record
        _ = sb.AppendLine("/// <summary>");
        _ = sb.AppendLine("/// Fluxor state for <see cref=\"" + model.TypeName + "\"/> projection list view.");
        _ = sb.AppendLine("/// </summary>");
        _ = sb.AppendLine("public record " + model.StateName + "(bool IsLoading, IReadOnlyList<" + model.TypeName + ">? Items, string? Error);");
        _ = sb.AppendLine();

        // Feature class
        _ = sb.AppendLine("/// <summary>");
        _ = sb.AppendLine("/// Fluxor feature for <see cref=\"" + model.TypeName + "\"/> state management.");
        _ = sb.AppendLine("/// </summary>");
        _ = sb.AppendLine("public class " + model.FeatureName + " : Fluxor.Feature<" + model.StateName + ">");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    /// <inheritdoc />");
        _ = sb.AppendLine("    public override string GetName() => nameof(" + model.StateName + ");");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <inheritdoc />");
        _ = sb.AppendLine("    protected override " + model.StateName + " GetInitialState() =>");
        _ = sb.AppendLine("        new(IsLoading: false, Items: null, Error: null);");
        _ = sb.AppendLine("}");

        return sb.ToString();
    }
}
