#nullable enable

namespace Hexalith.FrontComposer.SourceTools.Emitters;

using System.Text;

using Hexalith.FrontComposer.SourceTools.Transforms;

/// <summary>
/// Emits Fluxor Feature and State record source code from a FluxorModel.
/// </summary>
public static class FluxorFeatureEmitter
{
    /// <summary>
    /// Generates the Feature + State source code.
    /// </summary>
    /// <param name="model">The Fluxor output model.</param>
    /// <returns>The generated C# source code string.</returns>
    public static string Emit(FluxorModel model)
    {
        StringBuilder sb = new StringBuilder(1024);

        sb.AppendLine("// Generated by FrontComposer source generator");
        sb.AppendLine("// Do not edit directly");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine("namespace " + model.Namespace + ";");
            sb.AppendLine();
        }

        // State record
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Fluxor state for <see cref=\"" + model.TypeName + "\"/> projection list view.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public record " + model.StateName + "(bool IsLoading, IReadOnlyList<" + model.TypeName + ">? Items, string? Error);");
        sb.AppendLine();

        // Feature class
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Fluxor feature for <see cref=\"" + model.TypeName + "\"/> state management.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public class " + model.FeatureName + " : Fluxor.Feature<" + model.StateName + ">");
        sb.AppendLine("{");
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public override string GetName() => nameof(" + model.StateName + ");");
        sb.AppendLine();
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    protected override " + model.StateName + " GetInitialState() =>");
        sb.AppendLine("        new(IsLoading: false, Items: null, Error: null);");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
