
using System.Text;

using Hexalith.FrontComposer.SourceTools.Transforms;

namespace Hexalith.FrontComposer.SourceTools.Emitters;
/// <summary>
/// Emits Fluxor Action records and Reducer static class source code from a FluxorModel.
/// </summary>
public static class FluxorActionsEmitter {
    /// <summary>
    /// Generates the Action records source code.
    /// </summary>
    /// <param name="model">The Fluxor output model.</param>
    /// <returns>The generated C# source code string.</returns>
    public static string EmitActions(FluxorModel model) {
        var sb = new StringBuilder(1024);

        _ = sb.AppendLine("// Generated by FrontComposer source generator");
        _ = sb.AppendLine("// Do not edit directly");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System.Collections.Generic;");
        _ = sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace) {
            _ = sb.AppendLine("namespace " + model.Namespace + ";");
            _ = sb.AppendLine();
        }

        // Actions (past-tense naming convention)
        _ = sb.AppendLine("/// <summary>");
        _ = sb.AppendLine("/// Triggers data fetch for <see cref=\"" + model.TypeName + "\"/>.");
        _ = sb.AppendLine("/// </summary>");
        _ = sb.AppendLine("public record " + model.TypeName + "LoadRequestedAction();");
        _ = sb.AppendLine();

        _ = sb.AppendLine("/// <summary>");
        _ = sb.AppendLine("/// Data arrived for <see cref=\"" + model.TypeName + "\"/>.");
        _ = sb.AppendLine("/// </summary>");
        _ = sb.AppendLine("public record " + model.TypeName + "LoadedAction(IReadOnlyList<" + model.TypeName + "> Items);");
        _ = sb.AppendLine();

        _ = sb.AppendLine("/// <summary>");
        _ = sb.AppendLine("/// Data fetch failed for <see cref=\"" + model.TypeName + "\"/>.");
        _ = sb.AppendLine("/// </summary>");
        _ = sb.AppendLine("public record " + model.TypeName + "LoadFailedAction(string Error);");

        return sb.ToString();
    }

    /// <summary>
    /// Generates the Reducer static class source code.
    /// </summary>
    /// <param name="model">The Fluxor output model.</param>
    /// <returns>The generated C# source code string.</returns>
    public static string EmitReducers(FluxorModel model) {
        var sb = new StringBuilder(1024);

        _ = sb.AppendLine("// Generated by FrontComposer source generator");
        _ = sb.AppendLine("// Do not edit directly");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace) {
            _ = sb.AppendLine("namespace " + model.Namespace + ";");
            _ = sb.AppendLine();
        }

        _ = sb.AppendLine("/// <summary>");
        _ = sb.AppendLine("/// Fluxor reducers for <see cref=\"" + model.TypeName + "\"/> state transitions.");
        _ = sb.AppendLine("/// </summary>");
        _ = sb.AppendLine("public static class " + model.TypeName + "Reducers");
        _ = sb.AppendLine("{");

        // LoadRequested reducer
        _ = sb.AppendLine("    /// <summary>");
        _ = sb.AppendLine("    /// Handles <see cref=\"" + model.TypeName + "LoadRequestedAction\"/>.");
        _ = sb.AppendLine("    /// </summary>");
        _ = sb.AppendLine("    [Fluxor.ReducerMethod]");
        _ = sb.AppendLine("    public static " + model.StateName + " On" + model.TypeName + "LoadRequested(" + model.StateName + " state, " + model.TypeName + "LoadRequestedAction action)");
        _ = sb.AppendLine("        => state with { IsLoading = true, Error = null };");
        _ = sb.AppendLine();

        // Loaded reducer
        _ = sb.AppendLine("    /// <summary>");
        _ = sb.AppendLine("    /// Handles <see cref=\"" + model.TypeName + "LoadedAction\"/>.");
        _ = sb.AppendLine("    /// </summary>");
        _ = sb.AppendLine("    [Fluxor.ReducerMethod]");
        _ = sb.AppendLine("    public static " + model.StateName + " On" + model.TypeName + "Loaded(" + model.StateName + " state, " + model.TypeName + "LoadedAction action)");
        _ = sb.AppendLine("        => state with { IsLoading = false, Items = action.Items, Error = null };");
        _ = sb.AppendLine();

        // LoadFailed reducer
        _ = sb.AppendLine("    /// <summary>");
        _ = sb.AppendLine("    /// Handles <see cref=\"" + model.TypeName + "LoadFailedAction\"/>.");
        _ = sb.AppendLine("    /// </summary>");
        _ = sb.AppendLine("    [Fluxor.ReducerMethod]");
        _ = sb.AppendLine("    public static " + model.StateName + " On" + model.TypeName + "LoadFailed(" + model.StateName + " state, " + model.TypeName + "LoadFailedAction action)");
        _ = sb.AppendLine("        => state with { IsLoading = false, Error = action.Error };");

        _ = sb.AppendLine("}");

        return sb.ToString();
    }
}
