using System.Text;

using Hexalith.FrontComposer.SourceTools.Transforms;

namespace Hexalith.FrontComposer.SourceTools.Emitters;

/// <summary>
/// Story 2-2 Decision D28 — emits a per-command typed Fluxor subscriber that records the
/// last-confirmed command into <c>LastUsedValueProvider</c> via a <c>CorrelationId</c>-keyed
/// <see cref="System.Collections.Concurrent.ConcurrentDictionary{TKey, TValue}"/> (Decision D38)
/// with TTL = 5 minutes and MaxInFlight = 16 eviction.
/// </summary>
public static class LastUsedSubscriberEmitter {
    public const int TtlMinutes = 5;
    public const int MaxInFlight = 16;

    /// <summary>
    /// Emits the per-command subscriber source.
    /// </summary>
    public static string Emit(CommandFluxorModel fluxor) {
        if (fluxor is null) {
            throw new ArgumentNullException(nameof(fluxor));
        }

        string commandFqn = fluxor.CommandFullyQualifiedName;
        string typeName = fluxor.TypeName;
        string subscriberName = typeName + "LastUsedSubscriber";
        string actionsWrapper = fluxor.ActionsWrapperName;

        StringBuilder sb = new(2048);
        _ = sb.AppendLine("// Generated by FrontComposer source generator (Story 2-2 Task 4bis / Decision D28+D38)");
        _ = sb.AppendLine("// Do not edit directly");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine("using System.Collections.Concurrent;");
        _ = sb.AppendLine("using System.Collections.Generic;");
        _ = sb.AppendLine("using System.Threading.Tasks;");
        _ = sb.AppendLine("using Fluxor;");
        _ = sb.AppendLine("using Hexalith.FrontComposer.Contracts.Rendering;");
        _ = sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        _ = sb.AppendLine("using Microsoft.Extensions.Logging;");
        _ = sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(fluxor.Namespace);
        if (hasNamespace) {
            _ = sb.AppendLine("namespace " + fluxor.Namespace + ";");
            _ = sb.AppendLine();
        }

        // Subscriber class.
        _ = sb.AppendLine("/// <summary>Per-command Fluxor subscriber that records confirmed values into LastUsedValueProvider (Decision D28).</summary>");
        _ = sb.AppendLine("public sealed class " + subscriberName + " : IDisposable");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    private readonly IActionSubscriber _subscriber;");
        _ = sb.AppendLine("    private readonly ILastUsedRecorder _recorder;");
        _ = sb.AppendLine("    private readonly ILogger<" + subscriberName + ">? _logger;");
        _ = sb.AppendLine("    private readonly TimeProvider _timeProvider;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private readonly ConcurrentDictionary<string, PendingEntry> _pending = new();");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private readonly record struct PendingEntry(" + commandFqn + " Command, DateTimeOffset CapturedAt);");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    public " + subscriberName + "(IActionSubscriber subscriber, ILastUsedRecorder recorder, ILogger<" + subscriberName + ">? logger = null, TimeProvider? timeProvider = null)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        _subscriber = subscriber;");
        _ = sb.AppendLine("        _recorder = recorder;");
        _ = sb.AppendLine("        _logger = logger;");
        _ = sb.AppendLine("        _timeProvider = timeProvider ?? TimeProvider.System;");
        _ = sb.AppendLine("        _subscriber.SubscribeToAction<" + actionsWrapper + ".SubmittedAction>(this, OnSubmitted);");
        _ = sb.AppendLine("        _subscriber.SubscribeToAction<" + actionsWrapper + ".ConfirmedAction>(this, OnConfirmed);");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private void OnSubmitted(" + actionsWrapper + ".SubmittedAction action)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        PruneExpiredAndCap();");
        _ = sb.AppendLine("        _pending[action.CorrelationId] = new PendingEntry(action.Command, _timeProvider.GetUtcNow());");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private void OnConfirmed(" + actionsWrapper + ".ConfirmedAction action)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (_pending.TryRemove(action.CorrelationId, out var entry))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            _ = RecordConfirmedAsync(entry.Command);");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private async Task RecordConfirmedAsync(" + commandFqn + " command)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        try");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            await _recorder.RecordAsync<" + commandFqn + ">(command).ConfigureAwait(false);");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("        catch (Exception ex)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            _logger?.LogError(ex, \"Failed to persist LastUsed for {CommandType}\", \"" + commandFqn + "\");");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private void PruneExpiredAndCap()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        var threshold = _timeProvider.GetUtcNow().AddMinutes(-" + TtlMinutes + ");");
        _ = sb.AppendLine("        foreach (var kvp in _pending)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            if (kvp.Value.CapturedAt < threshold)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                _ = _pending.TryRemove(kvp.Key, out _);");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        while (_pending.Count >= " + MaxInFlight + ")");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            string? oldestKey = null;");
        _ = sb.AppendLine("            DateTimeOffset oldestAt = DateTimeOffset.MaxValue;");
        _ = sb.AppendLine("            foreach (var kvp in _pending)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                if (kvp.Value.CapturedAt < oldestAt)");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    oldestAt = kvp.Value.CapturedAt;");
        _ = sb.AppendLine("                    oldestKey = kvp.Key;");
        _ = sb.AppendLine("                }");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            if (oldestKey is null) break;");
        _ = sb.AppendLine("            _ = _pending.TryRemove(oldestKey, out _);");
        _ = sb.AppendLine("            _logger?.LogWarning(\"D38 cap reached: evicted pending {CommandType} CorrelationId={CorrelationId}\", \"" + commandFqn + "\", oldestKey);");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        // Suppress 'unused' warning when both collections are empty.");
        _ = sb.AppendLine("        _ = threshold;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    public void Dispose() => _subscriber.UnsubscribeFromAllActions(this);");
        _ = sb.AppendLine("}");
        _ = sb.AppendLine();

        // ServiceCollection extension for explicit registration.
        _ = sb.AppendLine("public static class " + typeName + "LastUsedSubscriberRegistration");
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    public static IServiceCollection Add" + subscriberName + "(this IServiceCollection services)");
        _ = sb.AppendLine("        => services.AddScoped<" + subscriberName + ">();");
        _ = sb.AppendLine("}");

        return sb.ToString();
    }
}
