using System.Collections.Immutable;
using System.Text;

using Hexalith.FrontComposer.SourceTools.Parsing;
using Hexalith.FrontComposer.SourceTools.Transforms;

namespace Hexalith.FrontComposer.SourceTools.Emitters;

/// <summary>
/// Emits a compilation-level MCP manifest from SourceTools IR.
/// </summary>
public static class McpManifestEmitter {
    public const string GeneratedHintName = "FrontComposerMcpManifest.g.cs";

    public static string Emit(ImmutableArray<CommandModel> commands, ImmutableArray<DomainModel> projections) {
        Dictionary<string, int> commandBaseCounts = CountCommandBaseNames(commands);
        Dictionary<string, int> resourceBaseCounts = CountProjectionBaseUris(projections);
        List<McpCommandDescriptorModel> commandDescriptors = [];
        List<McpResourceDescriptorModel> resourceDescriptors = [];

        foreach (CommandModel command in commands) {
            string boundedContext = string.IsNullOrWhiteSpace(command.BoundedContext) ? "Default" : command.BoundedContext!;
            string baseName = McpManifestTransform.BuildCommandProtocolName(boundedContext, command.Namespace, command.TypeName, false);
            bool disambiguate = commandBaseCounts.TryGetValue(baseName, out int commandCount) && commandCount > 1;
            commandDescriptors.Add(McpManifestTransform.TransformCommand(command, disambiguate));
        }

        foreach (DomainModel projection in projections) {
            string boundedContext = string.IsNullOrWhiteSpace(projection.BoundedContext) ? "Default" : projection.BoundedContext!;
            string baseUri = McpManifestTransform.BuildProjectionUri(boundedContext, projection.Namespace, projection.TypeName, false);
            bool disambiguate = resourceBaseCounts.TryGetValue(baseUri, out int resourceCount) && resourceCount > 1;
            resourceDescriptors.Add(McpManifestTransform.TransformProjection(projection, disambiguate));
        }

        commandDescriptors.Sort((left, right) => string.CompareOrdinal(left.ProtocolName, right.ProtocolName));
        resourceDescriptors.Sort((left, right) => string.CompareOrdinal(left.ProtocolUri, right.ProtocolUri));

        var sb = new StringBuilder(4096);
        sb.AppendLine("// Generated by FrontComposer source generator");
        sb.AppendLine("// Do not edit directly");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Hexalith.FrontComposer.Contracts.Mcp;");
        sb.AppendLine();
        sb.AppendLine("namespace Hexalith.FrontComposer.Generated;");
        sb.AppendLine();
        sb.AppendLine("[GeneratedManifest]");
        sb.AppendLine("internal static class FrontComposerMcpGeneratedManifest");
        sb.AppendLine("{");
        sb.AppendLine("    public static McpManifest Manifest { get; } = new McpManifest(");
        sb.AppendLine("        \"" + Escape(McpManifestTransform.SchemaVersion) + "\",");
        EmitCommands(sb, commandDescriptors);
        sb.AppendLine(",");
        EmitResources(sb, resourceDescriptors);
        sb.AppendLine(");");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static Dictionary<string, int> CountCommandBaseNames(ImmutableArray<CommandModel> commands) {
        Dictionary<string, int> counts = new(StringComparer.OrdinalIgnoreCase);
        foreach (CommandModel command in commands) {
            string boundedContext = string.IsNullOrWhiteSpace(command.BoundedContext) ? "Default" : command.BoundedContext!;
            string key = McpManifestTransform.BuildCommandProtocolName(boundedContext, command.Namespace, command.TypeName, false);
            counts[key] = counts.TryGetValue(key, out int count) ? count + 1 : 1;
        }

        return counts;
    }

    private static Dictionary<string, int> CountProjectionBaseUris(ImmutableArray<DomainModel> projections) {
        Dictionary<string, int> counts = new(StringComparer.OrdinalIgnoreCase);
        foreach (DomainModel projection in projections) {
            string boundedContext = string.IsNullOrWhiteSpace(projection.BoundedContext) ? "Default" : projection.BoundedContext!;
            string key = McpManifestTransform.BuildProjectionUri(boundedContext, projection.Namespace, projection.TypeName, false);
            counts[key] = counts.TryGetValue(key, out int count) ? count + 1 : 1;
        }

        return counts;
    }

    private static void EmitCommands(StringBuilder sb, IReadOnlyList<McpCommandDescriptorModel> commands) {
        sb.AppendLine("        new List<McpCommandDescriptor>");
        sb.AppendLine("        {");
        foreach (McpCommandDescriptorModel command in commands) {
            sb.AppendLine("            new McpCommandDescriptor(");
            sb.AppendLine("                \"" + Escape(command.ProtocolName) + "\",");
            sb.AppendLine("                \"" + Escape(command.CommandTypeName) + "\",");
            sb.AppendLine("                \"" + Escape(command.BoundedContext) + "\",");
            sb.AppendLine("                \"" + Escape(command.Title) + "\",");
            sb.AppendLine("                " + Literal(command.Description) + ",");
            sb.AppendLine("                " + Literal(command.AuthorizationPolicyName) + ",");
            EmitParameters(sb, command.Parameters, 16);
            sb.AppendLine(",");
            sb.Append("                ");
            EmitStrings(sb, command.DerivablePropertyNames, 16);
            sb.AppendLine("),");
        }

        sb.Append("        }");
    }

    private static void EmitResources(StringBuilder sb, IReadOnlyList<McpResourceDescriptorModel> resources) {
        sb.AppendLine("        new List<McpResourceDescriptor>");
        sb.AppendLine("        {");
        foreach (McpResourceDescriptorModel resource in resources) {
            sb.AppendLine("            new McpResourceDescriptor(");
            sb.AppendLine("                \"" + Escape(resource.ProtocolUri) + "\",");
            sb.AppendLine("                \"" + Escape(resource.Name) + "\",");
            sb.AppendLine("                \"" + Escape(resource.ProjectionTypeName) + "\",");
            sb.AppendLine("                \"" + Escape(resource.BoundedContext) + "\",");
            sb.AppendLine("                \"" + Escape(resource.Title) + "\",");
            sb.AppendLine("                " + Literal(resource.Description) + ",");
            EmitParameters(sb, resource.Fields, 16);
            sb.AppendLine("),");
        }

        sb.Append("        }");
    }

    private static void EmitParameters(StringBuilder sb, IReadOnlyList<McpParameterDescriptorModel> parameters, int indent) {
        string pad = new(' ', indent);
        sb.AppendLine(pad + "new List<McpParameterDescriptor>");
        sb.AppendLine(pad + "{");
        foreach (McpParameterDescriptorModel parameter in parameters) {
            sb.AppendLine(pad + "    new McpParameterDescriptor(");
            sb.AppendLine(pad + "        \"" + Escape(parameter.Name) + "\",");
            sb.AppendLine(pad + "        \"" + Escape(parameter.TypeName) + "\",");
            sb.AppendLine(pad + "        \"" + Escape(parameter.JsonType) + "\",");
            sb.AppendLine(pad + "        " + Bool(parameter.IsRequired) + ",");
            sb.AppendLine(pad + "        " + Bool(parameter.IsNullable) + ",");
            sb.AppendLine(pad + "        \"" + Escape(parameter.Title) + "\",");
            sb.AppendLine(pad + "        " + Literal(parameter.Description) + ",");
            sb.Append(pad + "        ");
            EmitStrings(sb, parameter.EnumValues, indent + 8);
            sb.AppendLine(",");
            sb.AppendLine(pad + "        " + Bool(parameter.IsUnsupported) + "),");
        }

        sb.Append(pad + "}");
    }

    private static void EmitStrings(StringBuilder sb, IReadOnlyList<string> values, int indent) {
        string pad = new(' ', indent);
        sb.Append("new List<string>");
        if (values.Count == 0) {
            sb.Append("()");
            return;
        }

        sb.AppendLine();
        sb.AppendLine(pad + "{");
        foreach (string value in values) {
            sb.AppendLine(pad + "    \"" + Escape(value) + "\",");
        }

        sb.Append(pad + "}");
    }

    private static string Literal(string? value)
        => value is null ? "null" : "\"" + Escape(value) + "\"";

    private static string Bool(bool value) => value ? "true" : "false";

    private static string Escape(string value) {
        var sb = new StringBuilder(value.Length);
        foreach (char c in value) {
            switch (c) {
                case '\\':
                    sb.Append("\\\\");
                    break;
                case '"':
                    sb.Append("\\\"");
                    break;
                case '\r':
                    sb.Append("\\r");
                    break;
                case '\n':
                    sb.Append("\\n");
                    break;
                case '\t':
                    sb.Append("\\t");
                    break;
                case '\0':
                    sb.Append("\\0");
                    break;
                default:
                    // Escape all other control characters and the JS line separators U+2028/U+2029
                    // so the generated source compiles deterministically and downstream JSON encoders
                    // do not face ambiguous payloads.
                    if (char.IsControl(c) || c == '\u2028' || c == '\u2029') {
                        sb.Append("\\u").Append(((int)c).ToString("x4", System.Globalization.CultureInfo.InvariantCulture));
                    }
                    else {
                        sb.Append(c);
                    }

                    break;
            }
        }

        return sb.ToString();
    }
}
