using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Text;

using Hexalith.FrontComposer.SourceTools.Parsing;

namespace Hexalith.FrontComposer.SourceTools.Emitters;

/// <summary>
/// Story 6-2 T3 — emits the deterministic Level 2 projection-template manifest. The
/// manifest exposes the list of <c>ProjectionTemplateDescriptor</c> instances assembled
/// from all <c>[ProjectionTemplate]</c> markers discovered in the consuming compilation.
/// </summary>
/// <remarks>
/// <para>
/// The generated artifact is intentionally type-only metadata: projection FQN, role, template
/// FQN, contract version. It carries no timestamps, absolute file paths, tenant identifiers,
/// user identifiers, localized strings, or sample item payloads (Story 6-2 D15 / AC15).
/// </para>
/// </remarks>
public static class ProjectionTemplateManifestEmitter {
    public const string GeneratedTypeName = "__FrontComposerProjectionTemplatesRegistration";
    public const string GeneratedHintName = "__FrontComposerProjectionTemplatesRegistration.g.cs";

    /// <summary>
    /// Result of consolidating all <see cref="ProjectionTemplateMarkerInfo"/> instances —
    /// the deduplicated descriptor list that lands in the manifest plus any HFC1037
    /// duplicate diagnostics the generator must report.
    /// </summary>
    public sealed class ManifestEmissionResult {
        public ManifestEmissionResult(string source, ImmutableArray<DiagnosticInfo> duplicateDiagnostics) {
            Source = source;
            DuplicateDiagnostics = duplicateDiagnostics;
        }

        public string Source { get; }

        public ImmutableArray<DiagnosticInfo> DuplicateDiagnostics { get; }
    }

    public static ManifestEmissionResult Emit(ImmutableArray<ProjectionTemplateMarkerInfo> markers) {
        // Deterministic sort: by projection FQN → role (null first) → template FQN.
        ProjectionTemplateMarkerInfo[] sorted = [.. markers];
        Array.Sort(sorted, CompareMarkers);

        // HFC1037 duplicate detection: group by (projection, role) and emit one diagnostic
        // per duplicate group naming all colliding template types. Duplicates are excluded
        // from the manifest so runtime selection never picks a non-deterministic winner.
        Dictionary<string, List<ProjectionTemplateMarkerInfo>> grouped = [];
        foreach (ProjectionTemplateMarkerInfo marker in sorted) {
            string key = marker.ProjectionTypeFullName + "|" + (marker.Role ?? "<any>");
            if (!grouped.TryGetValue(key, out List<ProjectionTemplateMarkerInfo>? bucket)) {
                bucket = [];
                grouped[key] = bucket;
            }

            bucket.Add(marker);
        }

        ImmutableArray<DiagnosticInfo>.Builder duplicateDiagnostics = ImmutableArray.CreateBuilder<DiagnosticInfo>();
        List<ProjectionTemplateMarkerInfo> winners = [];

        // Walk the sorted markers a second time so winner order matches the sorted projection
        // FQN order (stable for snapshot tests).
        HashSet<string> emittedKeys = [];
        foreach (ProjectionTemplateMarkerInfo marker in sorted) {
            string key = marker.ProjectionTypeFullName + "|" + (marker.Role ?? "<any>");
            if (emittedKeys.Contains(key)) {
                continue;
            }

            List<ProjectionTemplateMarkerInfo> bucket = grouped[key];
            if (bucket.Count > 1) {
                string roleLabel = marker.Role ?? "<any role>";
                string templateNames = string.Join(
                    ", ",
                    bucket.ConvertAll(static m => m.TemplateTypeFullName));
                duplicateDiagnostics.Add(new DiagnosticInfo(
                    "HFC1037",
                    string.Format(
                        CultureInfo.InvariantCulture,
                        "What: Duplicate [ProjectionTemplate] markers target projection '{0}' with role '{1}'.\nExpected: At most one Level 2 template per (projection, role) tuple.\nGot: {2} markers — [{3}].\nFix: Keep one template, or disambiguate via the Role named argument.\nFallback: Runtime selection ignores all duplicates so behavior is not order-dependent.\nDocsLink: https://hexalith.github.io/FrontComposer/diagnostics/HFC1037",
                        marker.ProjectionTypeFullName,
                        roleLabel,
                        bucket.Count,
                        templateNames),
                    "Error",
                    marker.FilePath,
                    marker.Line,
                    marker.Column));
            }
            else {
                winners.Add(bucket[0]);
            }

            emittedKeys.Add(key);
        }

        StringBuilder sb = new(2048);
        _ = sb.AppendLine("// Generated by FrontComposer source generator (Story 6-2)");
        _ = sb.AppendLine("// Do not edit directly");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine("using System.Collections.Generic;");
        _ = sb.AppendLine();

        _ = sb.AppendLine("/// <summary>");
        _ = sb.AppendLine("/// Generated Level 2 projection-template manifest (Story 6-2 T3).");
        _ = sb.AppendLine("/// Type-only metadata — no tenant/user/item/localized values.");
        _ = sb.AppendLine("/// </summary>");
        _ = sb.AppendLine("internal static class " + GeneratedTypeName);
        _ = sb.AppendLine("{");
        _ = sb.AppendLine("    /// <summary>The Level 2 contract version this manifest was emitted against.</summary>");
        _ = sb.AppendLine("    public const int ContractVersion = "
            + ProjectionTemplateMarkerParser.CurrentContractPacked.ToString(CultureInfo.InvariantCulture)
            + ";");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <summary>The deduplicated, deterministically-ordered template descriptors discovered in this compilation.</summary>");
        _ = sb.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<global::Hexalith.FrontComposer.Contracts.Rendering.ProjectionTemplateDescriptor> Descriptors { get; } = new global::Hexalith.FrontComposer.Contracts.Rendering.ProjectionTemplateDescriptor[]");
        _ = sb.AppendLine("    {");

        for (int i = 0; i < winners.Count; i++) {
            ProjectionTemplateMarkerInfo m = winners[i];
            string roleExpr = m.Role is null
                ? "(global::Hexalith.FrontComposer.Contracts.Attributes.ProjectionRole?)null"
                : "(global::Hexalith.FrontComposer.Contracts.Attributes.ProjectionRole?)global::Hexalith.FrontComposer.Contracts.Attributes.ProjectionRole." + m.Role;
            string trailingComma = i == winners.Count - 1 ? string.Empty : ",";
            _ = sb.AppendLine("        new global::Hexalith.FrontComposer.Contracts.Rendering.ProjectionTemplateDescriptor(");
            _ = sb.AppendLine("            ProjectionType: typeof(" + m.ProjectionTypeFullName + "),");
            _ = sb.AppendLine("            Role: " + roleExpr + ",");
            _ = sb.AppendLine("            TemplateType: typeof(" + m.TemplateTypeFullName + "),");
            _ = sb.AppendLine("            ContractVersion: " + m.ExpectedContractVersion.ToString(CultureInfo.InvariantCulture) + ")" + trailingComma);
        }

        _ = sb.AppendLine("    };");
        _ = sb.AppendLine("}");

        return new ManifestEmissionResult(sb.ToString(), duplicateDiagnostics.ToImmutable());
    }

    private static int CompareMarkers(ProjectionTemplateMarkerInfo a, ProjectionTemplateMarkerInfo b) {
        int c = string.CompareOrdinal(a.ProjectionTypeFullName, b.ProjectionTypeFullName);
        if (c != 0) {
            return c;
        }

        // null role sorts before any specified role
        int aRoleRank = a.Role is null ? 0 : 1;
        int bRoleRank = b.Role is null ? 0 : 1;
        if (aRoleRank != bRoleRank) {
            return aRoleRank - bRoleRank;
        }

        c = string.CompareOrdinal(a.Role ?? string.Empty, b.Role ?? string.Empty);
        if (c != 0) {
            return c;
        }

        return string.CompareOrdinal(a.TemplateTypeFullName, b.TemplateTypeFullName);
    }
}
