using System.Globalization;
using System.Text;

using Hexalith.FrontComposer.SourceTools.Transforms;

namespace Hexalith.FrontComposer.SourceTools.Emitters;

/// <summary>
/// Story 4-1 T3 / ADR-052 — emits a projection view component that dispatches
/// to a strategy-specific body via <see cref="ProjectionRoleBodyEmitter"/>.
/// Shared scaffolding (using-directives, class header, formatters, Loading /
/// Empty shells, subtitle host) lives here as private helpers; strategy bodies
/// live in <see cref="ProjectionRoleBodyEmitter"/>. The dispatch uses a
/// switch-expression with a throwing default arm so the C# compiler enforces
/// exhaustive coverage — a future strategy added without a case fails the build.
/// </summary>
public static class RazorEmitter {
    /// <summary>
    /// Generates the full view component source for a projection. The emitted
    /// component has three rendered states (Loading / Empty / Data) plus a
    /// subtitle rendered above the body. The Data-state body is dispatched by
    /// <see cref="RazorModel.Strategy"/>.
    /// </summary>
    /// <param name="model">The transform-stage Razor output model.</param>
    /// <returns>The generated C# source for <c>{TypeName}View</c>.</returns>
    public static string Emit(RazorModel model) {
        StringBuilder sb = new(4096);

        EmitFileHeader(sb);
        EmitUsings(sb);
        EmitNamespaceOpening(sb, model);
        EmitClassHeader(sb, model);
        EmitInjections(sb, model);
        EmitStrategyMembers(sb, model);
        EmitLifecycleHooks(sb, model);
        EmitFormatters(sb);
        EmitBuildRenderTree(sb, model);
        EmitClassFooter(sb);

        return sb.ToString();
    }

    private static void EmitFileHeader(StringBuilder sb) {
        _ = sb.AppendLine("// Generated by FrontComposer source generator");
        _ = sb.AppendLine("// Do not edit directly");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
    }

    private static void EmitUsings(StringBuilder sb) {
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine("using System.Collections.Generic;");
        _ = sb.AppendLine("using System.Globalization;");
        _ = sb.AppendLine("using System.Linq;");
        _ = sb.AppendLine("using System.Linq.Expressions;");
        _ = sb.AppendLine("using Fluxor;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components.Rendering;");
        _ = sb.AppendLine("using Microsoft.FluentUI.AspNetCore.Components;");
        _ = sb.AppendLine();
    }

    private static void EmitNamespaceOpening(StringBuilder sb, RazorModel model) {
        if (!string.IsNullOrEmpty(model.Namespace)) {
            _ = sb.AppendLine("namespace " + model.Namespace + ";");
            _ = sb.AppendLine();
        }
    }

    private static void EmitClassHeader(StringBuilder sb, RazorModel model) {
        _ = sb.AppendLine("/// <summary>");
        _ = sb.AppendLine("/// Auto-generated DataGrid view for <see cref=\"" + model.TypeName + "\"/>.");
        _ = sb.AppendLine("/// </summary>");
        _ = sb.AppendLine("public partial class " + model.TypeName + "View : ComponentBase, IDisposable");
        _ = sb.AppendLine("{");
    }

    private static void EmitInjections(StringBuilder sb, RazorModel model) {
        _ = sb.AppendLine("    [Inject]");
        _ = sb.AppendLine("    private IState<" + model.TypeName + "State> " + model.TypeName + "State { get; set; } = default!;");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    [Inject]");
        _ = sb.AppendLine("    private NavigationManager Navigation { get; set; } = default!;");
        _ = sb.AppendLine();
    }

    private static void EmitStrategyMembers(StringBuilder sb, RazorModel model) {
        if (model.Strategy == ProjectionRenderStrategy.ActionQueue) {
            _ = sb.AppendLine("    private object? _cachedActionQueueSource;");
            _ = sb.AppendLine("    private List<" + model.TypeName + ">? _cachedActionQueueItems;");
            _ = sb.AppendLine();
        }
        else if (model.Strategy == ProjectionRenderStrategy.StatusOverview) {
            _ = sb.AppendLine("    private sealed record " + model.TypeName + "StatusOverviewRow(Enum? Status, string StatusLabel, int Count, long SortOrder);");
            _ = sb.AppendLine();
            EmitStatusOverviewSortHelper(sb, model);
        }
    }

    private static void EmitStatusOverviewSortHelper(StringBuilder sb, RazorModel model) {
        ColumnModel? statusColumn = RoleBodyHelpers.ResolveStatusEnumColumn(model);

        _ = sb.AppendLine("    private static long GetEnumSortOrder(Enum? value)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (value is null)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return long.MaxValue;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();

        if (statusColumn is not null && statusColumn.EnumMemberNames.Count > 0) {
            _ = sb.AppendLine("        return value.ToString() switch");
            _ = sb.AppendLine("        {");
            for (int i = 0; i < statusColumn.EnumMemberNames.Count; i++) {
                string memberName = RoleBodyHelpers.EscapeString(statusColumn.EnumMemberNames[i]);
                _ = sb.AppendLine("            \"" + memberName + "\" => " + i.ToString(CultureInfo.InvariantCulture) + "L,");
            }

            _ = sb.AppendLine("            _ => long.MaxValue - 1,");
            _ = sb.AppendLine("        };");
        }
        else {
            _ = sb.AppendLine("        return long.MaxValue - 1;");
        }

        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
    }

    private static void EmitLifecycleHooks(StringBuilder sb, RazorModel model) {
        _ = sb.AppendLine("    /// <inheritdoc />");
        _ = sb.AppendLine("    protected override void OnInitialized()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        " + model.TypeName + "State.StateChanged += OnStateChanged;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private void OnStateChanged(object? sender, EventArgs e)");
        _ = sb.AppendLine("        => InvokeAsync(StateHasChanged);");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    /// <inheritdoc />");
        _ = sb.AppendLine("    public void Dispose()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        " + model.TypeName + "State.StateChanged -= OnStateChanged;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
    }

    private static void EmitFormatters(StringBuilder sb) {
        _ = sb.AppendLine("    private static string Truncate(string value, int maxLength)");
        _ = sb.AppendLine("        => value.Length <= maxLength ? value : value.Substring(0, maxLength - 1) + \"\\u2026\";");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private static string HumanizeEnumLabel(string value)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (string.IsNullOrEmpty(value))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return value;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        var sb = new System.Text.StringBuilder(value.Length + 10);");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        for (int i = 0; i < value.Length; i++)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            char c = value[i];");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            if (i == 0)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                sb.Append(char.ToUpperInvariant(c));");
        _ = sb.AppendLine("                continue;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            bool isUpper = c >= 'A' && c <= 'Z';");
        _ = sb.AppendLine("            bool prevIsUpper = value[i - 1] >= 'A' && value[i - 1] <= 'Z';");
        _ = sb.AppendLine("            bool prevIsLower = value[i - 1] >= 'a' && value[i - 1] <= 'z';");
        _ = sb.AppendLine("            bool prevIsDigit = value[i - 1] >= '0' && value[i - 1] <= '9';");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            if (isUpper && prevIsLower)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                sb.Append(' ');");
        _ = sb.AppendLine("                sb.Append(c);");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("            else if (isUpper && prevIsUpper && i + 1 < value.Length)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                char next = value[i + 1];");
        _ = sb.AppendLine("                bool nextIsLower = next >= 'a' && next <= 'z';");
        _ = sb.AppendLine("                if (nextIsLower && CountConsecutiveUppersBefore(value, i) + 1 >= 3)");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    sb.Append(' ');");
        _ = sb.AppendLine("                }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("                sb.Append(c);");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("            else if (isUpper && prevIsDigit)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                sb.Append(' ');");
        _ = sb.AppendLine("                sb.Append(c);");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("            else");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                sb.Append(c);");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        return sb.ToString();");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private static int CountConsecutiveUppersBefore(string value, int index)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        int count = 0;");
        _ = sb.AppendLine("        for (int i = index - 1; i >= 0; i--)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            if (value[i] >= 'A' && value[i] <= 'Z')");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                count++;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("            else");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                break;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        return count;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
    }

    private static void EmitBuildRenderTree(StringBuilder sb, RazorModel model) {
        _ = sb.AppendLine("    /// <inheritdoc />");
        _ = sb.AppendLine("    protected override void BuildRenderTree(RenderTreeBuilder builder)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        var state = " + model.TypeName + "State.Value;");
        _ = sb.AppendLine("        int seq = 0;");
        _ = sb.AppendLine();

        EmitSubtitleInvocation(sb, model);
        EmitLoadingShell(sb, model);
        EmitEmptyShell(sb, model);

        _ = sb.AppendLine("        seq = 100;");
        DispatchBody(sb, model);

        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");
    }

    /// <summary>
    /// Story 4-1 T3.1 / D8 / AC6 — subtitle emitted ABOVE every strategy body.
    /// Uses nullable-DI <c>IBadgeCountService</c> internally; here we only emit
    /// the component invocation + the cascading <c>SubtitleFallbackCount</c> from
    /// the current state item count so adopters without the badge service still
    /// see a meaningful count. The subtitle host is outside any per-row cascade
    /// (Story 4-1 FMA round 3 — prevents subtitle re-render per row).
    /// </summary>
    internal static void EmitSubtitleInvocation(StringBuilder sb, RazorModel model) {
        string whenStateLiteral = model.WhenStates.Count == 0
            ? "(string?)null"
            : "\"" + RoleBodyHelpers.EscapeString(string.Join(",", model.WhenStates)) + "\"";
        string roleLiteral = model.Strategy == ProjectionRenderStrategy.Default
            ? "(" + ProjectionRoleBodyEmitter.ContractsAttributesNamespace + ".ProjectionRole?)null"
            : "(" + ProjectionRoleBodyEmitter.ContractsAttributesNamespace + ".ProjectionRole?)"
                + ProjectionRoleBodyEmitter.ContractsAttributesNamespace + ".ProjectionRole." + model.Strategy.ToString();
        string fallbackCountExpression = ResolveSubtitleFallbackCountExpression(model);
        string distinctStatusCountExpression = ResolveDistinctStatusCountExpression(model);
        string entityLabelLiteral = "\"" + RoleBodyHelpers.EscapeString(ResolveEntityLabel(model)) + "\"";
        string entityPluralLabelLiteral = "\"" + RoleBodyHelpers.EscapeString(ResolveEntityPluralLabel(model)) + "\"";

        _ = sb.AppendLine("        builder.OpenComponent<" + ProjectionRoleBodyEmitter.ShellRenderingNamespace + ".FcProjectionSubtitle>(seq++);");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"ProjectionType\", typeof(" + model.TypeName + "));");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"Role\", " + roleLiteral + ");");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"WhenState\", " + whenStateLiteral + ");");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"FallbackCount\", " + fallbackCountExpression + ");");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"DistinctStatusCount\", " + distinctStatusCountExpression + ");");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"EntityLabel\", " + entityLabelLiteral + ");");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"EntityPluralLabel\", " + entityPluralLabelLiteral + ");");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"IsLoading\", state.IsLoading);");
        _ = sb.AppendLine("        builder.CloseComponent();");
        _ = sb.AppendLine();
    }

    private static string ResolveSubtitleFallbackCountExpression(RazorModel model) {
        if (model.Strategy != ProjectionRenderStrategy.ActionQueue) {
            return "state.Items?.Count ?? 0";
        }

        string? predicate = RoleBodyHelpers.ResolveWhenStateFilterPredicate(model);
        return predicate is null
            ? "state.Items?.Count ?? 0"
            : "state.Items is null ? 0 : state.Items.Count(x => " + predicate + ")";
    }

    private static string ResolveDistinctStatusCountExpression(RazorModel model) {
        if (model.Strategy != ProjectionRenderStrategy.StatusOverview) {
            return "(int?)null";
        }

        string? statusProperty = RoleBodyHelpers.ResolveStatusEnumProperty(model);
        return statusProperty is null
            ? "(int?)null"
            : "state.Items is null ? (int?)null : state.Items.Select(x => x." + statusProperty + ").Distinct().Count()";
    }

    private static string ResolveEntityLabel(RazorModel model) {
        if (!string.IsNullOrWhiteSpace(model.EntityLabel)) {
            return model.EntityLabel!;
        }

        return HumanizeTypeName(model.TypeName);
    }

    private static string ResolveEntityPluralLabel(RazorModel model) {
        if (!string.IsNullOrWhiteSpace(model.EntityPluralLabel)) {
            return model.EntityPluralLabel!;
        }

        string label = HumanizeTypeName(model.TypeName).ToLowerInvariant();
        return label.EndsWith("s", StringComparison.Ordinal) ? label : label + "s";
    }

    private static string HumanizeTypeName(string typeName) {
        const string projectionSuffix = "Projection";
        string baseName = typeName.EndsWith(projectionSuffix, StringComparison.Ordinal)
            ? typeName.Substring(0, typeName.Length - projectionSuffix.Length)
            : typeName;

        if (string.IsNullOrEmpty(baseName)) {
            return typeName;
        }

        StringBuilder sb = new(baseName.Length + 4);
        for (int i = 0; i < baseName.Length; i++) {
            char c = baseName[i];
            if (i > 0 && char.IsUpper(c) && !char.IsUpper(baseName[i - 1])) {
                _ = sb.Append(' ');
            }

            _ = sb.Append(c);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Story 4-1 T3.1 / D6 / AC8 — Loading shell renders a role-aware
    /// <c>FcProjectionLoadingSkeleton</c>. Column count is capped at 8 to match
    /// Story 4.4 column-prioritizer defaults. Short-circuits BuildRenderTree via
    /// <c>return</c> when <c>state.IsLoading</c>.
    /// </summary>
    internal static void EmitLoadingShell(StringBuilder sb, RazorModel model) {
        int columnCount = Math.Min(model.Columns.Count, 8);
        string layout = ResolveSkeletonLayout(model.Strategy);
        string entityLabelLiteral = "\"" + RoleBodyHelpers.EscapeString(ResolveEntityPluralLabel(model)) + "\"";

        _ = sb.AppendLine("        if (state.IsLoading)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            builder.OpenComponent<" + ProjectionRoleBodyEmitter.ShellRenderingNamespace + ".FcProjectionLoadingSkeleton>(seq++);");
        _ = sb.AppendLine("            builder.AddAttribute(seq++, \"ColumnCount\", " + columnCount + ");");
        _ = sb.AppendLine("            builder.AddAttribute(seq++, \"RowCount\", 5);");
        _ = sb.AppendLine("            builder.AddAttribute(seq++, \"Layout\", " + ProjectionRoleBodyEmitter.ShellRenderingNamespace + ".SkeletonLayout." + layout + ");");
        _ = sb.AppendLine("            builder.AddAttribute(seq++, \"EntityLabel\", " + entityLabelLiteral + ");");
        _ = sb.AppendLine("            builder.CloseComponent();");
        _ = sb.AppendLine("            return;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
    }

    /// <summary>
    /// Story 4-1 T3.1 / D7 / AC8 / H4 — Empty shell invokes
    /// <c>FcProjectionEmptyPlaceholder</c> and always passes the <c>Role</c>
    /// parameter so Story 4.6 can consume it for role-differentiated CTA copy
    /// without forcing generator re-emission (H4).
    /// </summary>
    internal static void EmitEmptyShell(StringBuilder sb, RazorModel model) {
        string roleLiteral = model.Strategy == ProjectionRenderStrategy.Default
            ? "(" + ProjectionRoleBodyEmitter.ContractsAttributesNamespace + ".ProjectionRole?)null"
            : "(" + ProjectionRoleBodyEmitter.ContractsAttributesNamespace + ".ProjectionRole?)"
                + ProjectionRoleBodyEmitter.ContractsAttributesNamespace + ".ProjectionRole." + model.Strategy.ToString();

        _ = sb.AppendLine("        if (state.Items is null || state.Items.Count == 0)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            builder.OpenComponent<" + ProjectionRoleBodyEmitter.ShellRenderingNamespace + ".FcProjectionEmptyPlaceholder>(seq++);");
        _ = sb.AppendLine("            builder.AddAttribute(seq++, \"ProjectionType\", typeof(" + model.TypeName + "));");
        _ = sb.AppendLine("            builder.AddAttribute(seq++, \"Role\", " + roleLiteral + ");");
        _ = sb.AppendLine("            builder.CloseComponent();");
        _ = sb.AppendLine("            return;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
    }

    /// <summary>
    /// Story 4-1 T3.9 / ADR-052 — strategy dispatch. Switch-expression with
    /// throwing default arm guarantees exhaustive coverage at build time:
    /// adding a new member to <see cref="ProjectionRenderStrategy"/> without
    /// updating this switch produces a compile error.
    /// </summary>
    private static void DispatchBody(StringBuilder sb, RazorModel model) {
        Action<StringBuilder, RazorModel> bodyEmitter = model.Strategy switch {
            ProjectionRenderStrategy.Default => ProjectionRoleBodyEmitter.EmitDefaultBody,
            ProjectionRenderStrategy.ActionQueue => ProjectionRoleBodyEmitter.EmitActionQueueBody,
            ProjectionRenderStrategy.StatusOverview => ProjectionRoleBodyEmitter.EmitStatusOverviewBody,
            ProjectionRenderStrategy.DetailRecord => ProjectionRoleBodyEmitter.EmitDetailRecordBody,
            ProjectionRenderStrategy.Timeline => ProjectionRoleBodyEmitter.EmitTimelineBody,
            ProjectionRenderStrategy.Dashboard => ProjectionRoleBodyEmitter.EmitDashboardBody,
            _ => throw new InvalidOperationException(
                "Unhandled ProjectionRenderStrategy: " + model.Strategy +
                ". Add a case to RazorEmitter.DispatchBody."),
        };

        bodyEmitter(sb, model);
    }

    private static void EmitClassFooter(StringBuilder sb) {
        // Class + BuildRenderTree already closed in EmitBuildRenderTree.
    }

    private static string ResolveSkeletonLayout(ProjectionRenderStrategy strategy) =>
        strategy switch {
            ProjectionRenderStrategy.DetailRecord => "Card",
            ProjectionRenderStrategy.Timeline => "Timeline",
            _ => "DataGrid",
        };
}
