#nullable enable

namespace Hexalith.FrontComposer.SourceTools.Emitters;

using System.Text;

using Hexalith.FrontComposer.SourceTools.Transforms;

/// <summary>
/// Emits a Razor DataGrid partial class from a RazorModel.
/// </summary>
public static class RazorEmitter
{
    /// <summary>
    /// Generates the source code for a DataGrid Razor component.
    /// </summary>
    /// <param name="model">The Razor output model.</param>
    /// <returns>The generated C# source code string.</returns>
    public static string Emit(RazorModel model)
    {
        StringBuilder sb = new StringBuilder(2048);

        sb.AppendLine("// Generated by FrontComposer source generator");
        sb.AppendLine("// Do not edit directly");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Linq.Expressions;");
        sb.AppendLine("using Fluxor;");
        sb.AppendLine("using Microsoft.AspNetCore.Components;");
        sb.AppendLine("using Microsoft.AspNetCore.Components.Rendering;");
        sb.AppendLine("using Microsoft.FluentUI.AspNetCore.Components;");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine("namespace " + model.Namespace + ";");
            sb.AppendLine();
        }

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated DataGrid view for <see cref=\"" + model.TypeName + "\"/>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public partial class " + model.TypeName + "View : ComponentBase, IDisposable");
        sb.AppendLine("{");

        // Inject state
        sb.AppendLine("    [Inject]");
        sb.AppendLine("    private IState<" + model.TypeName + "State> " + model.TypeName + "State { get; set; } = default!;");
        sb.AppendLine();

        // OnInitialized
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    protected override void OnInitialized()");
        sb.AppendLine("    {");
        sb.AppendLine("        " + model.TypeName + "State.StateChanged += OnStateChanged;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // OnStateChanged
        sb.AppendLine("    private void OnStateChanged(object? sender, EventArgs e)");
        sb.AppendLine("        => InvokeAsync(StateHasChanged);");
        sb.AppendLine();

        // Dispose
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    public void Dispose()");
        sb.AppendLine("    {");
        sb.AppendLine("        " + model.TypeName + "State.StateChanged -= OnStateChanged;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Formatting helpers
        sb.AppendLine("    private static string Truncate(string value, int maxLength)");
        sb.AppendLine("        => value.Length <= maxLength ? value : value.Substring(0, maxLength - 1) + \"\\u2026\";");
        sb.AppendLine();
        sb.AppendLine("    private static string HumanizeEnumLabel(string value)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (string.IsNullOrEmpty(value))");
        sb.AppendLine("        {");
        sb.AppendLine("            return value;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var sb = new System.Text.StringBuilder(value.Length + 10);");
        sb.AppendLine();
        sb.AppendLine("        for (int i = 0; i < value.Length; i++)");
        sb.AppendLine("        {");
        sb.AppendLine("            char c = value[i];");
        sb.AppendLine();
        sb.AppendLine("            if (i == 0)");
        sb.AppendLine("            {");
        sb.AppendLine("                sb.Append(char.ToUpperInvariant(c));");
        sb.AppendLine("                continue;");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            bool isUpper = c >= 'A' && c <= 'Z';");
        sb.AppendLine("            bool prevIsUpper = value[i - 1] >= 'A' && value[i - 1] <= 'Z';");
        sb.AppendLine("            bool prevIsLower = value[i - 1] >= 'a' && value[i - 1] <= 'z';");
        sb.AppendLine("            bool prevIsDigit = value[i - 1] >= '0' && value[i - 1] <= '9';");
        sb.AppendLine();
        sb.AppendLine("            if (isUpper && prevIsLower)");
        sb.AppendLine("            {");
        sb.AppendLine("                sb.Append(' ');");
        sb.AppendLine("                sb.Append(c);");
        sb.AppendLine("            }");
        sb.AppendLine("            else if (isUpper && prevIsUpper && i + 1 < value.Length)");
        sb.AppendLine("            {");
        sb.AppendLine("                char next = value[i + 1];");
        sb.AppendLine("                bool nextIsLower = next >= 'a' && next <= 'z';");
        sb.AppendLine("                if (nextIsLower && CountConsecutiveUppersBefore(value, i) + 1 >= 3)");
        sb.AppendLine("                {");
        sb.AppendLine("                    sb.Append(' ');");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.AppendLine("                sb.Append(c);");
        sb.AppendLine("            }");
        sb.AppendLine("            else if (isUpper && prevIsDigit)");
        sb.AppendLine("            {");
        sb.AppendLine("                sb.Append(' ');");
        sb.AppendLine("                sb.Append(c);");
        sb.AppendLine("            }");
        sb.AppendLine("            else");
        sb.AppendLine("            {");
        sb.AppendLine("                sb.Append(c);");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return sb.ToString();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static int CountConsecutiveUppersBefore(string value, int index)");
        sb.AppendLine("    {");
        sb.AppendLine("        int count = 0;");
        sb.AppendLine("        for (int i = index - 1; i >= 0; i--)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (value[i] >= 'A' && value[i] <= 'Z')");
        sb.AppendLine("            {");
        sb.AppendLine("                count++;");
        sb.AppendLine("            }");
        sb.AppendLine("            else");
        sb.AppendLine("            {");
        sb.AppendLine("                break;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return count;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // BuildRenderTree
        sb.AppendLine("    /// <inheritdoc />");
        sb.AppendLine("    protected override void BuildRenderTree(RenderTreeBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        var state = " + model.TypeName + "State.Value;");
        sb.AppendLine();

        // Loading state
        sb.AppendLine("        if (state.IsLoading)");
        sb.AppendLine("        {");
        sb.AppendLine("            builder.OpenElement(0, \"div\");");
        sb.AppendLine("            builder.AddAttribute(1, \"class\", \"fc-loading-skeleton\");");
        sb.AppendLine("            builder.AddContent(2, \"Loading...\");");
        sb.AppendLine("            builder.CloseElement();");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // Empty state
        sb.AppendLine("        if (state.Items is null || state.Items.Count == 0)");
        sb.AppendLine("        {");
        sb.AppendLine("            builder.OpenElement(3, \"div\");");
        sb.AppendLine("            builder.AddAttribute(4, \"class\", \"fc-empty-state\");");
        string emptyContent = model.Columns.Count == 0
            ? "No data columns available"
            : "No data available";
        sb.AppendLine("            builder.AddContent(5, \"" + emptyContent + "\");");

        sb.AppendLine("            builder.CloseElement();");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine();

        // DataGrid
        sb.AppendLine("        int seq = 100;");
        sb.AppendLine("        builder.OpenComponent<FluentDataGrid<" + model.TypeName + ">>(seq++);");
        sb.AppendLine("        builder.AddAttribute(seq++, \"Items\", state.Items.AsQueryable());");
        sb.AppendLine();

        // Column rendering -- ChildContent is RenderFragment (not RenderFragment<T>)
        sb.AppendLine("        builder.AddAttribute(seq++, \"ChildContent\", (RenderFragment)((RenderTreeBuilder b) =>");
        sb.AppendLine("        {");
        sb.AppendLine("            int colSeq = 200;");

        foreach (ColumnModel col in model.Columns)
        {
            sb.AppendLine();
            EmitColumn(sb, col, model.TypeName);
        }

        sb.AppendLine("        }));");
        sb.AppendLine();

        // TODO: Badge rendering placeholder
        sb.AppendLine("        // TODO: Badge rendering (Story 2.x)");
        sb.AppendLine();

        sb.AppendLine("        builder.CloseComponent();");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitColumn(StringBuilder sb, ColumnModel col, string typeName)
    {
        switch (col.TypeCategory)
        {
            case TypeCategory.Text:
                EmitTextColumn(sb, col, typeName);
                break;
            case TypeCategory.Numeric:
                EmitNumericColumn(sb, col, typeName);
                break;
            case TypeCategory.Boolean:
                EmitBooleanColumn(sb, col, typeName);
                break;
            case TypeCategory.DateTime:
                EmitDateTimeColumn(sb, col, typeName);
                break;
            case TypeCategory.Enum:
                EmitEnumColumn(sb, col, typeName);
                break;
            case TypeCategory.Collection:
                EmitCollectionColumn(sb, col, typeName);
                break;
        }
    }

    private static void EmitTextColumn(StringBuilder sb, ColumnModel col, string typeName)
    {
        string formatHint = col.FormatHint ?? string.Empty;

        if (formatHint.StartsWith("Truncate:", System.StringComparison.Ordinal))
        {
            // Guid truncation
            string length = formatHint.Substring("Truncate:".Length);
            sb.AppendLine("            // Guid column: " + col.PropertyName);
            sb.AppendLine("            b.OpenComponent<PropertyColumn<" + typeName + ", string?>>(colSeq++);");
            sb.AppendLine("            b.AddAttribute(colSeq++, \"Title\", \"" + EscapeString(col.Header) + "\");");

            if (col.IsNullable)
            {
                sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + " == null ? \"\\u2014\" : x." + col.PropertyName + ".Value.ToString(\"N\").Substring(0, " + length + ")));");
            }
            else
            {
                sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + ".ToString(\"N\").Substring(0, " + length + ")));");
            }

            sb.AppendLine("            b.CloseComponent();");
        }
        else
        {
            // Standard text column
            sb.AppendLine("            // Text column: " + col.PropertyName);
            sb.AppendLine("            b.OpenComponent<PropertyColumn<" + typeName + ", string?>>(colSeq++);");
            sb.AppendLine("            b.AddAttribute(colSeq++, \"Title\", \"" + EscapeString(col.Header) + "\");");
            sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + " ?? \"\\u2014\"));");
            sb.AppendLine("            b.CloseComponent();");
        }
    }

    private static void EmitNumericColumn(StringBuilder sb, ColumnModel col, string typeName)
    {
        string format = col.FormatHint ?? "N0";
        sb.AppendLine("            // Numeric column: " + col.PropertyName);
        sb.AppendLine("            b.OpenComponent<PropertyColumn<" + typeName + ", string?>>(colSeq++);");
        sb.AppendLine("            b.AddAttribute(colSeq++, \"Title\", \"" + EscapeString(col.Header) + "\");");

        if (col.IsNullable)
        {
            sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + ".HasValue ? x." + col.PropertyName + ".Value.ToString(\"" + format + "\", CultureInfo.CurrentCulture) : \"\\u2014\"));");
        }
        else
        {
            sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + ".ToString(\"" + format + "\", CultureInfo.CurrentCulture)));");
        }

        sb.AppendLine("            b.AddAttribute(colSeq++, \"Class\", \"fc-col-numeric\");");
        sb.AppendLine("            b.CloseComponent();");
    }

    private static void EmitBooleanColumn(StringBuilder sb, ColumnModel col, string typeName)
    {
        sb.AppendLine("            // Boolean column: " + col.PropertyName);
        sb.AppendLine("            b.OpenComponent<PropertyColumn<" + typeName + ", string?>>(colSeq++);");
        sb.AppendLine("            b.AddAttribute(colSeq++, \"Title\", \"" + EscapeString(col.Header) + "\");");

        if (col.IsNullable)
        {
            sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + ".HasValue ? (x." + col.PropertyName + ".Value ? \"Yes\" : \"No\") : \"\\u2014\"));");
        }
        else
        {
            sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + " ? \"Yes\" : \"No\"));");
        }

        sb.AppendLine("            b.CloseComponent();");
    }

    private static void EmitDateTimeColumn(StringBuilder sb, ColumnModel col, string typeName)
    {
        string format = col.FormatHint ?? "d";
        sb.AppendLine("            // DateTime column: " + col.PropertyName);
        sb.AppendLine("            b.OpenComponent<PropertyColumn<" + typeName + ", string?>>(colSeq++);");
        sb.AppendLine("            b.AddAttribute(colSeq++, \"Title\", \"" + EscapeString(col.Header) + "\");");

        if (col.IsNullable)
        {
            sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + ".HasValue ? x." + col.PropertyName + ".Value.ToString(\"" + format + "\", CultureInfo.CurrentCulture) : \"\\u2014\"));");
        }
        else
        {
            sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + ".ToString(\"" + format + "\", CultureInfo.CurrentCulture)));");
        }

        sb.AppendLine("            b.CloseComponent();");
    }

    private static void EmitEnumColumn(StringBuilder sb, ColumnModel col, string typeName)
    {
        sb.AppendLine("            // Enum column: " + col.PropertyName);
        sb.AppendLine("            b.OpenComponent<PropertyColumn<" + typeName + ", string?>>(colSeq++);");
        sb.AppendLine("            b.AddAttribute(colSeq++, \"Title\", \"" + EscapeString(col.Header) + "\");");

        if (col.IsNullable)
        {
            sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + ".HasValue ? Truncate(HumanizeEnumLabel(x." + col.PropertyName + ".Value.ToString()), 30) : \"\\u2014\"));");
        }
        else
        {
            sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => Truncate(HumanizeEnumLabel(x." + col.PropertyName + ".ToString()), 30)));");
        }

        sb.AppendLine("            b.CloseComponent();");
    }

    private static void EmitCollectionColumn(StringBuilder sb, ColumnModel col, string typeName)
    {
        sb.AppendLine("            // Collection column: " + col.PropertyName);
        sb.AppendLine("            b.OpenComponent<PropertyColumn<" + typeName + ", string?>>(colSeq++);");
        sb.AppendLine("            b.AddAttribute(colSeq++, \"Title\", \"" + EscapeString(col.Header) + "\");");
        sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + " == null ? \"\\u2014\" : System.Linq.Enumerable.Count(x." + col.PropertyName + ").ToString() + \" items\"));");
        sb.AppendLine("            b.CloseComponent();");
    }

    private static string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
