
using System.Text;

using Hexalith.FrontComposer.SourceTools.Transforms;

namespace Hexalith.FrontComposer.SourceTools.Emitters;
/// <summary>
/// Emits a Razor DataGrid partial class from a RazorModel.
/// </summary>
public static class RazorEmitter {
    /// <summary>
    /// Generates the source code for a DataGrid Razor component.
    /// </summary>
    /// <param name="model">The Razor output model.</param>
    /// <returns>The generated C# source code string.</returns>
    public static string Emit(RazorModel model) {
        var sb = new StringBuilder(2048);

        _ = sb.AppendLine("// Generated by FrontComposer source generator");
        _ = sb.AppendLine("// Do not edit directly");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine("using System.Collections.Generic;");
        _ = sb.AppendLine("using System.Globalization;");
        _ = sb.AppendLine("using System.Linq;");
        _ = sb.AppendLine("using System.Linq.Expressions;");
        _ = sb.AppendLine("using Fluxor;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components;");
        _ = sb.AppendLine("using Microsoft.AspNetCore.Components.Rendering;");
        _ = sb.AppendLine("using Microsoft.FluentUI.AspNetCore.Components;");
        _ = sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace) {
            _ = sb.AppendLine("namespace " + model.Namespace + ";");
            _ = sb.AppendLine();
        }

        _ = sb.AppendLine("/// <summary>");
        _ = sb.AppendLine("/// Auto-generated DataGrid view for <see cref=\"" + model.TypeName + "\"/>.");
        _ = sb.AppendLine("/// </summary>");
        _ = sb.AppendLine("public partial class " + model.TypeName + "View : ComponentBase, IDisposable");
        _ = sb.AppendLine("{");

        // Inject state
        _ = sb.AppendLine("    [Inject]");
        _ = sb.AppendLine("    private IState<" + model.TypeName + "State> " + model.TypeName + "State { get; set; } = default!;");
        _ = sb.AppendLine();

        // OnInitialized
        _ = sb.AppendLine("    /// <inheritdoc />");
        _ = sb.AppendLine("    protected override void OnInitialized()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        " + model.TypeName + "State.StateChanged += OnStateChanged;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        // OnStateChanged
        _ = sb.AppendLine("    private void OnStateChanged(object? sender, EventArgs e)");
        _ = sb.AppendLine("        => InvokeAsync(StateHasChanged);");
        _ = sb.AppendLine();

        // Dispose
        _ = sb.AppendLine("    /// <inheritdoc />");
        _ = sb.AppendLine("    public void Dispose()");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        " + model.TypeName + "State.StateChanged -= OnStateChanged;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        // Formatting helpers
        _ = sb.AppendLine("    private static string Truncate(string value, int maxLength)");
        _ = sb.AppendLine("        => value.Length <= maxLength ? value : value.Substring(0, maxLength - 1) + \"\\u2026\";");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private static string HumanizeEnumLabel(string value)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        if (string.IsNullOrEmpty(value))");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            return value;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        var sb = new System.Text.StringBuilder(value.Length + 10);");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        for (int i = 0; i < value.Length; i++)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            char c = value[i];");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            if (i == 0)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                sb.Append(char.ToUpperInvariant(c));");
        _ = sb.AppendLine("                continue;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            bool isUpper = c >= 'A' && c <= 'Z';");
        _ = sb.AppendLine("            bool prevIsUpper = value[i - 1] >= 'A' && value[i - 1] <= 'Z';");
        _ = sb.AppendLine("            bool prevIsLower = value[i - 1] >= 'a' && value[i - 1] <= 'z';");
        _ = sb.AppendLine("            bool prevIsDigit = value[i - 1] >= '0' && value[i - 1] <= '9';");
        _ = sb.AppendLine();
        _ = sb.AppendLine("            if (isUpper && prevIsLower)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                sb.Append(' ');");
        _ = sb.AppendLine("                sb.Append(c);");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("            else if (isUpper && prevIsUpper && i + 1 < value.Length)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                char next = value[i + 1];");
        _ = sb.AppendLine("                bool nextIsLower = next >= 'a' && next <= 'z';");
        _ = sb.AppendLine("                if (nextIsLower && CountConsecutiveUppersBefore(value, i) + 1 >= 3)");
        _ = sb.AppendLine("                {");
        _ = sb.AppendLine("                    sb.Append(' ');");
        _ = sb.AppendLine("                }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("                sb.Append(c);");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("            else if (isUpper && prevIsDigit)");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                sb.Append(' ');");
        _ = sb.AppendLine("                sb.Append(c);");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("            else");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                sb.Append(c);");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        return sb.ToString();");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("    private static int CountConsecutiveUppersBefore(string value, int index)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        int count = 0;");
        _ = sb.AppendLine("        for (int i = index - 1; i >= 0; i--)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            if (value[i] >= 'A' && value[i] <= 'Z')");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                count++;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("            else");
        _ = sb.AppendLine("            {");
        _ = sb.AppendLine("                break;");
        _ = sb.AppendLine("            }");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();
        _ = sb.AppendLine("        return count;");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine();

        // BuildRenderTree
        _ = sb.AppendLine("    /// <inheritdoc />");
        _ = sb.AppendLine("    protected override void BuildRenderTree(RenderTreeBuilder builder)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        var state = " + model.TypeName + "State.Value;");
        _ = sb.AppendLine();

        // Loading state
        _ = sb.AppendLine("        if (state.IsLoading)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            builder.OpenElement(0, \"div\");");
        _ = sb.AppendLine("            builder.AddAttribute(1, \"class\", \"fc-loading-skeleton\");");
        _ = sb.AppendLine("            builder.AddContent(2, \"Loading...\");");
        _ = sb.AppendLine("            builder.CloseElement();");
        _ = sb.AppendLine("            return;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();

        // Empty state
        _ = sb.AppendLine("        if (state.Items is null || state.Items.Count == 0)");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            builder.OpenElement(3, \"div\");");
        _ = sb.AppendLine("            builder.AddAttribute(4, \"class\", \"fc-empty-state\");");
        string emptyContent = model.Columns.Count == 0
            ? "No data columns available"
            : "No data available";
        _ = sb.AppendLine("            builder.AddContent(5, \"" + emptyContent + "\");");

        _ = sb.AppendLine("            builder.CloseElement();");
        _ = sb.AppendLine("            return;");
        _ = sb.AppendLine("        }");
        _ = sb.AppendLine();

        // DataGrid
        _ = sb.AppendLine("        int seq = 100;");
        _ = sb.AppendLine("        builder.OpenComponent<FluentDataGrid<" + model.TypeName + ">>(seq++);");
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"Items\", state.Items.AsQueryable());");
        _ = sb.AppendLine();

        // Column rendering -- ChildContent is RenderFragment (not RenderFragment<T>)
        _ = sb.AppendLine("        builder.AddAttribute(seq++, \"ChildContent\", (RenderFragment)((RenderTreeBuilder b) =>");
        _ = sb.AppendLine("        {");
        _ = sb.AppendLine("            int colSeq = 200;");

        foreach (ColumnModel col in model.Columns) {
            _ = sb.AppendLine();
            EmitColumn(sb, col, model.TypeName);
        }

        _ = sb.AppendLine("        }));");
        _ = sb.AppendLine();

        // TODO: Badge rendering placeholder
        _ = sb.AppendLine("        // TODO: Badge rendering (Story 2.x)");
        _ = sb.AppendLine();

        _ = sb.AppendLine("        builder.CloseComponent();");
        _ = sb.AppendLine("    }");
        _ = sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitColumn(StringBuilder sb, ColumnModel col, string typeName) {
        switch (col.TypeCategory) {
            case TypeCategory.Text:
                EmitTextColumn(sb, col, typeName);
                break;
            case TypeCategory.Numeric:
                EmitNumericColumn(sb, col, typeName);
                break;
            case TypeCategory.Boolean:
                EmitBooleanColumn(sb, col, typeName);
                break;
            case TypeCategory.DateTime:
                EmitDateTimeColumn(sb, col, typeName);
                break;
            case TypeCategory.Enum:
                EmitEnumColumn(sb, col, typeName);
                break;
            case TypeCategory.Collection:
                EmitCollectionColumn(sb, col, typeName);
                break;
        }
    }

    private static void EmitTextColumn(StringBuilder sb, ColumnModel col, string typeName) {
        string formatHint = col.FormatHint ?? string.Empty;

        if (formatHint.StartsWith("Truncate:", System.StringComparison.Ordinal)) {
            // Guid truncation
            string length = formatHint.Substring("Truncate:".Length);
            _ = sb.AppendLine("            // Guid column: " + col.PropertyName);
            _ = sb.AppendLine("            b.OpenComponent<PropertyColumn<" + typeName + ", string?>>(colSeq++);");
            _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Title\", \"" + EscapeString(col.Header) + "\");");

            if (col.IsNullable) {
                _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + " == null ? \"\\u2014\" : x." + col.PropertyName + ".Value.ToString(\"N\").Substring(0, " + length + ")));");
            }
            else {
                _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + ".ToString(\"N\").Substring(0, " + length + ")));");
            }

            _ = sb.AppendLine("            b.CloseComponent();");
        }
        else {
            // Standard text column
            _ = sb.AppendLine("            // Text column: " + col.PropertyName);
            _ = sb.AppendLine("            b.OpenComponent<PropertyColumn<" + typeName + ", string?>>(colSeq++);");
            _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Title\", \"" + EscapeString(col.Header) + "\");");
            _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + " ?? \"\\u2014\"));");
            _ = sb.AppendLine("            b.CloseComponent();");
        }
    }

    private static void EmitNumericColumn(StringBuilder sb, ColumnModel col, string typeName) {
        string format = col.FormatHint ?? "N0";
        _ = sb.AppendLine("            // Numeric column: " + col.PropertyName);
        _ = sb.AppendLine("            b.OpenComponent<PropertyColumn<" + typeName + ", string?>>(colSeq++);");
        _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Title\", \"" + EscapeString(col.Header) + "\");");

        if (col.IsNullable) {
            _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + ".HasValue ? x." + col.PropertyName + ".Value.ToString(\"" + format + "\", CultureInfo.CurrentCulture) : \"\\u2014\"));");
        }
        else {
            _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + ".ToString(\"" + format + "\", CultureInfo.CurrentCulture)));");
        }

        _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Class\", \"fc-col-numeric\");");
        _ = sb.AppendLine("            b.CloseComponent();");
    }

    private static void EmitBooleanColumn(StringBuilder sb, ColumnModel col, string typeName) {
        _ = sb.AppendLine("            // Boolean column: " + col.PropertyName);
        _ = sb.AppendLine("            b.OpenComponent<PropertyColumn<" + typeName + ", string?>>(colSeq++);");
        _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Title\", \"" + EscapeString(col.Header) + "\");");

        if (col.IsNullable) {
            _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + ".HasValue ? (x." + col.PropertyName + ".Value ? \"Yes\" : \"No\") : \"\\u2014\"));");
        }
        else {
            _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + " ? \"Yes\" : \"No\"));");
        }

        _ = sb.AppendLine("            b.CloseComponent();");
    }

    private static void EmitDateTimeColumn(StringBuilder sb, ColumnModel col, string typeName) {
        string format = col.FormatHint ?? "d";
        _ = sb.AppendLine("            // DateTime column: " + col.PropertyName);
        _ = sb.AppendLine("            b.OpenComponent<PropertyColumn<" + typeName + ", string?>>(colSeq++);");
        _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Title\", \"" + EscapeString(col.Header) + "\");");

        if (col.IsNullable) {
            _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + ".HasValue ? x." + col.PropertyName + ".Value.ToString(\"" + format + "\", CultureInfo.CurrentCulture) : \"\\u2014\"));");
        }
        else {
            _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + ".ToString(\"" + format + "\", CultureInfo.CurrentCulture)));");
        }

        _ = sb.AppendLine("            b.CloseComponent();");
    }

    private static void EmitEnumColumn(StringBuilder sb, ColumnModel col, string typeName) {
        _ = sb.AppendLine("            // Enum column: " + col.PropertyName);
        _ = sb.AppendLine("            b.OpenComponent<PropertyColumn<" + typeName + ", string?>>(colSeq++);");
        _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Title\", \"" + EscapeString(col.Header) + "\");");

        if (col.IsNullable) {
            _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + ".HasValue ? Truncate(HumanizeEnumLabel(x." + col.PropertyName + ".Value.ToString()), 30) : \"\\u2014\"));");
        }
        else {
            _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => Truncate(HumanizeEnumLabel(x." + col.PropertyName + ".ToString()), 30)));");
        }

        _ = sb.AppendLine("            b.CloseComponent();");
    }

    private static void EmitCollectionColumn(StringBuilder sb, ColumnModel col, string typeName) {
        _ = sb.AppendLine("            // Collection column: " + col.PropertyName);
        _ = sb.AppendLine("            b.OpenComponent<PropertyColumn<" + typeName + ", string?>>(colSeq++);");
        _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Title\", \"" + EscapeString(col.Header) + "\");");
        _ = sb.AppendLine("            b.AddAttribute(colSeq++, \"Property\", (Expression<Func<" + typeName + ", string?>>)(x => x." + col.PropertyName + " == null ? \"\\u2014\" : System.Linq.Enumerable.Count(x." + col.PropertyName + ").ToString() + \" items\"));");
        _ = sb.AppendLine("            b.CloseComponent();");
    }

    private static string EscapeString(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
