#nullable enable

namespace Hexalith.FrontComposer.SourceTools.Emitters;

using System.Text;

using Hexalith.FrontComposer.SourceTools.Transforms;

/// <summary>
/// Emits domain registration partial class source code from a RegistrationModel.
/// Each projection contributes its own partial class member -- Roslyn merges them at compile time.
/// </summary>
public static class RegistrationEmitter
{
    /// <summary>
    /// Generates the Registration partial class source code for a single projection.
    /// </summary>
    /// <param name="model">The registration output model.</param>
    /// <returns>The generated C# source code string.</returns>
    public static string Emit(RegistrationModel model)
    {
        StringBuilder sb = new StringBuilder(512);

        sb.AppendLine("// Generated by FrontComposer source generator");
        sb.AppendLine("// Do not edit directly");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine("namespace " + model.Namespace + ";");
            sb.AppendLine();
        }

        string className = model.BoundedContext + "DomainRegistration";

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Domain registration for the \"" + model.BoundedContext + "\" bounded context.");
        sb.AppendLine("/// This partial class contribution registers <see cref=\"" + model.TypeName + "\"/>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static partial class " + className);
        sb.AppendLine("{");

        // Display label
        if (model.DisplayLabel is not null)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Gets the display label for the \"" + model.BoundedContext + "\" bounded context.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static string " + model.TypeName + "DisplayLabel => \"" + EscapeString(model.DisplayLabel) + "\";");
            sb.AppendLine();
        }

        // Registration method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the projection type name for <see cref=\"" + model.TypeName + "\"/>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static string " + model.TypeName + "ProjectionName => nameof(" + model.TypeName + ");");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
