
using System.Text;

using Hexalith.FrontComposer.SourceTools.Transforms;

namespace Hexalith.FrontComposer.SourceTools.Emitters;
/// <summary>
/// Emits per-type domain registration source code from a RegistrationModel.
/// Each projection gets its own Registration class with a DomainManifest Manifest
/// member and a RegisterDomain(IFrontComposerRegistry) method.
/// </summary>
public static class RegistrationEmitter {
    /// <summary>
    /// Generates the Registration class source code for a single projection.
    /// </summary>
    /// <param name="model">The registration output model.</param>
    /// <returns>The generated C# source code string.</returns>
    public static string Emit(RegistrationModel model) {
        var sb = new StringBuilder(1024);

        _ = sb.AppendLine("// Generated by FrontComposer source generator");
        _ = sb.AppendLine("// Do not edit directly");
        _ = sb.AppendLine();
        _ = sb.AppendLine("#nullable enable");
        _ = sb.AppendLine();
        _ = sb.AppendLine("using System.Collections.Generic;");
        _ = sb.AppendLine("using Hexalith.FrontComposer.Contracts.Registration;");
        _ = sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace) {
            _ = sb.AppendLine("namespace " + model.Namespace + ";");
            _ = sb.AppendLine();
        }

        string className = model.TypeName + "Registration";
        string displayName = model.DisplayLabel ?? model.BoundedContext;

        _ = sb.AppendLine("/// <summary>");
        _ = sb.AppendLine("/// Domain registration for <see cref=\"" + model.TypeName + "\"/> in the \"" + model.BoundedContext + "\" bounded context.");
        _ = sb.AppendLine("/// </summary>");
        _ = sb.AppendLine("public static class " + className);
        _ = sb.AppendLine("{");

        // Manifest member
        _ = sb.AppendLine("    /// <summary>");
        _ = sb.AppendLine("    /// Gets the domain manifest describing this projection's bounded context.");
        _ = sb.AppendLine("    /// </summary>");
        _ = sb.AppendLine("    public static DomainManifest Manifest { get; } = new DomainManifest(");
        _ = sb.AppendLine("        Name: \"" + EscapeString(displayName) + "\",");
        _ = sb.AppendLine("        BoundedContext: \"" + EscapeString(model.BoundedContext) + "\",");
        _ = sb.AppendLine("        Projections: new List<string> { typeof(" + model.TypeName + ").FullName! },");
        _ = sb.AppendLine("        Commands: new List<string>());");
        _ = sb.AppendLine();

        // RegisterDomain method
        _ = sb.AppendLine("    /// <summary>");
        _ = sb.AppendLine("    /// Registers this projection's domain metadata with the composition registry.");
        _ = sb.AppendLine("    /// </summary>");
        _ = sb.AppendLine("    /// <param name=\"registry\">The front composer registry.</param>");
        _ = sb.AppendLine("    public static void RegisterDomain(IFrontComposerRegistry registry)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        registry.RegisterDomain(Manifest);");
        _ = sb.AppendLine("    }");

        _ = sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EscapeString(string value) => value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t")
            .Replace("\0", "\\0");
}
