#nullable enable

namespace Hexalith.FrontComposer.SourceTools.Emitters;

using System.Text;

using Hexalith.FrontComposer.SourceTools.Transforms;

/// <summary>
/// Emits per-type domain registration source code from a RegistrationModel.
/// Each projection gets its own Registration class with a DomainManifest Manifest
/// member and a RegisterDomain(IFrontComposerRegistry) method.
/// </summary>
public static class RegistrationEmitter
{
    /// <summary>
    /// Generates the Registration class source code for a single projection.
    /// </summary>
    /// <param name="model">The registration output model.</param>
    /// <returns>The generated C# source code string.</returns>
    public static string Emit(RegistrationModel model)
    {
        StringBuilder sb = new StringBuilder(1024);

        sb.AppendLine("// Generated by FrontComposer source generator");
        sb.AppendLine("// Do not edit directly");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Hexalith.FrontComposer.Contracts.Registration;");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        if (hasNamespace)
        {
            sb.AppendLine("namespace " + model.Namespace + ";");
            sb.AppendLine();
        }

        string className = model.TypeName + "Registration";
        string displayName = model.DisplayLabel ?? model.BoundedContext;

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Domain registration for <see cref=\"" + model.TypeName + "\"/> in the \"" + model.BoundedContext + "\" bounded context.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class " + className);
        sb.AppendLine("{");

        // Manifest member
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the domain manifest describing this projection's bounded context.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static DomainManifest Manifest { get; } = new DomainManifest(");
        sb.AppendLine("        Name: \"" + EscapeString(displayName) + "\",");
        sb.AppendLine("        BoundedContext: \"" + EscapeString(model.BoundedContext) + "\",");
        sb.AppendLine("        Projections: new List<string> { typeof(" + model.TypeName + ").FullName! },");
        sb.AppendLine("        Commands: new List<string>());");
        sb.AppendLine();

        // RegisterDomain method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers this projection's domain metadata with the composition registry.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"registry\">The front composer registry.</param>");
        sb.AppendLine("    public static void RegisterDomain(IFrontComposerRegistry registry)");
        sb.AppendLine("    {");
        sb.AppendLine("        registry.RegisterDomain(Manifest);");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EscapeString(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t")
            .Replace("\0", "\\0");
    }
}
